function f = f(in1,Ts)
%F
%    F = F(IN1,TS)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    14-May-2018 10:55:32

dpsi = in1(40,:);
dx = in1(37,:);
dy = in1(38,:);
dz = in1(39,:);
eta11 = in1(1,:);
eta12 = in1(2,:);
eta13 = in1(3,:);
eta14 = in1(4,:);
eta15 = in1(5,:);
eta16 = in1(6,:);
eta21 = in1(19,:);
eta22 = in1(20,:);
eta23 = in1(21,:);
eta24 = in1(22,:);
eta25 = in1(23,:);
eta26 = in1(24,:);
v11 = in1(7,:);
v12 = in1(8,:);
v13 = in1(9,:);
v14 = in1(10,:);
v15 = in1(11,:);
v16 = in1(12,:);
v21 = in1(25,:);
v22 = in1(26,:);
v23 = in1(27,:);
v24 = in1(28,:);
v25 = in1(29,:);
v26 = in1(30,:);
v1_t1 = in1(13,:);
v1_t2 = in1(14,:);
v1_t3 = in1(15,:);
v1_t4 = in1(16,:);
v1_t5 = in1(17,:);
v1_t6 = in1(18,:);
v2_t1 = in1(31,:);
v2_t2 = in1(32,:);
v2_t3 = in1(33,:);
v2_t4 = in1(34,:);
v2_t5 = in1(35,:);
v2_t6 = in1(36,:);
t2 = cos(eta15);
t3 = 1.0./t2;
t4 = cos(eta16);
t5 = sin(eta16);
t6 = sin(eta15);
t7 = cos(eta25);
t8 = 1.0./t7;
t9 = cos(eta26);
t10 = sin(eta26);
t11 = sin(eta25);
f = [eta11+Ts.*v11;eta12+Ts.*v12;eta13+Ts.*v13;eta14+Ts.*(t3.*t4.*v14-t3.*t5.*v15);eta15+Ts.*(t4.*v15+t5.*v14);eta16+Ts.*(v16-t3.*t4.*t6.*v14+t3.*t5.*t6.*v15);v11+Ts.*v1_t1;v12+Ts.*v1_t2;v13+Ts.*v1_t3;v14+Ts.*v1_t4;v15+Ts.*v1_t5;v16+Ts.*v1_t6;v1_t1;v1_t2;v1_t3;v1_t4;v1_t5;v1_t6;eta21+Ts.*v21;eta22+Ts.*v22;eta23+Ts.*v23;eta24+Ts.*(t8.*t9.*v24-t8.*t10.*v25);eta25+Ts.*(t9.*v25+t10.*v24);eta26+Ts.*(v26-t8.*t9.*t11.*v24+t8.*t10.*t11.*v25);v21+Ts.*v2_t1;v22+Ts.*v2_t2;v23+Ts.*v2_t3;v24+Ts.*v2_t4;v25+Ts.*v2_t5;v26+Ts.*v2_t6;v2_t1;v2_t2;v2_t3;v2_t4;v2_t5;v2_t6;dx;dy;dz;dpsi];
