function hMruOne = hMruOne(in1)
%HMRUONE
%    HMRUONE = HMRUONE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    14-May-2018 10:55:47

eta11 = in1(1,:);
eta12 = in1(2,:);
eta13 = in1(3,:);
eta14 = in1(4,:);
eta15 = in1(5,:);
eta16 = in1(6,:);
v11 = in1(7,:);
v12 = in1(8,:);
v13 = in1(9,:);
v14 = in1(10,:);
v15 = in1(11,:);
v16 = in1(12,:);
hMruOne = [eta11;eta12;eta13;eta14;eta15;eta16;v11;v12;v13;v14;v15;v16];
