function hMruTwo = hMruTwo(in1)
%HMRUTWO
%    HMRUTWO = HMRUTWO(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    14-May-2018 10:55:47

eta21 = in1(19,:);
eta22 = in1(20,:);
eta23 = in1(21,:);
eta24 = in1(22,:);
eta25 = in1(23,:);
eta26 = in1(24,:);
v21 = in1(25,:);
v22 = in1(26,:);
v23 = in1(27,:);
v24 = in1(28,:);
v25 = in1(29,:);
v26 = in1(30,:);
hMruTwo = [eta21;eta22;eta23;eta24;eta25;eta26;v21;v22;v23;v24;v25;v26];
