// ****************** stdlib.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#pragma once

#include "crtdefs.h"
#include "TcDef.h"

#ifdef __cplusplus
extern "C" {
#endif
void* __cdecl malloc(size_t size);
void* __cdecl calloc(size_t nElem, size_t size);
void* __cdecl realloc(void* memblock, size_t size);
void __cdecl free(void* memblock);
#ifdef __cplusplus
}
#endif
