function f = f(in1,in2,Ts)
%F
%    F = F(IN1,IN2,TS)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    30-Jul-2018 15:56:28

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
x13 = in1(13,:);
x14 = in1(14,:);
x15 = in1(15,:);
x16 = in1(16,:);
x17 = in1(17,:);
x18 = in1(18,:);
x19 = in1(19,:);
t2 = cos(x11);
t3 = sin(x10);
t4 = cos(x10);
t5 = 1.0./x14;
t6 = sin(x11);
f = [x1+Ts.*x4;x2+Ts.*x5;x3+Ts.*x6;x4+Ts.*x7;x5+Ts.*x8;x6+Ts.*x9;x7;x8;x9;x10+Ts.*x12;x11+Ts.*x13;x12-Ts.*(t5.*(t2.*t3.*(9.81e2./1.0e2)-t4.*x7+x12.*x15.*2.0-t2.*t3.*x9-t3.*t6.*x8+t3.*t4.*x13.^2.*x14)+x12.*x19);x13-Ts.*(x13.*x19+(t5.*(t6.*(9.81e2./1.0e2)+t2.*x8-t6.*x9+t4.*x13.*x15.*2.0-t3.*x12.*x13.*x14.*2.0))./t4);x14+Ts.*x15;x15;x16;x17;x18;x19];
