function h = h(in1)
%H
%    H = H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    30-Jul-2018 15:56:28

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x10 = in1(10,:);
x11 = in1(11,:);
x14 = in1(14,:);
x15 = in1(15,:);
x16 = in1(16,:);
x17 = in1(17,:);
x18 = in1(18,:);
t2 = cos(x10);
h = [x1;x2;x3;x4;x5;x6;x14;x15;x1+x16-x14.*sin(x10);x2+x17+t2.*x14.*sin(x11);x3+x18+t2.*x14.*cos(x11)];
