<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="FB_RemoteInterface" Id="{876c2b91-df3c-4683-9fd3-7a3048a99a09}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_RemoteInterface
VAR_INPUT
	txUdp : ST_TxUdpRemote;
END_VAR
VAR_OUTPUT
	rxUdp : ST_RxUdpRemote;
END_VAR
VAR
	// Udp connection
	{attribute 'tc_no_symbol'}
	udpClient : FB_UdpClient('', 0, 0, 0, 0, 0, 0);	// Dummy constructor
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Update Udp client
udpClient();]]></ST>
    </Implementation>
    <Method Name="FB_exit" Id="{8f02c622-0e73-4bd7-94f0-589e37e92221}">
      <Declaration><![CDATA[METHOD FB_exit : BOOL
VAR_INPUT
	bInCopyCode : BOOL; // if TRUE, the exit method is called for exiting an instance that is copied afterwards (online change).
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{6ef0140a-757a-433f-b860-bfc093351cf9}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	
	// Init variables
	_remoteIpAddr : T_Ipv4Addr;
	_remotePort : UINT;
	_localPort : UINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// Initilize udpClient
udpClient.FB_init(
	bInitRetains,
	bInCopyCode,
	_remoteIpAddr,
	_remotePort,
	_localPort,
	SIZEOF(rxUdp),
	ADR(rxUdp),
	SIZEOF(txUdp),
	ADR(txUdp)
);]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_reinit" Id="{4fd06a20-81e1-4ab4-9bba-7c79e2cd39ec}">
      <Declaration><![CDATA[METHOD FB_reinit : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_RemoteInterface">
      <LineId Id="9" Count="0" />
      <LineId Id="17" Count="0" />
    </LineIds>
    <LineIds Name="FB_RemoteInterface.FB_exit">
      <LineId Id="6" Count="0" />
    </LineIds>
    <LineIds Name="FB_RemoteInterface.FB_init">
      <LineId Id="13" Count="10" />
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_RemoteInterface.FB_reinit">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>