<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_StewartInterface" Id="{bc1132f0-30a6-41f8-8816-fcd499a79e5c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_StewartInterface
VAR_INPUT
	// Stewart Operation 
	bStop : BOOL;
	bReset : BOOL;
	bStart : BOOL;
	eModeCmd : E_StewartMode;
	
END_VAR
VAR_OUTPUT
	bError : BOOL;
	bBusy : BOOL := FALSE;
	bReady : BOOL := FALSE;
	eState : E_StewartState;
	eStatus : E_StewartStatus;
	eOpMode : E_StewartOpMode;
	eMode : E_StewartMode;
	
	// Feedback data
	eta : ARRAY [0..5] OF LREAL;
	eta_t : ARRAY [0..5] OF LREAL;
	eta_tt : ARRAY [0..5] OF LREAL;
	
END_VAR
VAR	
	// Ship simulator data
	etaSim AT %I* : ARRAY [0..5] OF LREAL;
	
	// Sine wave data
	etaSine : ARRAY [0..5] OF LREAL;
	etaSine_t : ARRAY [0..5] OF LREAL;
	etaSine_tt : ARRAY [0..5] OF LREAL;
	
	// Udp connection
	udpClient : FB_UdpClientRT('', 0, 0, 0, 0, 0, 0);	// Dummy constructor

	{attribute 'tc_no_symbol'}
	eCmnd : E_StewartCommand;
	{attribute 'tc_no_symbol'}
	rxUdp : ST_RxUdpStewart;
	{attribute 'tc_no_symbol'}
	txUdp : ST_TxUdpStewart;
	
	// Stewart setpoint
	etaRef : ARRAY [0..5] OF LREAL;
	etaRef_t : ARRAY [0..5] OF LREAL;
	etaRef_tt : ARRAY [0..5] OF LREAL;
	
	// Hmi connection
	txHmi : ST_TxHmiStewart;
	
	// Udp activity monitoring
	bActive : BOOL;
	frame : UDINT := 0;
	frameOld : UDINT := 0;
	frameLoss : UDINT := 0;
	
	// Task monitoring
	fbGetCurrentTaskIdx : GETCURTASKINDEX;
	bCycleTimeExceeded : BOOL;
	nCycleCount : UDINT;
	Ts : LREAL;
	t : LREAL := 0.0;
	
	// Sine Generator Settings
	sineAmplitude : ARRAY [0..5] OF LREAL := [0, 0, 0.2, 2.0/180.0*PI, 2.0/180.0*PI, 0];
	sineOmega : ARRAY [0..5] OF LREAL := [0.6283, 0.6283, 0.6283, 0.6283, 0.6283, 0.6283];
	sinePhase : ARRAY [0..5] OF LREAL;

	// Zero eta
	{attribute 'tc_no_symbol'}
	etaZeros : ARRAY [0..5] OF LREAL;
	
	// Max/min settings
	etaRefMin : ARRAY [0..5] OF LREAL := [-0.2, -0.2, -0.4, -5.0/180.0*pi, -5.0/180.0*pi, -5.0/180.0*pi];
	etaRefMax : ARRAY [0..5] OF LREAL := [0.2, 0.2, 0.4, 5.0/180.0*pi, 5.0/180.0*pi, 5.0/180.0*pi];
END_VAR]]></Declaration>
    <Implementation>
      <StateChart>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="UMLStateChart">
              <v n="Abortable">true</v>
              <v n="UseVarInstForMethods">false</v>
              <v n="StatesCount">14</v>
              <v n="HistoryCount">0</v>
              <v n="TransitionsCount">47</v>
              <v n="RegionsCount">0</v>
              <v n="TracesCount">0</v>
              <v n="StatesInitString">":=[(ID := 1, Name := 'GeneratedStartStateForAbort1', StateType := _UML_SC_StateTypes.InitialState, StartOfTransitionIndex := 1, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 2, Name := 'GeneratedFinalStateForAbort1', StateType := _UML_SC_StateTypes.FinalState, StartOfTransitionIndex := 0, OutGoingTransitionsCount := 0, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 3, Name := 'TO_SETTLED', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 2, OutGoingTransitionsCount := 5, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := False, HasExitAction := False) , 
(ID := 4, Name := 'StartState2', StateType := _UML_SC_StateTypes.FastState, StartOfTransitionIndex := 7, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 5, Name := 'STOPP', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 8, OutGoingTransitionsCount := 2, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := False) , 
(ID := 6, Name := 'GENERATOR', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 10, OutGoingTransitionsCount := 5, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := True) , 
(ID := 7, Name := 'NEUTRAL', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 15, OutGoingTransitionsCount := 8, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := True) , 
(ID := 8, Name := 'StartState1', StateType := _UML_SC_StateTypes.FastState, StartOfTransitionIndex := 23, OutGoingTransitionsCount := 1, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := False, HasDoAction := False, HasExitAction := False) , 
(ID := 9, Name := 'FILE', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 24, OutGoingTransitionsCount := 5, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := True) , 
(ID := 10, Name := 'SETTLED', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 29, OutGoingTransitionsCount := 5, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := True) , 
(ID := 11, Name := 'TO_NEUTRAL', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 34, OutGoingTransitionsCount := 5, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := False, HasExitAction := False) , 
(ID := 12, Name := 'StatusCheck', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 39, OutGoingTransitionsCount := 2, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := True) , 
(ID := 13, Name := 'ERROR', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 41, OutGoingTransitionsCount := 2, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := False) , 
(ID := 14, Name := 'SIMULATION', StateType := _UML_SC_StateTypes.SlowState, StartOfTransitionIndex := 43, OutGoingTransitionsCount := 5, RegionCount := 0, RegionStartIndex := 0, RegionEndIndex := 0, CompletionTransitionID := 0, MaxDoCycles := 32766, HasEntryAction := True, HasDoAction := True, HasExitAction := True) ];
"</v>
              <v n="TransitionsInitString">":=[(ID := 1, StartStateID := 1, EndStateID := 8, Priority := 1, HasAction := False, IsCompletion := True,IsPseudoException := False,IsException := False), 
(ID := 2, StartStateID := 3, EndStateID := 12, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 3, StartStateID := 3, EndStateID := 5, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 4, StartStateID := 3, EndStateID := 12, Priority := 3, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 5, StartStateID := 3, EndStateID := 13, Priority := 4, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 6, StartStateID := 3, EndStateID := 10, Priority := 5, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 7, StartStateID := 4, EndStateID := 10, Priority := 1, HasAction := False, IsCompletion := True,IsPseudoException := False,IsException := False), 
(ID := 8, StartStateID := 5, EndStateID := 2, Priority := 1, HasAction := True, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 9, StartStateID := 5, EndStateID := 4, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 10, StartStateID := 6, EndStateID := 12, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 11, StartStateID := 6, EndStateID := 5, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 12, StartStateID := 6, EndStateID := 12, Priority := 3, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 13, StartStateID := 6, EndStateID := 13, Priority := 4, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 14, StartStateID := 6, EndStateID := 11, Priority := 5, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 15, StartStateID := 7, EndStateID := 12, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 16, StartStateID := 7, EndStateID := 5, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 17, StartStateID := 7, EndStateID := 12, Priority := 3, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 18, StartStateID := 7, EndStateID := 13, Priority := 4, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 19, StartStateID := 7, EndStateID := 9, Priority := 5, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 20, StartStateID := 7, EndStateID := 6, Priority := 6, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 21, StartStateID := 7, EndStateID := 14, Priority := 7, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 22, StartStateID := 7, EndStateID := 3, Priority := 8, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 23, StartStateID := 8, EndStateID := 12, Priority := 1, HasAction := False, IsCompletion := True,IsPseudoException := False,IsException := False), 
(ID := 24, StartStateID := 9, EndStateID := 12, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 25, StartStateID := 9, EndStateID := 5, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 26, StartStateID := 9, EndStateID := 12, Priority := 3, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 27, StartStateID := 9, EndStateID := 13, Priority := 4, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 28, StartStateID := 9, EndStateID := 11, Priority := 5, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 29, StartStateID := 10, EndStateID := 12, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 30, StartStateID := 10, EndStateID := 5, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 31, StartStateID := 10, EndStateID := 12, Priority := 3, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 32, StartStateID := 10, EndStateID := 13, Priority := 4, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 33, StartStateID := 10, EndStateID := 11, Priority := 5, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 34, StartStateID := 11, EndStateID := 12, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 35, StartStateID := 11, EndStateID := 5, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 36, StartStateID := 11, EndStateID := 12, Priority := 3, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 37, StartStateID := 11, EndStateID := 13, Priority := 4, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 38, StartStateID := 11, EndStateID := 7, Priority := 5, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 39, StartStateID := 12, EndStateID := 2, Priority := 1, HasAction := True, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 40, StartStateID := 12, EndStateID := 4, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 41, StartStateID := 13, EndStateID := 2, Priority := 1, HasAction := True, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 42, StartStateID := 13, EndStateID := 4, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False), 
(ID := 43, StartStateID := 14, EndStateID := 12, Priority := 1, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 44, StartStateID := 14, EndStateID := 5, Priority := 2, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 45, StartStateID := 14, EndStateID := 12, Priority := 3, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 46, StartStateID := 14, EndStateID := 13, Priority := 4, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := True), 
(ID := 47, StartStateID := 14, EndStateID := 11, Priority := 5, HasAction := False, IsCompletion := False,IsPseudoException := False,IsException := False)];
"</v>
              <v n="RegionsInitString">""</v>
              <v n="StateNamesString">"GeneratedStartStateForAbort1:INT:=1;
GeneratedFinalStateForAbort1:INT:=2;
TO_SETTLED:INT:=3;
StartState2:INT:=4;
STOPP:INT:=5;
GENERATOR:INT:=6;
NEUTRAL:INT:=7;
StartState1:INT:=8;
FILE:INT:=9;
SETTLED:INT:=10;
TO_NEUTRAL:INT:=11;
StatusCheck:INT:=12;
ERROR:INT:=13;
SIMULATION:INT:=14;
"</v>
              <n n="StateNamesInitString" />
              <v n="ForceActionRemove">false</v>
              <d n="RegionsWithStartStatesTable" t="Hashtable" ckt="Guid" cvt="Int32">
                <v>910c26a1-8756-4511-824d-75f2b874d655</v>
                <v>1</v>
                <v>00000000-0000-0000-0000-000000000000</v>
                <v>1</v>
              </d>
              <d n="RegionsWithHistoryStatesTable" t="Hashtable" ckt="Guid" cvt="Int32">
                <v>00000000-0000-0000-0000-000000000000</v>
                <v>1</v>
              </d>
              <d n="RegionsWithEndStatesTable" t="Hashtable" />
              <n n="BreakPointGuids" />
              <v n="UmlEditorRestrictions" t="EditorRestrictions">None</v>
              <v n="DUTObjectGuid">{a8d4f693-94b0-4d80-b8c8-abae0c802c76}</v>
              <v n="DUTNamesObjectGuid">{2fcaed78-4c5f-491d-af57-14a8b8e8f4ae}</v>
              <v n="TraceObject">{00000000-0000-0000-0000-000000000000}</v>
              <v n="IsCompiling">false</v>
              <v n="HideLanguageModel">false</v>
              <v n="DefaultStateSizeX">62</v>
              <v n="DefaultStateSizeY">32</v>
              <v n="SuppressAutomaticLibraryLoading">false</v>
              <v n="DiagramName">"ST_StewartInterface"</v>
              <v n="DiagramGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
              <v n="IsActionRemoving">false</v>
              <v n="ForceRepaintDiagram">false</v>
              <v n="Documentationdiagram">false</v>
              <v n="ApplicationGuidForDiagram">{00000000-0000-0000-0000-000000000000}</v>
              <v n="AutomaticLayOutHeightSpace">0</v>
              <v n="AutomaticLayOutWidthSpace">0</v>
              <d n="ElementObjects" t="Hashtable" ckt="Guid">
                <v>49d8c493-e130-498c-8290-94cd04bb637c</v>
                <o t="UMLStateChartPseudoElement">
                  <o n="ElementVisualisation" t="UMLStateChartDiagramElementVisualisationDot">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">2</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">175</v>
                    <v n="LeftPosition">610</v>
                    <v n="WidthValue">20</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">20</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <v n="Condition">""</v>
                  <v n="HistoryType" t="HistoryTypes">None</v>
                  <v n="StateChartGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"StartState2"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartStartState</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">20</v>
                  <v n="DefaultCellSizeY">20</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{910c26a1-8756-4511-824d-75f2b874d655}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">2</v>
                  <v n="ElementObjectGuid">{49d8c493-e130-498c-8290-94cd04bb637c}</v>
                  <v n="ParentGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ContainerGuid">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                  <v n="ZOrder">324U</v>
                </o>
                <v>f5193168-3c3e-4dc1-b76d-86a7edfcc476</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"bReady := FALSE;"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"StatusCheck_DO"</v>
                  <v n="ExitActionText">"bReady := TRUE;"</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"StatusCheck_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">true</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"StatusCheck"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">36</v>
                    <v n="LeftPosition">496</v>
                    <v n="WidthValue">164</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">83</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{f5193168-3c3e-4dc1-b76d-86a7edfcc476}</v>
                  <v n="ParentGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">267U</v>
                </o>
                <v>f77eec2c-d70b-471f-bcea-4594d099fc8b</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"bReset := FALSE;"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"ERROR_DO"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"ERROR_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"ERROR"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">586</v>
                    <v n="LeftPosition">1289</v>
                    <v n="WidthValue">161</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">66</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{f77eec2c-d70b-471f-bcea-4594d099fc8b}</v>
                  <v n="ParentGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">301U</v>
                </o>
                <v>5853e86b-95e2-4f38-a240-330dc8df6d39</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"bStart := FALSE;"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"GENERATOR_DO"</v>
                  <v n="ExitActionText">"bStart := FALSE;"</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"GENERATOR_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">true</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"GENERATOR"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">578</v>
                    <v n="LeftPosition">810</v>
                    <v n="WidthValue">155</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">83</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{910c26a1-8756-4511-824d-75f2b874d655}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{5853e86b-95e2-4f38-a240-330dc8df6d39}</v>
                  <v n="ParentGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ContainerGuid">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">325U</v>
                </o>
                <v>fa206268-213c-4c42-8b42-8322357a29ba</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"bStart := FALSE;"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"SIMULATION_DO"</v>
                  <v n="ExitActionText">"bStart := FALSE;"</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"SIMULATION_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">true</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"SIMULATION"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">602</v>
                    <v n="LeftPosition">49</v>
                    <v n="WidthValue">155</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">83</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{910c26a1-8756-4511-824d-75f2b874d655}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{fa206268-213c-4c42-8b42-8322357a29ba}</v>
                  <v n="ParentGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ContainerGuid">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">326U</v>
                </o>
                <v>4e5e080a-fccb-4078-89e3-8ba156a63a91</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"bReset := FALSE;"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"STOPP_DO"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"STOPP_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"STOPP"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">271</v>
                    <v n="LeftPosition">1271</v>
                    <v n="WidthValue">161</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">66</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{4e5e080a-fccb-4078-89e3-8ba156a63a91}</v>
                  <v n="ParentGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">300U</v>
                </o>
                <v>897f99e0-ecbf-40c3-baf9-a39f7de4af68</v>
                <o t="UMLStateChartPseudoElement">
                  <o n="ElementVisualisation" t="UMLStateChartDiagramElementVisualisationDot">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">10</v>
                    <v n="LeftPosition">395</v>
                    <v n="WidthValue">20</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">20</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <v n="Condition">""</v>
                  <v n="HistoryType" t="HistoryTypes">None</v>
                  <v n="StateChartGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"StartState1"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartStartState</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">20</v>
                  <v n="DefaultCellSizeY">20</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{897f99e0-ecbf-40c3-baf9-a39f7de4af68}</v>
                  <v n="ParentGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                  <v n="ZOrder">268U</v>
                </o>
                <v>113074f3-7280-4734-adb6-ec5d4d75ccf4</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"eCmnd := E_StewartCommand.TO_SETTLED;"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"TO_SETTLED"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">368</v>
                    <v n="LeftPosition">607</v>
                    <v n="WidthValue">302</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">49</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{910c26a1-8756-4511-824d-75f2b874d655}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{113074f3-7280-4734-adb6-ec5d4d75ccf4}</v>
                  <v n="ParentGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ContainerGuid">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">327U</v>
                </o>
                <v>dd41abb1-cf8c-4daa-a515-0826b419d6de</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"bBusy := FALSE;"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"SETTLED_DO"</v>
                  <v n="ExitActionText">"bBusy := TRUE;"</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"SETTLED_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">true</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"SETTLED"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">217</v>
                    <v n="LeftPosition">510</v>
                    <v n="WidthValue">156</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">83</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{910c26a1-8756-4511-824d-75f2b874d655}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{dd41abb1-cf8c-4daa-a515-0826b419d6de}</v>
                  <v n="ParentGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ContainerGuid">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">328U</v>
                </o>
                <v>b194dc9d-1e2b-4eca-a1c4-4e5f60544940</v>
                <o t="UMLStateChartComposite">
                  <v n="AllowCompositeActions">true</v>
                  <v n="ExecuteDoActionsWhenNestedCompositesAreActive">false</v>
                  <o n="ElementVisualisation" t="UMLCompositeVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">160</v>
                    <v n="LeftPosition">30</v>
                    <v n="WidthValue">1156</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">738</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l n="Areas" t="ArrayList" cet="UMLArea">
                    <o>
                      <v n="Elementguid">{910c26a1-8756-4511-824d-75f2b874d655}</v>
                      <v n="Name">"Region0"</v>
                      <v n="Position">0</v>
                      <v n="Priority">0</v>
                    </o>
                  </l>
                  <v n="StateChartGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"Execute"</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"Execute"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"Stewart"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartComposite</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">150</v>
                  <v n="DefaultCellSizeY">100</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <v n="ParentGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-989556</v>
                  <v n="ZOrder">323U</v>
                </o>
                <v>b8bb5204-9a6f-4b66-bbbe-90fa86a2fb7f</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"bStart := FALSE"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"FILE_DO"</v>
                  <v n="ExitActionText">"bStart := FALSE"</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"FILE_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">true</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"FILE"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">768</v>
                    <v n="LeftPosition">528</v>
                    <v n="WidthValue">152</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">83</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{910c26a1-8756-4511-824d-75f2b874d655}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{b8bb5204-9a6f-4b66-bbbe-90fa86a2fb7f}</v>
                  <v n="ParentGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ContainerGuid">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">329U</v>
                </o>
                <v>73277216-de9b-49fb-b8bc-bb0ff8b88c9a</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"bBusy := FALSE;"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">"NEUTRAL_DO"</v>
                  <v n="ExitActionText">"bBusy := TRUE;"</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">"NEUTRAL_DO"</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">true</v>
                  <v n="HasExitAction">true</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"NEUTRAL"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">477</v>
                    <v n="LeftPosition">510</v>
                    <v n="WidthValue">156</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">83</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{910c26a1-8756-4511-824d-75f2b874d655}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{73277216-de9b-49fb-b8bc-bb0ff8b88c9a}</v>
                  <v n="ParentGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ContainerGuid">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">330U</v>
                </o>
                <v>ee59122d-01c0-492f-bbb7-6075eabcb69b</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">"eCmnd := E_StewartCommand.TO_NEUTRAL"</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">true</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"TO_NEUTRAL"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">327</v>
                    <v n="LeftPosition">210</v>
                    <v n="WidthValue">301</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">49</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{910c26a1-8756-4511-824d-75f2b874d655}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{ee59122d-01c0-492f-bbb7-6075eabcb69b}</v>
                  <v n="ParentGuid">{bc1132f0-30a6-41f8-8816-fcd499a79e5c}</v>
                  <v n="ContainerGuid">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">331U</v>
                </o>
              </d>
              <v n="FirstPaint">true</v>
              <v n="NextElementID">0</v>
              <d n="UMLRelationObjects" t="Hashtable" ckt="Guid" cvt="UMLRelation">
                <v>9db889f9-8d1a-440e-a22c-5ba0d5d7cc3e</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <v n="HighlightedLine">true</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"NOT bActive"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">48</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{f5193168-3c3e-4dc1-b76d-86a7edfcc476}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{9db889f9-8d1a-440e-a22c-5ba0d5d7cc3e}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-139</v>
                      <v>ActionPosition</v>
                      <v>279</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-34</v>
                      <v>ActionPosition</v>
                      <v>-17</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">892</v>
                      <v n="AnchorTopPosition">155</v>
                      <v n="AnchorRelationID">{9db889f9-8d1a-440e-a22c-5ba0d5d7cc3e}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">655</v>
                      <v n="AnchorTopPosition">104</v>
                      <v n="AnchorRelationID">{9db889f9-8d1a-440e-a22c-5ba0d5d7cc3e}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">892</v>
                        <v n="AnchorTopPosition">104</v>
                        <v n="AnchorRelationID">{9db889f9-8d1a-440e-a22c-5ba0d5d7cc3e}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{9db889f9-8d1a-440e-a22c-5ba0d5d7cc3e}</v>
                  <v n="RelationGuid">{9db889f9-8d1a-440e-a22c-5ba0d5d7cc3e}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">ExceptionTransition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>49aa1ff1-cdad-45a8-a2e9-67a019ddd9b5</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{73277216-de9b-49fb-b8bc-bb0ff8b88c9a}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"eModeCmd = E_StewartMode.GENERATOR"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">38</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{5853e86b-95e2-4f38-a240-330dc8df6d39}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{49aa1ff1-cdad-45a8-a2e9-67a019ddd9b5}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>129</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-2</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">661</v>
                      <v n="AnchorTopPosition">522</v>
                      <v n="AnchorRelationID">{49aa1ff1-cdad-45a8-a2e9-67a019ddd9b5}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">902</v>
                      <v n="AnchorTopPosition">573</v>
                      <v n="AnchorRelationID">{49aa1ff1-cdad-45a8-a2e9-67a019ddd9b5}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">902</v>
                        <v n="AnchorTopPosition">522</v>
                        <v n="AnchorRelationID">{49aa1ff1-cdad-45a8-a2e9-67a019ddd9b5}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{49aa1ff1-cdad-45a8-a2e9-67a019ddd9b5}</v>
                  <v n="RelationGuid">{49aa1ff1-cdad-45a8-a2e9-67a019ddd9b5}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">2</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>2</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>1c2944d6-010a-432b-b6dd-c897db58069d</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{897f99e0-ecbf-40c3-baf9-a39f7de4af68}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">268U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">""</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">43</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{f5193168-3c3e-4dc1-b76d-86a7edfcc476}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{1c2944d6-010a-432b-b6dd-c897db58069d}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">410</v>
                      <v n="AnchorTopPosition">7</v>
                      <v n="AnchorRelationID">{1c2944d6-010a-432b-b6dd-c897db58069d}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">564</v>
                      <v n="AnchorTopPosition">31</v>
                      <v n="AnchorRelationID">{1c2944d6-010a-432b-b6dd-c897db58069d}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">564</v>
                        <v n="AnchorTopPosition">7</v>
                        <v n="AnchorRelationID">{1c2944d6-010a-432b-b6dd-c897db58069d}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{1c2944d6-010a-432b-b6dd-c897db58069d}</v>
                  <v n="RelationGuid">{1c2944d6-010a-432b-b6dd-c897db58069d}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">CompletionTransition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>3ed5ca2a-d9b0-444b-b347-b6917e5ac7f9</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <v n="HighlightedLine">true</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"bStop"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">46</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{4e5e080a-fccb-4078-89e3-8ba156a63a91}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{3ed5ca2a-d9b0-444b-b347-b6917e5ac7f9}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">1181</v>
                      <v n="AnchorTopPosition">268</v>
                      <v n="AnchorRelationID">{3ed5ca2a-d9b0-444b-b347-b6917e5ac7f9}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">1266</v>
                      <v n="AnchorTopPosition">268</v>
                      <v n="AnchorRelationID">{3ed5ca2a-d9b0-444b-b347-b6917e5ac7f9}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{3ed5ca2a-d9b0-444b-b347-b6917e5ac7f9}</v>
                  <v n="RelationGuid">{3ed5ca2a-d9b0-444b-b347-b6917e5ac7f9}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">ExceptionTransition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">2</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>2</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>bc23480c-ec6c-4634-823a-89a425614cd8</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{f77eec2c-d70b-471f-bcea-4594d099fc8b}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"NOT bError"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">37</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{bc23480c-ec6c-4634-823a-89a425614cd8}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-118</v>
                      <v>ActionPosition</v>
                      <v>0</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>25</v>
                      <v>ActionPosition</v>
                      <v>20</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">1353</v>
                      <v n="AnchorTopPosition">647</v>
                      <v n="AnchorRelationID">{bc23480c-ec6c-4634-823a-89a425614cd8}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">1181</v>
                      <v n="AnchorTopPosition">687</v>
                      <v n="AnchorRelationID">{bc23480c-ec6c-4634-823a-89a425614cd8}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">1353</v>
                        <v n="AnchorTopPosition">687</v>
                        <v n="AnchorRelationID">{bc23480c-ec6c-4634-823a-89a425614cd8}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{bc23480c-ec6c-4634-823a-89a425614cd8}</v>
                  <v n="RelationGuid">{bc23480c-ec6c-4634-823a-89a425614cd8}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>cb13c4e0-3a5a-42d9-bc1a-e2c20df2dbb5</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <v n="HighlightedLine">true</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"eOpMode = E_StewartOpMode.MANUAL"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">45</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{f5193168-3c3e-4dc1-b76d-86a7edfcc476}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{cb13c4e0-3a5a-42d9-bc1a-e2c20df2dbb5}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-240</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-51</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">951</v>
                      <v n="AnchorTopPosition">155</v>
                      <v n="AnchorRelationID">{cb13c4e0-3a5a-42d9-bc1a-e2c20df2dbb5}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">655</v>
                      <v n="AnchorTopPosition">64</v>
                      <v n="AnchorRelationID">{cb13c4e0-3a5a-42d9-bc1a-e2c20df2dbb5}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">951</v>
                        <v n="AnchorTopPosition">64</v>
                        <v n="AnchorRelationID">{cb13c4e0-3a5a-42d9-bc1a-e2c20df2dbb5}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{cb13c4e0-3a5a-42d9-bc1a-e2c20df2dbb5}</v>
                  <v n="RelationGuid">{cb13c4e0-3a5a-42d9-bc1a-e2c20df2dbb5}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">ExceptionTransition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">3</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>3</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>ef2deb4c-0b59-4a14-a99e-7fb849fa7a0a</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{dd41abb1-cf8c-4daa-a515-0826b419d6de}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"eModeCmd = E_StewartMode.NEUTRAL"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">26</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{ee59122d-01c0-492f-bbb7-6075eabcb69b}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{ef2deb4c-0b59-4a14-a99e-7fb849fa7a0a}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-4</v>
                      <v>ActionPosition</v>
                      <v>0</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-9</v>
                      <v>ActionPosition</v>
                      <v>-10</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">505</v>
                      <v n="AnchorTopPosition">262</v>
                      <v n="AnchorRelationID">{ef2deb4c-0b59-4a14-a99e-7fb849fa7a0a}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">255</v>
                      <v n="AnchorTopPosition">322</v>
                      <v n="AnchorRelationID">{ef2deb4c-0b59-4a14-a99e-7fb849fa7a0a}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">255</v>
                        <v n="AnchorTopPosition">262</v>
                        <v n="AnchorRelationID">{ef2deb4c-0b59-4a14-a99e-7fb849fa7a0a}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{ef2deb4c-0b59-4a14-a99e-7fb849fa7a0a}</v>
                  <v n="RelationGuid">{ef2deb4c-0b59-4a14-a99e-7fb849fa7a0a}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>2b6f464f-6e32-4219-9491-2463a2da4da6</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{5853e86b-95e2-4f38-a240-330dc8df6d39}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"NOT (eModeCmd = E_StewartMode.GENERATOR)"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">39</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{ee59122d-01c0-492f-bbb7-6075eabcb69b}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{2b6f464f-6e32-4219-9491-2463a2da4da6}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-97</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-2</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">805</v>
                      <v n="AnchorTopPosition">627</v>
                      <v n="AnchorRelationID">{2b6f464f-6e32-4219-9491-2463a2da4da6}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">323</v>
                      <v n="AnchorTopPosition">371</v>
                      <v n="AnchorRelationID">{2b6f464f-6e32-4219-9491-2463a2da4da6}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">323</v>
                        <v n="AnchorTopPosition">627</v>
                        <v n="AnchorRelationID">{2b6f464f-6e32-4219-9491-2463a2da4da6}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{2b6f464f-6e32-4219-9491-2463a2da4da6}</v>
                  <v n="RelationGuid">{2b6f464f-6e32-4219-9491-2463a2da4da6}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>0409fd0f-eb0b-4cee-bbdc-09182c0456ea</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{b8bb5204-9a6f-4b66-bbbe-90fa86a2fb7f}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"NOT (eModeCmd = E_StewartMode.FILE)"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">50</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{ee59122d-01c0-492f-bbb7-6075eabcb69b}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{0409fd0f-eb0b-4cee-bbdc-09182c0456ea}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-42</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>29</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">523</v>
                      <v n="AnchorTopPosition">800</v>
                      <v n="AnchorRelationID">{0409fd0f-eb0b-4cee-bbdc-09182c0456ea}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">303</v>
                      <v n="AnchorTopPosition">371</v>
                      <v n="AnchorRelationID">{0409fd0f-eb0b-4cee-bbdc-09182c0456ea}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">303</v>
                        <v n="AnchorTopPosition">800</v>
                        <v n="AnchorRelationID">{0409fd0f-eb0b-4cee-bbdc-09182c0456ea}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{0409fd0f-eb0b-4cee-bbdc-09182c0456ea}</v>
                  <v n="RelationGuid">{0409fd0f-eb0b-4cee-bbdc-09182c0456ea}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>032a32cf-8d11-4b72-b1bd-1f23a26cce59</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <v n="HighlightedLine">true</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"bError"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">36</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{f77eec2c-d70b-471f-bcea-4594d099fc8b}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{032a32cf-8d11-4b72-b1bd-1f23a26cce59}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">1181</v>
                      <v n="AnchorTopPosition">602</v>
                      <v n="AnchorRelationID">{032a32cf-8d11-4b72-b1bd-1f23a26cce59}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">1284</v>
                      <v n="AnchorTopPosition">602</v>
                      <v n="AnchorRelationID">{032a32cf-8d11-4b72-b1bd-1f23a26cce59}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{032a32cf-8d11-4b72-b1bd-1f23a26cce59}</v>
                  <v n="RelationGuid">{032a32cf-8d11-4b72-b1bd-1f23a26cce59}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">ExceptionTransition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">4</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>4</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>97a81f28-c7c4-417e-a904-557128895189</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{f5193168-3c3e-4dc1-b76d-86a7edfcc476}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"eOpMode = E_StewartOpMode.NORMAL AND bActive"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">44</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{97a81f28-c7c4-417e-a904-557128895189}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-363</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>9</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">570</v>
                      <v n="AnchorTopPosition">114</v>
                      <v n="AnchorRelationID">{97a81f28-c7c4-417e-a904-557128895189}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">570</v>
                      <v n="AnchorTopPosition">155</v>
                      <v n="AnchorRelationID">{97a81f28-c7c4-417e-a904-557128895189}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{97a81f28-c7c4-417e-a904-557128895189}</v>
                  <v n="RelationGuid">{97a81f28-c7c4-417e-a904-557128895189}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>623679c3-f2c6-4ab4-8028-9537039276db</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{fa206268-213c-4c42-8b42-8322357a29ba}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"NOT (eModeCmd = E_StewartMode.SIMULATION)"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">34</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{ee59122d-01c0-492f-bbb7-6075eabcb69b}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{623679c3-f2c6-4ab4-8028-9537039276db}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-39</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-22</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">74</v>
                      <v n="AnchorTopPosition">597</v>
                      <v n="AnchorRelationID">{623679c3-f2c6-4ab4-8028-9537039276db}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">205</v>
                      <v n="AnchorTopPosition">345</v>
                      <v n="AnchorRelationID">{623679c3-f2c6-4ab4-8028-9537039276db}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">74</v>
                        <v n="AnchorTopPosition">345</v>
                        <v n="AnchorRelationID">{623679c3-f2c6-4ab4-8028-9537039276db}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{623679c3-f2c6-4ab4-8028-9537039276db}</v>
                  <v n="RelationGuid">{623679c3-f2c6-4ab4-8028-9537039276db}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>ffb6e2e9-64bc-4cf1-a6b2-65c9e36d4ee7</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{4e5e080a-fccb-4078-89e3-8ba156a63a91}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"NOT bStop"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">47</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{b194dc9d-1e2b-4eca-a1c4-4e5f60544940}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{ffb6e2e9-64bc-4cf1-a6b2-65c9e36d4ee7}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-119</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>28</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">1338</v>
                      <v n="AnchorTopPosition">332</v>
                      <v n="AnchorRelationID">{ffb6e2e9-64bc-4cf1-a6b2-65c9e36d4ee7}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">1181</v>
                      <v n="AnchorTopPosition">377</v>
                      <v n="AnchorRelationID">{ffb6e2e9-64bc-4cf1-a6b2-65c9e36d4ee7}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">1338</v>
                        <v n="AnchorTopPosition">377</v>
                        <v n="AnchorRelationID">{ffb6e2e9-64bc-4cf1-a6b2-65c9e36d4ee7}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{ffb6e2e9-64bc-4cf1-a6b2-65c9e36d4ee7}</v>
                  <v n="RelationGuid">{ffb6e2e9-64bc-4cf1-a6b2-65c9e36d4ee7}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>f096a2e6-f660-4766-b0b1-5571bfa534c6</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{ee59122d-01c0-492f-bbb7-6075eabcb69b}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"eState = E_StewartState.NEUTRAL"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">27</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{73277216-de9b-49fb-b8bc-bb0ff8b88c9a}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{f096a2e6-f660-4766-b0b1-5571bfa534c6}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-72</v>
                      <v>ActionPosition</v>
                      <v>5</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>88</v>
                      <v>ActionPosition</v>
                      <v>12</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">506</v>
                      <v n="AnchorTopPosition">352</v>
                      <v n="AnchorRelationID">{f096a2e6-f660-4766-b0b1-5571bfa534c6}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">535</v>
                      <v n="AnchorTopPosition">472</v>
                      <v n="AnchorRelationID">{f096a2e6-f660-4766-b0b1-5571bfa534c6}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">535</v>
                        <v n="AnchorTopPosition">352</v>
                        <v n="AnchorRelationID">{f096a2e6-f660-4766-b0b1-5571bfa534c6}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{f096a2e6-f660-4766-b0b1-5571bfa534c6}</v>
                  <v n="RelationGuid">{f096a2e6-f660-4766-b0b1-5571bfa534c6}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>b916ffcf-86cf-4922-b33d-62dd98fd491e</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{49d8c493-e130-498c-8290-94cd04bb637c}</v>
                  <v n="HighlightedLine">true</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">""</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">2</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{dd41abb1-cf8c-4daa-a515-0826b419d6de}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{b916ffcf-86cf-4922-b33d-62dd98fd491e}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" />
                    <d n="flagsY" t="Hashtable" />
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">605</v>
                      <v n="AnchorTopPosition">180</v>
                      <v n="AnchorRelationID">{b916ffcf-86cf-4922-b33d-62dd98fd491e}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">574</v>
                      <v n="AnchorTopPosition">212</v>
                      <v n="AnchorRelationID">{b916ffcf-86cf-4922-b33d-62dd98fd491e}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">574</v>
                        <v n="AnchorTopPosition">180</v>
                        <v n="AnchorRelationID">{b916ffcf-86cf-4922-b33d-62dd98fd491e}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{b916ffcf-86cf-4922-b33d-62dd98fd491e}</v>
                  <v n="RelationGuid">{b916ffcf-86cf-4922-b33d-62dd98fd491e}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">CompletionTransition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>c31659c7-1d4e-4e22-921c-8e067df09d02</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{73277216-de9b-49fb-b8bc-bb0ff8b88c9a}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"eModeCmd = E_StewartMode.SETTLED"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">28</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{113074f3-7280-4734-adb6-ec5d4d75ccf4}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{c31659c7-1d4e-4e22-921c-8e067df09d02}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>7</v>
                      <v>ActionPosition</v>
                      <v>10</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>5</v>
                      <v>ActionPosition</v>
                      <v>0</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">631</v>
                      <v n="AnchorTopPosition">472</v>
                      <v n="AnchorRelationID">{c31659c7-1d4e-4e22-921c-8e067df09d02}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">631</v>
                      <v n="AnchorTopPosition">412</v>
                      <v n="AnchorRelationID">{c31659c7-1d4e-4e22-921c-8e067df09d02}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{c31659c7-1d4e-4e22-921c-8e067df09d02}</v>
                  <v n="RelationGuid">{c31659c7-1d4e-4e22-921c-8e067df09d02}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">4</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>4</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>d36d85b5-be19-45ab-90d8-f522bcc2e6e5</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{113074f3-7280-4734-adb6-ec5d4d75ccf4}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"eState = E_StewartState.SETTLED"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">29</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{dd41abb1-cf8c-4daa-a515-0826b419d6de}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{d36d85b5-be19-45ab-90d8-f522bcc2e6e5}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-160</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-57</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">870</v>
                      <v n="AnchorTopPosition">363</v>
                      <v n="AnchorRelationID">{d36d85b5-be19-45ab-90d8-f522bcc2e6e5}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">661</v>
                      <v n="AnchorTopPosition">262</v>
                      <v n="AnchorRelationID">{d36d85b5-be19-45ab-90d8-f522bcc2e6e5}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">870</v>
                        <v n="AnchorTopPosition">262</v>
                        <v n="AnchorRelationID">{d36d85b5-be19-45ab-90d8-f522bcc2e6e5}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">false</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{d36d85b5-be19-45ab-90d8-f522bcc2e6e5}</v>
                  <v n="RelationGuid">{d36d85b5-be19-45ab-90d8-f522bcc2e6e5}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>7dc0ac2b-166e-4c9d-9d8a-49a838b42ab2</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{73277216-de9b-49fb-b8bc-bb0ff8b88c9a}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <n n="ActionName" />
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"eModeCmd = E_StewartMode.FILE"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">49</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{b8bb5204-9a6f-4b66-bbbe-90fa86a2fb7f}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{7dc0ac2b-166e-4c9d-9d8a-49a838b42ab2}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>4</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>72</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">599</v>
                      <v n="AnchorTopPosition">555</v>
                      <v n="AnchorRelationID">{7dc0ac2b-166e-4c9d-9d8a-49a838b42ab2}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">1</v>
                      <v n="AnchorLeftPosition">599</v>
                      <v n="AnchorTopPosition">763</v>
                      <v n="AnchorRelationID">{7dc0ac2b-166e-4c9d-9d8a-49a838b42ab2}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">1</v>
                    <d n="AnchorPoints" t="Hashtable" />
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{7dc0ac2b-166e-4c9d-9d8a-49a838b42ab2}</v>
                  <v n="RelationGuid">{7dc0ac2b-166e-4c9d-9d8a-49a838b42ab2}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">1</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>1</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
                <v>c2cb57a3-218c-4c6b-89e7-3f3547cb45bc</v>
                <o>
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="StartUMLElement">{73277216-de9b-49fb-b8bc-bb0ff8b88c9a}</v>
                  <v n="HighlightedLine">false</v>
                  <v n="ZOrder">323U</v>
                  <v n="SpecialHandling">false</v>
                  <v n="ActionLocalVariableName">""</v>
                  <v n="ActionParametersString">""</v>
                  <v n="ActionName">""</v>
                  <v n="ActionText">""</v>
                  <v n="InjectedActionCode">""</v>
                  <v n="ActionTextLength">100</v>
                  <v n="ConditionText">"eModeCmd = E_StewartMode.SIMULATION"</v>
                  <v n="LengthConditionText">100</v>
                  <v n="RelationID">32</v>
                  <v n="TriggerlessStatechartTransition">true</v>
                  <v n="EndUMLElement">{fa206268-213c-4c42-8b42-8322357a29ba}</v>
                  <o n="UMLRelationVisualisation" t="UMLRelationVisualisation">
                    <v n="RelationID">{c2cb57a3-218c-4c6b-89e7-3f3547cb45bc}</v>
                    <v n="FlagPosition" t="Double">0.5</v>
                    <d n="flagsX" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>-40</v>
                      <v>ActionPosition</v>
                      <v>-50</v>
                    </d>
                    <d n="flagsY" t="Hashtable" ckt="String" cvt="Int32">
                      <v>ConditionPosition</v>
                      <v>0</v>
                      <v>ActionPosition</v>
                      <v>-30</v>
                    </d>
                    <o n="StartAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">0</v>
                      <v n="AnchorLeftPosition">505</v>
                      <v n="AnchorTopPosition">522</v>
                      <v n="AnchorRelationID">{c2cb57a3-218c-4c6b-89e7-3f3547cb45bc}</v>
                      <v n="StartAnchor">true</v>
                      <v n="EndAnchor">false</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <o n="EndAnchor" t="UMLAnchorPoint">
                      <v n="AnchorID">2</v>
                      <v n="AnchorLeftPosition">164</v>
                      <v n="AnchorTopPosition">597</v>
                      <v n="AnchorRelationID">{c2cb57a3-218c-4c6b-89e7-3f3547cb45bc}</v>
                      <v n="StartAnchor">false</v>
                      <v n="EndAnchor">true</v>
                      <v n="AnchorDockedState" t="Docked">NotDocked</v>
                    </o>
                    <v n="NextAnchorID">2</v>
                    <d n="AnchorPoints" t="Hashtable" ckt="Int32" cvt="UMLAnchorPoint">
                      <v>1</v>
                      <o>
                        <v n="AnchorID">1</v>
                        <v n="AnchorLeftPosition">164</v>
                        <v n="AnchorTopPosition">522</v>
                        <v n="AnchorRelationID">{c2cb57a3-218c-4c6b-89e7-3f3547cb45bc}</v>
                        <v n="StartAnchor">false</v>
                        <v n="EndAnchor">false</v>
                        <v n="AnchorDockedState" t="Docked">NotDocked</v>
                      </o>
                    </d>
                    <v n="RelationIsLinear">true</v>
                    <v n="RelationIsFreeHand">false</v>
                  </o>
                  <v n="ReferenceGuid">{c2cb57a3-218c-4c6b-89e7-3f3547cb45bc}</v>
                  <v n="RelationGuid">{c2cb57a3-218c-4c6b-89e7-3f3547cb45bc}</v>
                  <v n="RelationName">""</v>
                  <n n="RelationStereotypes" />
                  <v n="RelationType" t="RelationTypes">Transition</v>
                  <v n="IsReferenceTo">false</v>
                  <v n="StartElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="Priority">3</v>
                  <v n="GeneratesCode">false</v>
                  <v n="StartElementShowArrow">false</v>
                  <v n="StartElementCardnality">""</v>
                  <v n="EndElementCardnality">""</v>
                  <v n="EndElementArrowFlag" t="ArrowTypes">Slim</v>
                  <v n="EndElementShowArrow">true</v>
                  <v n="StartElementRoleName">""</v>
                  <v n="EndElementRoleName">""</v>
                  <v n="UserCreated">true</v>
                  <v n="GeneratedByCode">false</v>
                  <v n="AllowRoutingOptimisation">false</v>
                  <d n="flagTexts" t="Hashtable" ckt="String" cvt="String">
                    <v>Priority</v>
                    <v>3</v>
                  </d>
                  <v n="Position">-1L</v>
                  <v n="PositionCounter">1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                </o>
              </d>
              <v n="NextRelationID">0</v>
              <v n="DefaultAutomaticLayout">false</v>
              <o n="ClassDiagrammProperties" t="UMLDiagramProperties">
                <v n="ArrayOfPointerToClassPresentation" t="RelationTypes">Empty</v>
                <v n="ArrayOfClassPresentation" t="RelationTypes">Empty</v>
                <v n="ArrayOfInterfacePresentation" t="RelationTypes">Empty</v>
                <v n="ArrayOfInterfaceAggregationPresentation" t="RelationTypes">Empty</v>
                <v n="PointerToClassPresentation" t="RelationTypes">Empty</v>
                <v n="ClassPresentation" t="RelationTypes">Empty</v>
                <v n="InterfacePresentation" t="RelationTypes">Empty</v>
                <v n="InterfaceAggregationPresentation" t="RelationTypes">Empty</v>
                <v n="ShowRoleNames">true</v>
                <v n="ShowCardinalities">true</v>
                <v n="ShowRelationNames">true</v>
                <v n="ShowAttributesinClasses">false</v>
                <v n="ShowMethodsInClasses">false</v>
                <v n="ParametersMaximumLength">20</v>
              </o>
              <v n="IsFastStateDiagram">false</v>
              <l n="StereoTypeProfile" t="ArrayList" />
              <v n="RelationRoleID">57</v>
              <d n="PositionSerialization" t="Hashtable" ckt="Int64" cvt="Guid">
                <v>57</v>
                <v>91c8a235-a4ad-4efa-b426-77d491125855</v>
                <v>56</v>
                <v>0409fd0f-eb0b-4cee-bbdc-09182c0456ea</v>
                <v>55</v>
                <v>7dc0ac2b-166e-4c9d-9d8a-49a838b42ab2</v>
                <v>54</v>
                <v>b8bb5204-9a6f-4b66-bbbe-90fa86a2fb7f</v>
                <v>53</v>
                <v>b8bb5204-9a6f-4b66-bbbe-90fa86a2fb7f</v>
                <v>52</v>
                <v>9db889f9-8d1a-440e-a22c-5ba0d5d7cc3e</v>
                <v>51</v>
                <v>ffb6e2e9-64bc-4cf1-a6b2-65c9e36d4ee7</v>
                <v>50</v>
                <v>3ed5ca2a-d9b0-444b-b347-b6917e5ac7f9</v>
                <v>49</v>
                <v>4e5e080a-fccb-4078-89e3-8ba156a63a91</v>
                <v>48</v>
                <v>4e5e080a-fccb-4078-89e3-8ba156a63a91</v>
                <v>47</v>
                <v>cb13c4e0-3a5a-42d9-bc1a-e2c20df2dbb5</v>
                <v>46</v>
                <v>97a81f28-c7c4-417e-a904-557128895189</v>
                <v>45</v>
                <v>1c2944d6-010a-432b-b6dd-c897db58069d</v>
                <v>44</v>
                <v>f5193168-3c3e-4dc1-b76d-86a7edfcc476</v>
                <v>43</v>
                <v>f5193168-3c3e-4dc1-b76d-86a7edfcc476</v>
                <v>42</v>
                <v>cab5b7d7-dc21-4fdc-adfd-27c486f4ef74</v>
                <v>41</v>
                <v>2b6f464f-6e32-4219-9491-2463a2da4da6</v>
                <v>40</v>
                <v>49aa1ff1-cdad-45a8-a2e9-67a019ddd9b5</v>
                <v>39</v>
                <v>5853e86b-95e2-4f38-a240-330dc8df6d39</v>
                <v>38</v>
                <v>5853e86b-95e2-4f38-a240-330dc8df6d39</v>
                <v>37</v>
                <v>bc23480c-ec6c-4634-823a-89a425614cd8</v>
                <v>36</v>
                <v>032a32cf-8d11-4b72-b1bd-1f23a26cce59</v>
                <v>35</v>
                <v>f77eec2c-d70b-471f-bcea-4594d099fc8b</v>
                <v>34</v>
                <v>f77eec2c-d70b-471f-bcea-4594d099fc8b</v>
                <v>33</v>
                <v>623679c3-f2c6-4ab4-8028-9537039276db</v>
                <v>32</v>
                <v>c2cb57a3-218c-4c6b-89e7-3f3547cb45bc</v>
                <v>31</v>
                <v>fa206268-213c-4c42-8b42-8322357a29ba</v>
                <v>30</v>
                <v>fa206268-213c-4c42-8b42-8322357a29ba</v>
                <v>29</v>
                <v>d36d85b5-be19-45ab-90d8-f522bcc2e6e5</v>
                <v>28</v>
                <v>c31659c7-1d4e-4e22-921c-8e067df09d02</v>
                <v>27</v>
                <v>113074f3-7280-4734-adb6-ec5d4d75ccf4</v>
                <v>26</v>
                <v>113074f3-7280-4734-adb6-ec5d4d75ccf4</v>
                <v>25</v>
                <v>f83add32-6f7b-42a2-95e3-19de406ae599</v>
                <v>24</v>
                <v>f096a2e6-f660-4766-b0b1-5571bfa534c6</v>
                <v>23</v>
                <v>ec45b326-114e-412d-9d62-7095c09f6ed5</v>
                <v>22</v>
                <v>ef2deb4c-0b59-4a14-a99e-7fb849fa7a0a</v>
                <v>21</v>
                <v>ee59122d-01c0-492f-bbb7-6075eabcb69b</v>
                <v>20</v>
                <v>ee59122d-01c0-492f-bbb7-6075eabcb69b</v>
                <v>19</v>
                <v>9b67180e-c559-4770-8723-f8cf2d7cda4a</v>
                <v>18</v>
                <v>b8956def-1048-443e-9278-ae32c3b1cb8f</v>
                <v>17</v>
                <v>73277216-de9b-49fb-b8bc-bb0ff8b88c9a</v>
                <v>16</v>
                <v>73277216-de9b-49fb-b8bc-bb0ff8b88c9a</v>
                <v>15</v>
                <v>2832396c-647d-47fb-b5e1-7a06bf8dc4d6</v>
                <v>14</v>
                <v>488ebaf5-9a11-4fa0-899d-42ba32bb1863</v>
                <v>11</v>
                <v>b58f3e2e-a9f3-419e-8e36-3148bcd6a2c4</v>
                <v>10</v>
                <v>e226eac8-092d-4d52-974d-fb2d32733f80</v>
                <v>8</v>
                <v>4350233d-6cb8-4973-b78b-e1f1d3f81ffc</v>
                <v>7</v>
                <v>b916ffcf-86cf-4922-b33d-62dd98fd491e</v>
                <v>6</v>
                <v>dd41abb1-cf8c-4daa-a515-0826b419d6de</v>
                <v>5</v>
                <v>dd41abb1-cf8c-4daa-a515-0826b419d6de</v>
                <v>4</v>
                <v>49d8c493-e130-498c-8290-94cd04bb637c</v>
                <v>2</v>
                <v>897f99e0-ecbf-40c3-baf9-a39f7de4af68</v>
                <v>1</v>
                <v>b194dc9d-1e2b-4eca-a1c4-4e5f60544940</v>
              </d>
            </o>
          </Data>
          <TypeList>
            <Type n="ArrayList">System.Collections.ArrayList</Type>
            <Type n="ArrowTypes">{812dac4c-85cd-4336-bb2f-f967774b251e}</Type>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Docked">{7586ffd4-4b2d-494c-aff5-a40d31dac111}</Type>
            <Type n="Double">System.Double</Type>
            <Type n="EditorRestrictions">{1ca7a370-7213-48b2-9df6-3ac7e85f0c68}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Hashtable">System.Collections.Hashtable</Type>
            <Type n="HistoryTypes">{3534dff0-3cd3-4ab6-8e74-b81ff8613005}</Type>
            <Type n="ImplicitStartStateTypes">{159536e2-c3a1-4501-a760-7b5009964f41}</Type>
            <Type n="Int16">System.Int16</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="RelationTypes">{f5146002-a332-47c0-9d9a-7997d539e6a9}</Type>
            <Type n="String">System.String</Type>
            <Type n="UInt32">System.UInt32</Type>
            <Type n="UMLAnchorPoint">{610ad96d-085d-4ced-95e0-831f42edefc2}</Type>
            <Type n="UMLArea">{7b0cf5f4-81b9-4f82-abc9-9de087e8469a}</Type>
            <Type n="UMLCompositeVisualisation">{408045ae-deed-4f23-8f67-f77d80b7a749}</Type>
            <Type n="UMLDiagramProperties">{71bc64fb-98e8-4f9a-b2ec-0da66cfaa0a0}</Type>
            <Type n="UMLRelation">{66eb2f12-934d-4c0a-8710-d6fec8d1ff48}</Type>
            <Type n="UMLRelationVisualisation">{79af0d10-00d2-4abe-9c91-6b4e07d4aa1d}</Type>
            <Type n="UMLStateChart">{9b0dd937-6691-44b8-b0c0-27601a5e098a}</Type>
            <Type n="UMLStateChartComposite">{05967c19-34ab-4e26-b363-c32e4509c5dc}</Type>
            <Type n="UMLStateChartDiagramElementVisualisationDot">{573ce27a-c0d4-453b-8ffd-6d125a13ad66}</Type>
            <Type n="UMLStateChartElement">{a9cbb7e7-7aa8-4772-a0f9-efee80bd48b2}</Type>
            <Type n="UMLStateChartElementVisualisation">{861a8beb-602e-4017-bf45-a602984c46fe}</Type>
            <Type n="UMLStateChartPseudoElement">{3569ebb7-c8a3-4ab4-b440-d179b9e0fe9b}</Type>
            <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
          </TypeList>
        </XmlArchive>
      </StateChart>
    </Implementation>
    <Method Name="decode_E_StewartOpMode" Id="{aeed7a95-8ef5-47a2-87d9-187ad2fce3da}">
      <Declaration><![CDATA[METHOD decode_E_StewartOpMode : E_StewartOpMode
VAR_INPUT
	motionStatus : UDINT;
END_VAR
VAR
	mask : UDINT;
	n : USINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
mask := 16#FF000000 AND motionStatus;
n := UDINT_TO_USINT(SHR(mask, 6));

(*
CASE mask OF
	16#00000000 :
		eResult := E_StewartOpMode.MANUAL;
		
	16#01000000 :
		eResult := E_StewartOpMode.NORMAL;
	
END_CASE
*)


 ]]></ST>
      </Implementation>
    </Method>
    <Method Name="decode_E_StewartState" Id="{e4d78dc9-868d-41d9-8edb-2d85943c11a0}">
      <Declaration><![CDATA[METHOD PRIVATE decode_E_StewartState : E_StewartState
VAR_INPUT
	motionStatus : UDINT;
END_VAR
VAR
	mask : UDINT;
	eResult : E_StewartState;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// PDF: Motion System Ethernet Interface p.18

mask := 16#0000000F AND motionStatus;

CASE mask OF
	16#00000000 : 
		eResult := E_StewartState.TRANSIT;
		
	16#00000001 : 
		eResult := E_StewartState.OFF;
		
	16#00000002 : 
		eResult := E_StewartState.SETTLED;
		
	16#00000003 : 
		eResult := E_StewartState.OIL_HEATING;
		
	16#00000004 : 
		eResult := E_StewartState.NEUTRAL;
		
	16#00000005 : 
		eResult := E_StewartState.NEUTRAL_FREEZE;
		
	16#00000008 : 
		eResult := E_StewartState.ENGAGED;
		
	16#00000009 : 
		eResult := E_StewartState.ENGAGED_FREEZE;
	
END_CASE

decode_E_StewartState := eResult;]]></ST>
      </Implementation>
    </Method>
    <Method Name="decode_E_StewartStatus" Id="{bbaee5fb-4eca-4cf3-9659-16a29517b6f5}">
      <Declaration><![CDATA[METHOD decode_E_StewartStatus : E_StewartStatus
VAR_INPUT
	motionStatus : UDINT;
END_VAR
VAR
	mask : UDINT;
	eResult : E_StewartStatus;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
mask := 16#000000F0 AND motionStatus;

CASE mask OF
	16#00000000 :
		eResult := E_StewartStatus.SYSTEM_OK;
		
	16#01000040 :
		eResult := E_StewartStatus.WARNING;
		
	16#01000080 :
		eResult := E_StewartStatus.ERROR;
	
END_CASE

decode_E_StewartStatus := eResult;

 ]]></ST>
      </Implementation>
    </Method>
    <Method Name="ERROR_DO" Id="{4a61e0e3-a4c6-4d6d-8f96-df1f66850830}">
      <Declaration><![CDATA[METHOD PRIVATE ERROR_DO : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// Wait for SYSTEM_OK and return to settled
IF eStatus = E_StewartStatus.SYSTEM_OK THEN
	eModeCmd := E_StewartMode.SETTLED;
	eCmnd := E_StewartCommand.TO_SETTLED;

	bError := FALSE;
	
END_IF

// Check for bReset request and acknowledge fault
IF bReset THEN
	eCmnd := E_StewartCommand.ACK_FAULT;
	bReset := FALSE;
END_IF

// Execute main thread
Execute();]]></ST>
      </Implementation>
    </Method>
    <Method Name="Execute" Id="{7ab70c3b-60b3-4238-ba48-85e0dc447c49}">
      <Declaration><![CDATA[METHOD PRIVATE Execute : BOOL
VAR_INPUT
END_VAR
VAR

	i: INT;
	
	nState : DWORD;
	nStatus : DWORD;
	nOpMode : DWORD;
	
	A : LREAL;
	omega : LREAL;
	phi : LREAL;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// Task monitoring
fbGetCurrentTaskIdx();
bCycleTimeExceeded := _TaskInfo[fbGetCurrentTaskIdx.index].CycleTimeExceeded;
nCycleCount := _TaskInfo[fbGetCurrentTaskIdx.index].CycleCount;
Ts := UDINT_TO_LREAL(_TaskInfo[fbGetCurrentTaskIdx.index].CycleTime/10)/1E6;

// Sine genrator
FOR i := 0 TO 5 DO
	// Sine signals
	A := LIMIT(etaRefMin[i], sineAmplitude[i], etaRefMax[i]);
	omega := sineOmega[i];
	phi := sinePhase[i];
	
	etaSine[i] := A*SIN(omega*t + phi);
	etaSine_t[i] := omega*A*COS(omega*t + phi);
	etaSine_tt[i] := -omega*omega*A*SIN(omega*t + phi);
END_FOR

// Increment Time
t := t + Ts;

// Set controls
txUdp.CMND := eCmnd;

txUdp.X_EXTRA 			:= LREAL_TO_REAL( LIMIT(etaRefMin[0], etaRef[0], etaRefMax[0]) );
txUdp.Y_EXTRA 			:= LREAL_TO_REAL( LIMIT(etaRefMin[1], etaRef[1], etaRefMax[1]) );
txUdp.Z_EXTRA 			:= LREAL_TO_REAL( LIMIT(etaRefMin[2], etaRef[2], etaRefMax[2]) );
txUdp.PHI_EXTRA 		:= LREAL_TO_REAL( LIMIT(etaRefMin[3], etaRef[3], etaRefMax[3]) );
txUdp.THETA_EXTRA 		:= LREAL_TO_REAL( LIMIT(etaRefMin[4], etaRef[4], etaRefMax[4]) );
txUdp.PSI_EXTRA 		:= LREAL_TO_REAL( LIMIT(etaRefMin[5], etaRef[5], etaRefMax[5]) );

txUdp.X_EXTRA_DOT		:= LREAL_TO_REAL(etaRef_t[0]);
txUdp.Y_EXTRA_DOT		:= LREAL_TO_REAL(etaRef_t[1]);
txUdp.Z_EXTRA_DOT		:= LREAL_TO_REAL(etaRef_t[2]);
txUdp.PHI_EXTRA_DOT		:= LREAL_TO_REAL(etaRef_t[3]);
txUdp.THETA_EXTRA_DOT	:= LREAL_TO_REAL(etaRef_t[4]);
txUdp.PSI_EXTRA_DOT		:= LREAL_TO_REAL(etaRef_t[5]);

txUdp.X_EXTRA_DDOT		:= LREAL_TO_REAL(etaRef_tt[0]);
txUdp.Y_EXTRA_DDOT		:= LREAL_TO_REAL(etaRef_tt[1]);
txUdp.Z_EXTRA_DDOT		:= LREAL_TO_REAL(etaRef_tt[2]);
txUdp.PHI_EXTRA_DDOT	:= LREAL_TO_REAL(etaRef_tt[3]);
txUdp.THETA_EXTRA_DDOT	:= LREAL_TO_REAL(etaRef_tt[4]);
txUdp.PSI_EXTRA_DDOT	:= LREAL_TO_REAL(etaRef_tt[5]);

// Update udpClient
udpClient();

// Unamsk Motion_Status signal
nState	:= 16#0000000F AND rxUdp.Motion_Status;
nStatus	:= 16#000000F0 AND rxUdp.Motion_Status;
nOpMode := 16#FF000000 AND rxUdp.Motion_Status;

// Shift for USINT conversion
nState 	:= SHR(nState, 0*4);
nStatus := SHR(nStatus, 1*4);
nOpMode := SHR(nOpMode, 6*4);

// Enum(USINT) typecast
MEMCPY(ADR(eState), ADR(nState), SIZEOF(eState));
MEMCPY(ADR(eStatus), ADR(nStatus), SIZEOF(eStatus));
MEMCPY(ADR(eOpMode), ADR(nOpMode), SIZEOF(eOpMode));

// Error/Warning check
IF (eStatus <> E_StewartStatus.SYSTEM_OK) THEN
	bError := TRUE;;
END_IF

// Check activity
frame := rxUdp.Frame_Count;
IF frame <> frameOld THEN
	// Update frame old
	frameOld := frame;
	
	// Reset frameLoss
	frameLoss := 0;
ELSE
	// Count frame losses
	frameLoss := frameLoss + 1;
END_IF

// Set activity status after 1 second given 5ms in ms
IF frameLoss > 200 THEN
	bActive := FALSE;
ELSE
	bActive := TRUE;
END_IF

// Feedback data
eta[0] := REAL_TO_LREAL(rxUdp.Actual_platform_position_surge);
eta[1] := REAL_TO_LREAL(rxUdp.Actual_platform_position_sway);
eta[2] := REAL_TO_LREAL(rxUdp.Actual_platform_position_heave);
eta[3] := REAL_TO_LREAL(rxUdp.Actual_platform_position_roll);
eta[4] := REAL_TO_LREAL(rxUdp.Actual_platform_position_pitch);
eta[5] := REAL_TO_LREAL(rxUdp.Actual_platform_position_yaw);

eta_t[0] := REAL_TO_LREAL(rxUdp.Actual_platform_velocity_surge);
eta_t[1] := REAL_TO_LREAL(rxUdp.Actual_platform_velocity_sway);
eta_t[2] := REAL_TO_LREAL(rxUdp.Actual_platform_velocity_heave);
eta_t[3] := REAL_TO_LREAL(rxUdp.Actual_platform_velocity_roll);
eta_t[4] := REAL_TO_LREAL(rxUdp.Actual_platform_velocity_pitch);
eta_t[5] := REAL_TO_LREAL(rxUdp.Actual_platform_velocity_yaw);

eta_tt[0] := REAL_TO_LREAL(rxUdp.Actual_platform_acceleration_surge);
eta_tt[1] := REAL_TO_LREAL(rxUdp.Actual_platform_acceleration_sway);
eta_tt[2] := REAL_TO_LREAL(rxUdp.Actual_platform_acceleration_heave);
eta_tt[3] := REAL_TO_LREAL(rxUdp.Actual_platform_acceleration_roll);
eta_tt[4] := REAL_TO_LREAL(rxUdp.Actual_platform_acceleration_pitch);
eta_tt[5] := REAL_TO_LREAL(rxUdp.Actual_platform_acceleration_yaw);

// Update global Hmi data
IF bActive THEN
	txHmi.status := 1;
ELSE
	txHmi.status := 0;
END_IF

txHmi.eta[0] := rxUdp.Actual_platform_position_surge;
txHmi.eta[1] := rxUdp.Actual_platform_position_sway;
txHmi.eta[2] := rxUdp.Actual_platform_position_heave;
txHmi.eta[3] := rxUdp.Actual_platform_position_roll;
txHmi.eta[4] := rxUdp.Actual_platform_position_pitch;
txHmi.eta[5] := rxUdp.Actual_platform_position_yaw;

txHmi.etaRef[0] := rxUdp.Platform_setpoint_surge;
txHmi.etaRef[1] := rxUdp.Platform_setpoint_sway;
txHmi.etaRef[2] := rxUdp.Platform_setpoint_heave;
txHmi.etaRef[3] := rxUdp.Platform_setpoint_roll;
txHmi.etaRef[4] := rxUdp.Platform_setpoint_pitch;
txHmi.etaRef[5] := rxUdp.Platform_setpoint_yaw;

txHmi.cyl[0] := rxUdp.Actual_position_actuator_1;
txHmi.cyl[1] := rxUdp.Actual_position_actuator_2;
txHmi.cyl[2] := rxUdp.Actual_position_actuator_3;
txHmi.cyl[3] := rxUdp.Actual_position_actuator_4;
txHmi.cyl[4] := rxUdp.Actual_position_actuator_5;
txHmi.cyl[5] := rxUdp.Actual_position_actuator_6;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_exit" Id="{9bed94a0-b2f9-4c8b-9085-b30806c38f7e}">
      <Declaration><![CDATA[METHOD FB_exit : BOOL
VAR_INPUT
	bInCopyCode : BOOL; // if TRUE, the exit method is called for exiting an instance that is copied afterwards (online change).
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{c61434a5-8a62-405e-832e-838499c788e2}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	
	// Init variables
	_remoteIpAddr : T_Ipv4Addr;
	_remotePort : UINT;
	_localPort : UINT;

END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[// Initilize udpClient
udpClient.FB_init(
	bInitRetains,
	bInCopyCode,
	_remoteIpAddr,
	_remotePort,
	_localPort,
	SIZEOF(rxUdp),
	ADR(rxUdp),
	SIZEOF(txUdp),
	ADR(txUdp)
);

// EM8000
IF _remotePort = 50030 THEN
	rxUdp.Actual_platform_position_heave := 0.9986208;
END_IF

// EM15000
IF _remotePort = 50031 THEN
	rxUdp.Actual_platform_position_heave := 0.4663845;
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_reinit" Id="{0d8df33c-9ef8-4c5e-ab3a-f88ad66fdbff}">
      <Declaration><![CDATA[METHOD FB_reinit : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="FILE_DO" Id="{60908887-7e2a-47de-881c-86e8e5d8344f}">
      <Declaration><![CDATA[METHOD PRIVATE FILE_DO : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// TODO: Add remote input
etaRef := etaZeros;
etaRef_t := etaZeros;
etaRef_tt := etaZeros;

// Enagage and disengage
IF bStart THEN
	eCmnd := E_StewartCommand.TO_ENGAGED;
	
ELSE
	eCmnd := E_StewartCommand.TO_NEUTRAL;
	
END_IF

// Set mode
eMode := E_StewartMode.FILE;]]></ST>
      </Implementation>
    </Method>
    <Method Name="GENERATOR_DO" Id="{56942693-b597-4c5f-bdcd-afda718bb866}">
      <Declaration><![CDATA[METHOD PRIVATE GENERATOR_DO : BOOL
VAR_INPUT
END_VAR
VAR
	i : UINT;
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// Apply sine generator input
etaRef := etaSine;
etaRef_t := etaSine_t;
etaRef_tt := etaSine_tt;

IF bStart THEN
	eCmnd := E_StewartCommand.TO_ENGAGED;
	
ELSE
	eCmnd := E_StewartCommand.TO_NEUTRAL;
	
END_IF

// Set mode
eMode := E_StewartMode.GENERATOR;]]></ST>
      </Implementation>
    </Method>
    <Method Name="NEUTRAL_DO" Id="{69231ff7-e79a-4faa-b660-c71db9a3b5fc}">
      <Declaration><![CDATA[METHOD PRIVATE NEUTRAL_DO : BOOL
VAR_INPUT
END_VAR
VAR
	i : UINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// Zero input
etaRef := etaZeros;
etaRef_t := etaZeros;
etaRef_tt := etaZeros;

// Set mode
eMode := E_StewartMode.NEUTRAL;]]></ST>
      </Implementation>
    </Method>
    <Method Name="SETTLED_DO" Id="{3f622d4b-3977-4a1f-9053-5c946b26f676}">
      <Declaration><![CDATA[METHOD PRIVATE SETTLED_DO : BOOL
VAR_INPUT
END_VAR
VAR
	i : UINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// Zero input
etaRef := etaZeros;
etaRef_t := etaZeros;
etaRef_tt := etaZeros;


eMode := E_StewartMode.SETTLED;]]></ST>
      </Implementation>
    </Method>
    <Method Name="SIMULATION_DO" Id="{c4950ba8-bec0-4ee1-aa4a-7e027c541c4f}">
      <Declaration><![CDATA[METHOD PRIVATE SIMULATION_DO : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// Apply simulator output
etaRef := etaSim;
etaRef_t := etaZeros;
etaRef_tt := etaZeros;

IF bStart THEN
	eCmnd := E_StewartCommand.TO_ENGAGED;
	
ELSE
	eCmnd := E_StewartCommand.TO_NEUTRAL;
	
END_IF
			

// Set mode
eMode := E_StewartMode.SIMULATION;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="StatusCheck_DO" Id="{a39a77ba-2cc3-4587-a018-d8ce79cb4e47}">
      <Declaration><![CDATA[METHOD PRIVATE StatusCheck_DO : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[eModeCmd := E_StewartMode.SETTLED;
eCmnd := E_StewartCommand.TO_SETTLED;

Execute();


]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stewart_DO" Id="{3f4bcd7a-1198-44f9-8097-0a0c8b8727c7}">
      <Declaration><![CDATA[METHOD PRIVATE Stewart_DO : BOOL
VAR_INPUT
END_VAR

VAR
	i: INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[


// Execute Main thread 
Execute();



]]></ST>
      </Implementation>
    </Method>
    <Method Name="STOPP_DO" Id="{c0f5e363-81aa-4e1d-ba41-5ee852d3c92a}">
      <Declaration><![CDATA[METHOD PRIVATE STOPP_DO : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// Got to settled in case of stop
eModeCmd := E_StewartMode.SETTLED;
eCmnd := E_StewartCommand.TO_SETTLED;
	 
// Execute main thread
Execute();

// Reset stop
IF (eStatus = E_StewartStatus.SYSTEM_OK) AND bReset THEN
	bStop := FALSE;
	
END_IF]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_StewartInterface.decode_E_StewartOpMode">
      <LineId Id="25" Count="0" />
      <LineId Id="24" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="10" Count="1" />
      <LineId Id="5" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="14" Count="5" />
      <LineId Id="27" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="13" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.decode_E_StewartState">
      <LineId Id="7" Count="0" />
      <LineId Id="41" Count="1" />
      <LineId Id="8" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="11" Count="1" />
      <LineId Id="16" Count="6" />
      <LineId Id="24" Count="13" />
      <LineId Id="23" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="39" Count="0" />
      <LineId Id="38" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.decode_E_StewartStatus">
      <LineId Id="27" Count="0" />
      <LineId Id="10" Count="1" />
      <LineId Id="5" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="14" Count="3" />
      <LineId Id="23" Count="2" />
      <LineId Id="18" Count="1" />
      <LineId Id="22" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="13" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.ERROR_DO">
      <LineId Id="15" Count="1" />
      <LineId Id="28" Count="2" />
      <LineId Id="22" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="13" Count="0" />
      <LineId Id="5" Count="1" />
      <LineId Id="8" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="23" Count="0" />
      <LineId Id="10" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.Execute">
      <LineId Id="72" Count="3" />
      <LineId Id="71" Count="0" />
      <LineId Id="139" Count="0" />
      <LineId Id="129" Count="0" />
      <LineId Id="131" Count="1" />
      <LineId Id="188" Count="1" />
      <LineId Id="191" Count="0" />
      <LineId Id="190" Count="0" />
      <LineId Id="133" Count="1" />
      <LineId Id="192" Count="0" />
      <LineId Id="135" Count="2" />
      <LineId Id="130" Count="0" />
      <LineId Id="70" Count="0" />
      <LineId Id="39" Count="0" />
      <LineId Id="38" Count="0" />
      <LineId Id="148" Count="0" />
      <LineId Id="143" Count="4" />
      <LineId Id="140" Count="0" />
      <LineId Id="194" Count="5" />
      <LineId Id="193" Count="0" />
      <LineId Id="201" Count="5" />
      <LineId Id="200" Count="0" />
      <LineId Id="37" Count="0" />
      <LineId Id="27" Count="4" />
      <LineId Id="6" Count="0" />
      <LineId Id="166" Count="0" />
      <LineId Id="181" Count="0" />
      <LineId Id="178" Count="0" />
      <LineId Id="177" Count="0" />
      <LineId Id="179" Count="1" />
      <LineId Id="182" Count="0" />
      <LineId Id="168" Count="0" />
      <LineId Id="167" Count="0" />
      <LineId Id="170" Count="1" />
      <LineId Id="32" Count="4" />
      <LineId Id="8" Count="18" />
      <LineId Id="5" Count="0" />
      <LineId Id="41" Count="20" />
      <LineId Id="40" Count="0" />
      <LineId Id="80" Count="20" />
      <LineId Id="108" Count="5" />
      <LineId Id="79" Count="0" />
      <LineId Id="183" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.FB_exit">
      <LineId Id="6" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.FB_init">
      <LineId Id="34" Count="20" />
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.FB_reinit">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.FILE_DO">
      <LineId Id="17" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="15" Count="1" />
      <LineId Id="6" Count="8" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.GENERATOR_DO">
      <LineId Id="8" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="75" Count="1" />
      <LineId Id="68" Count="6" />
      <LineId Id="67" Count="0" />
      <LineId Id="65" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="66" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.NEUTRAL_DO">
      <LineId Id="11" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="23" Count="1" />
      <LineId Id="22" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="20" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.SETTLED_DO">
      <LineId Id="14" Count="0" />
      <LineId Id="26" Count="3" />
      <LineId Id="24" Count="0" />
      <LineId Id="23" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.SIMULATION_DO">
      <LineId Id="28" Count="0" />
      <LineId Id="70" Count="0" />
      <LineId Id="83" Count="1" />
      <LineId Id="77" Count="0" />
      <LineId Id="76" Count="0" />
      <LineId Id="57" Count="0" />
      <LineId Id="79" Count="0" />
      <LineId Id="78" Count="0" />
      <LineId Id="80" Count="0" />
      <LineId Id="82" Count="0" />
      <LineId Id="81" Count="0" />
      <LineId Id="58" Count="0" />
      <LineId Id="75" Count="0" />
      <LineId Id="74" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="13" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.StatusCheck_DO">
      <LineId Id="6" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="7" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.Stewart_DO">
      <LineId Id="130" Count="0" />
      <LineId Id="146" Count="0" />
      <LineId Id="137" Count="0" />
      <LineId Id="129" Count="0" />
      <LineId Id="87" Count="0" />
      <LineId Id="99" Count="0" />
      <LineId Id="77" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="17" Count="0" />
    </LineIds>
    <LineIds Name="FB_StewartInterface.STOPP_DO">
      <LineId Id="11" Count="2" />
      <LineId Id="15" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="21" Count="1" />
      <LineId Id="24" Count="0" />
      <LineId Id="23" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>