// ****************** CToolPlaneDistanceClassFactory.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1230
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#ifndef CTOOLPLANEDISTANCECLASSFACTORY_H_INCLUDED
#define CTOOLPLANEDISTANCECLASSFACTORY_H_INCLUDED

#include "ObjClassFactory.h"

class CToolPlaneDistanceClassFactory : public CObjClassFactory
{
public:
	CToolPlaneDistanceClassFactory();
	
	// ITComClassFactory
	DECLARE_CLASS_MAP()
};

#endif
