// ****************** CToolPlaneDistanceClassFactory.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1230
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "stdafx.h"
#pragma hdrstop

#include "CToolPlaneDistance.h"
#include "CToolPlaneDistanceClassFactory.h"

// ITComClassFactory
BEGIN_CLASS_MAP(CToolPlaneDistanceClassFactory)
	CLASS_ENTRY_RT(CID_ToolPlaneDistance,SRVNAME_ToolPlaneDistance "!CToolPlaneDistance", CToolPlaneDistance)
END_CLASS_MAP()


CToolPlaneDistanceClassFactory::CToolPlaneDistanceClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_ToolPlaneDistance)); 
}

