// ****************** ToolPlaneDistanceCtrl.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1230
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef TOOLPLANEDISTANCECTRL_H_INCLUDED
#define TOOLPLANEDISTANCECTRL_H_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CToolPlaneDistanceDrvName "ToolPlaneDistance"

#include "ToolPlaneDistanceResource.h"
#include "ToolPlaneDistanceW32.h"
#include "TcPch.h"
#include "CToolPlaneDistanceClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CToolPlaneDistanceCtrl :		public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CToolPlaneDistanceCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CToolPlaneDistanceCtrl, CToolPlaneDistanceClassFactory>
{
public:
	CToolPlaneDistanceCtrl() : ITcOCFCtrlImpl<CToolPlaneDistanceCtrl, CToolPlaneDistanceClassFactory>(){}

	virtual ~CToolPlaneDistanceCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_ToolPlaneDistanceCtrl)
DECLARE_NOT_AGGREGATABLE(CToolPlaneDistanceCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CToolPlaneDistanceCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif
