// ****************** ToolPlaneDistanceServices.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1230
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef TOOLPLANEDISTANCESERVICES_H_INCLUDED
#define TOOLPLANEDISTANCESERVICES_H_INCLUDED

#define SRVNAME_ToolPlaneDistance "ToolPlaneDistance"

// TcCOM-ClassId of this module: 144b28a1-f56b-42f6-a491-dbbcadd34ad9
const   CTCID   CID_ToolPlaneDistance    =  {0x144b28a1,0xf56b,0x42f6,{0xa4,0x91,0xdb,0xbc,0xad,0xd3,0x4a,0xd9}};

#endif
