// ****************** ToolPlaneDistance_types.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2017b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1230
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
/*
 * ToolPlaneDistance_types.h
 *
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * Code generation for model "ToolPlaneDistance".
 *
 * Model version              : 1.1507
 * Simulink Coder version : 8.13 (R2017b) 24-Jul-2017
 * C++ source code generated on : Wed Apr 25 10:18:36 2018
 *
 * Target selection: TwinCAT.tlc
 * Note: GRT includes extra infrastructure and instrumentation for prototyping
 * Embedded hardware selection: Intel->x86-64 (Windows64)
 * Code generation objectives: Unspecified
 * Validation result: Not run
 */

#ifndef RTW_HEADER_ToolPlaneDistance_types_h_
#define RTW_HEADER_ToolPlaneDistance_types_h_
#include "rtwtypes.h"
#include "multiword_types.h"
#include "zero_crossing_types.h"
#ifndef typedef_motionlab_ComauRobot3DOF_Tool_T
#define typedef_motionlab_ComauRobot3DOF_Tool_T

typedef struct {
  int32_T isInitialized;
  real_T dt;
  real_T a1;
  real_T a2;
  real_T a3;
  real_T d1;
  real_T d4;
  real_T d6;
  real_T L;
} motionlab_ComauRobot3DOF_Tool_T;

#endif                                 /*typedef_motionlab_ComauRobot3DOF_Tool_T*/

/* Custom Type definition for MATLAB Function: '<S1>/Tool-Plane Distance' */
#ifndef struct_tag_sGxvadsxpUsjdesWy3kZDKH
#define struct_tag_sGxvadsxpUsjdesWy3kZDKH

struct tag_sGxvadsxpUsjdesWy3kZDKH
{
  real_T quat[4];
  real_T pos[3];
  real_T H[16];
};

#endif                                 /*struct_tag_sGxvadsxpUsjdesWy3kZDKH*/

#ifndef typedef_sGxvadsxpUsjdesWy3kZDKH_ToolP_T
#define typedef_sGxvadsxpUsjdesWy3kZDKH_ToolP_T

typedef struct tag_sGxvadsxpUsjdesWy3kZDKH sGxvadsxpUsjdesWy3kZDKH_ToolP_T;

#endif                                 /*typedef_sGxvadsxpUsjdesWy3kZDKH_ToolP_T*/

#ifndef struct_tag_sVAkmAxZ9aLewjRhYZmZvLH
#define struct_tag_sVAkmAxZ9aLewjRhYZmZvLH

struct tag_sVAkmAxZ9aLewjRhYZmZvLH
{
  sGxvadsxpUsjdesWy3kZDKH_ToolP_T WORLD_TO_EM8000;
  sGxvadsxpUsjdesWy3kZDKH_ToolP_T WORLD_TO_EM1500;
  sGxvadsxpUsjdesWy3kZDKH_ToolP_T EM8000_TO_EM1500;
  sGxvadsxpUsjdesWy3kZDKH_ToolP_T EM8000_TO_COMAU;
  sGxvadsxpUsjdesWy3kZDKH_ToolP_T EM8000_TO_MRU1;
  sGxvadsxpUsjdesWy3kZDKH_ToolP_T EM1500_TO_MRU1;
  sGxvadsxpUsjdesWy3kZDKH_ToolP_T EM8000_TO_AT960;
  sGxvadsxpUsjdesWy3kZDKH_ToolP_T EM1500_TO_TMAC;
};

#endif                                 /*struct_tag_sVAkmAxZ9aLewjRhYZmZvLH*/

#ifndef typedef_sVAkmAxZ9aLewjRhYZmZvLH_ToolP_T
#define typedef_sVAkmAxZ9aLewjRhYZmZvLH_ToolP_T

typedef struct tag_sVAkmAxZ9aLewjRhYZmZvLH sVAkmAxZ9aLewjRhYZmZvLH_ToolP_T;

#endif                                 /*typedef_sVAkmAxZ9aLewjRhYZmZvLH_ToolP_T*/

#ifndef struct_tag_sfNS2VRvJob5D5eauUzxBT
#define struct_tag_sfNS2VRvJob5D5eauUzxBT

struct tag_sfNS2VRvJob5D5eauUzxBT
{
  sVAkmAxZ9aLewjRhYZmZvLH_ToolP_T calib;
};

#endif                                 /*struct_tag_sfNS2VRvJob5D5eauUzxBT*/

#ifndef typedef_sfNS2VRvJob5D5eauUzxBT_ToolPl_T
#define typedef_sfNS2VRvJob5D5eauUzxBT_ToolPl_T

typedef struct tag_sfNS2VRvJob5D5eauUzxBT sfNS2VRvJob5D5eauUzxBT_ToolPl_T;

#endif                                 /*typedef_sfNS2VRvJob5D5eauUzxBT_ToolPl_T*/

/* Parameters (auto storage) */
typedef struct P_ToolPlaneDistance_T_ P_ToolPlaneDistance_T;

/* Forward declaration for rtModel */
typedef struct tag_RTM_ToolPlaneDistance_T RT_MODEL_ToolPlaneDistance_T;

#endif                                 /* RTW_HEADER_ToolPlaneDistance_types_h_ */
