# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1304, 903)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabSelector = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSelector.sizePolicy().hasHeightForWidth())
        self.tabSelector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabSelector.setFont(font)
        self.tabSelector.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tabSelector.setStyleSheet("")
        self.tabSelector.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabSelector.setObjectName("tabSelector")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.groupBox_33 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_33.setGeometry(QtCore.QRect(10, 20, 401, 81))
        self.groupBox_33.setObjectName("groupBox_33")
        self._bStopEM8000 = QtWidgets.QPushButton(self.groupBox_33)
        self._bStopEM8000.setGeometry(QtCore.QRect(290, 30, 91, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self._bStopEM8000.setPalette(palette)
        self._bStopEM8000.setObjectName("_bStopEM8000")
        self._bResetEM8000 = QtWidgets.QPushButton(self.groupBox_33)
        self._bResetEM8000.setGeometry(QtCore.QRect(180, 30, 91, 31))
        self._bResetEM8000.setObjectName("_bResetEM8000")
        self._eModeEM8000 = QtWidgets.QComboBox(self.groupBox_33)
        self._eModeEM8000.setGeometry(QtCore.QRect(20, 30, 141, 31))
        self._eModeEM8000.setObjectName("_eModeEM8000")
        self._eModeEM8000.addItem("")
        self._eModeEM8000.addItem("")
        self._eModeEM8000.addItem("")
        self._eModeEM8000.addItem("")
        self._eModeEM8000.addItem("")
        self.groupBox_34 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_34.setGeometry(QtCore.QRect(10, 430, 401, 341))
        self.groupBox_34.setObjectName("groupBox_34")
        self.groupBox_35 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_35.setGeometry(QtCore.QRect(430, 20, 841, 751))
        self.groupBox_35.setObjectName("groupBox_35")
        self._plotModeEM8000 = QtWidgets.QComboBox(self.groupBox_35)
        self._plotModeEM8000.setGeometry(QtCore.QRect(20, 31, 131, 31))
        self._plotModeEM8000.setObjectName("_plotModeEM8000")
        self._plotModeEM8000.addItem("")
        self._plotModeEM8000.addItem("")
        self._plotModeEM8000.addItem("")
        self._plotEM8000 = GraphicsLayoutWidget(self.groupBox_35)
        self._plotEM8000.setGeometry(QtCore.QRect(10, 80, 821, 661))
        self._plotEM8000.setObjectName("_plotEM8000")
        self.groupBox_36 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_36.setGeometry(QtCore.QRect(10, 110, 401, 311))
        self.groupBox_36.setObjectName("groupBox_36")
        self.groupBox_37 = QtWidgets.QGroupBox(self.groupBox_36)
        self.groupBox_37.setGeometry(QtCore.QRect(100, 30, 81, 121))
        self.groupBox_37.setObjectName("groupBox_37")
        self._ampEM8000_0 = QtWidgets.QDoubleSpinBox(self.groupBox_37)
        self._ampEM8000_0.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self._ampEM8000_0.setObjectName("_ampEM8000_0")
        self._ampEM8000_1 = QtWidgets.QDoubleSpinBox(self.groupBox_37)
        self._ampEM8000_1.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self._ampEM8000_1.setObjectName("_ampEM8000_1")
        self._ampEM8000_2 = QtWidgets.QDoubleSpinBox(self.groupBox_37)
        self._ampEM8000_2.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self._ampEM8000_2.setObjectName("_ampEM8000_2")
        self.groupBox_38 = QtWidgets.QGroupBox(self.groupBox_36)
        self.groupBox_38.setGeometry(QtCore.QRect(200, 30, 81, 121))
        self.groupBox_38.setObjectName("groupBox_38")
        self._freqEM8000_0 = QtWidgets.QDoubleSpinBox(self.groupBox_38)
        self._freqEM8000_0.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self._freqEM8000_0.setObjectName("_freqEM8000_0")
        self._freqEM8000_1 = QtWidgets.QDoubleSpinBox(self.groupBox_38)
        self._freqEM8000_1.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self._freqEM8000_1.setObjectName("_freqEM8000_1")
        self._freqEM8000_2 = QtWidgets.QDoubleSpinBox(self.groupBox_38)
        self._freqEM8000_2.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self._freqEM8000_2.setObjectName("_freqEM8000_2")
        self.groupBox_39 = QtWidgets.QGroupBox(self.groupBox_36)
        self.groupBox_39.setGeometry(QtCore.QRect(300, 30, 81, 121))
        self.groupBox_39.setObjectName("groupBox_39")
        self._phaseEM8000_0 = QtWidgets.QDoubleSpinBox(self.groupBox_39)
        self._phaseEM8000_0.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self._phaseEM8000_0.setObjectName("_phaseEM8000_0")
        self._phaseEM8000_1 = QtWidgets.QDoubleSpinBox(self.groupBox_39)
        self._phaseEM8000_1.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self._phaseEM8000_1.setObjectName("_phaseEM8000_1")
        self._phaseEM8000_2 = QtWidgets.QDoubleSpinBox(self.groupBox_39)
        self._phaseEM8000_2.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self._phaseEM8000_2.setObjectName("_phaseEM8000_2")
        self.groupBox_40 = QtWidgets.QGroupBox(self.groupBox_36)
        self.groupBox_40.setGeometry(QtCore.QRect(100, 170, 81, 121))
        self.groupBox_40.setObjectName("groupBox_40")
        self._ampEM8000_3 = QtWidgets.QDoubleSpinBox(self.groupBox_40)
        self._ampEM8000_3.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self._ampEM8000_3.setObjectName("_ampEM8000_3")
        self._ampEM8000_4 = QtWidgets.QDoubleSpinBox(self.groupBox_40)
        self._ampEM8000_4.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self._ampEM8000_4.setObjectName("_ampEM8000_4")
        self._ampEM8000_5 = QtWidgets.QDoubleSpinBox(self.groupBox_40)
        self._ampEM8000_5.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self._ampEM8000_5.setObjectName("_ampEM8000_5")
        self.groupBox_41 = QtWidgets.QGroupBox(self.groupBox_36)
        self.groupBox_41.setGeometry(QtCore.QRect(200, 170, 81, 121))
        self.groupBox_41.setObjectName("groupBox_41")
        self._freqEM8000_3 = QtWidgets.QDoubleSpinBox(self.groupBox_41)
        self._freqEM8000_3.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self._freqEM8000_3.setObjectName("_freqEM8000_3")
        self._freqEM8000_4 = QtWidgets.QDoubleSpinBox(self.groupBox_41)
        self._freqEM8000_4.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self._freqEM8000_4.setObjectName("_freqEM8000_4")
        self._freqEM8000_5 = QtWidgets.QDoubleSpinBox(self.groupBox_41)
        self._freqEM8000_5.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self._freqEM8000_5.setObjectName("_freqEM8000_5")
        self.groupBox_42 = QtWidgets.QGroupBox(self.groupBox_36)
        self.groupBox_42.setGeometry(QtCore.QRect(300, 170, 81, 121))
        self.groupBox_42.setObjectName("groupBox_42")
        self._phaseEM8000_3 = QtWidgets.QDoubleSpinBox(self.groupBox_42)
        self._phaseEM8000_3.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self._phaseEM8000_3.setObjectName("_phaseEM8000_3")
        self._phaseEM8000_4 = QtWidgets.QDoubleSpinBox(self.groupBox_42)
        self._phaseEM8000_4.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self._phaseEM8000_4.setObjectName("_phaseEM8000_4")
        self._phaseEM8000_5 = QtWidgets.QDoubleSpinBox(self.groupBox_42)
        self._phaseEM8000_5.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self._phaseEM8000_5.setObjectName("_phaseEM8000_5")
        self.groupBox_43 = QtWidgets.QGroupBox(self.groupBox_36)
        self.groupBox_43.setGeometry(QtCore.QRect(20, 30, 61, 261))
        self.groupBox_43.setObjectName("groupBox_43")
        self.label_7 = QtWidgets.QLabel(self.groupBox_43)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 51, 16))
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.groupBox_43)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 51, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_43)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_43)
        self.label_12.setGeometry(QtCore.QRect(10, 200, 51, 16))
        self.label_12.setObjectName("label_12")
        self.label_19 = QtWidgets.QLabel(self.groupBox_43)
        self.label_19.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_43)
        self.label_20.setGeometry(QtCore.QRect(10, 230, 51, 16))
        self.label_20.setObjectName("label_20")
        self.tabSelector.addTab(self.tab_11, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 351, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.em1500_eModeCmd = QtWidgets.QComboBox(self.groupBox_2)
        self.em1500_eModeCmd.setGeometry(QtCore.QRect(13, 30, 153, 22))
        self.em1500_eModeCmd.setObjectName("em1500_eModeCmd")
        self.em1500_eModeCmd.addItem("")
        self.em1500_eModeCmd.addItem("")
        self.em1500_eModeCmd.addItem("")
        self.em1500_eModeCmd.addItem("")
        self.em1500_eModeCmd.addItem("")
        self.em1500_engage = QtWidgets.QPushButton(self.groupBox_2)
        self.em1500_engage.setGeometry(QtCore.QRect(12, 65, 155, 23))
        self.em1500_engage.setObjectName("em1500_engage")
        self.em1500_disengage = QtWidgets.QPushButton(self.groupBox_2)
        self.em1500_disengage.setGeometry(QtCore.QRect(180, 65, 155, 23))
        self.em1500_disengage.setObjectName("em1500_disengage")
        self.em1500_eMode = QtWidgets.QLineEdit(self.groupBox_2)
        self.em1500_eMode.setGeometry(QtCore.QRect(180, 30, 153, 22))
        self.em1500_eMode.setReadOnly(True)
        self.em1500_eMode.setObjectName("em1500_eMode")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 230, 351, 291))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(80, 30, 81, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.em1500_amp_1 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.em1500_amp_1.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em1500_amp_1.setObjectName("em1500_amp_1")
        self.em1500_amp_2 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.em1500_amp_2.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em1500_amp_2.setObjectName("em1500_amp_2")
        self.em1500_amp_0 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.em1500_amp_0.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em1500_amp_0.setObjectName("em1500_amp_0")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_9.setGeometry(QtCore.QRect(170, 30, 81, 121))
        self.groupBox_9.setObjectName("groupBox_9")
        self.em1500_freq_1 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.em1500_freq_1.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em1500_freq_1.setObjectName("em1500_freq_1")
        self.em1500_freq_2 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.em1500_freq_2.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em1500_freq_2.setObjectName("em1500_freq_2")
        self.em1500_freq_0 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.em1500_freq_0.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em1500_freq_0.setObjectName("em1500_freq_0")
        self.groupBox_26 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_26.setGeometry(QtCore.QRect(260, 30, 81, 121))
        self.groupBox_26.setObjectName("groupBox_26")
        self.em1500_phase_1 = QtWidgets.QDoubleSpinBox(self.groupBox_26)
        self.em1500_phase_1.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em1500_phase_1.setObjectName("em1500_phase_1")
        self.em1500_phase_2 = QtWidgets.QDoubleSpinBox(self.groupBox_26)
        self.em1500_phase_2.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em1500_phase_2.setObjectName("em1500_phase_2")
        self.em1500_phase_0 = QtWidgets.QDoubleSpinBox(self.groupBox_26)
        self.em1500_phase_0.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em1500_phase_0.setObjectName("em1500_phase_0")
        self.groupBox_27 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_27.setGeometry(QtCore.QRect(80, 160, 81, 121))
        self.groupBox_27.setObjectName("groupBox_27")
        self.em1500_amp_4 = QtWidgets.QDoubleSpinBox(self.groupBox_27)
        self.em1500_amp_4.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em1500_amp_4.setObjectName("em1500_amp_4")
        self.em1500_amp_5 = QtWidgets.QDoubleSpinBox(self.groupBox_27)
        self.em1500_amp_5.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em1500_amp_5.setObjectName("em1500_amp_5")
        self.em1500_amp_3 = QtWidgets.QDoubleSpinBox(self.groupBox_27)
        self.em1500_amp_3.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em1500_amp_3.setObjectName("em1500_amp_3")
        self.groupBox_28 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_28.setGeometry(QtCore.QRect(170, 160, 81, 121))
        self.groupBox_28.setObjectName("groupBox_28")
        self.em1500_freq_4 = QtWidgets.QDoubleSpinBox(self.groupBox_28)
        self.em1500_freq_4.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em1500_freq_4.setObjectName("em1500_freq_4")
        self.em1500_freq_5 = QtWidgets.QDoubleSpinBox(self.groupBox_28)
        self.em1500_freq_5.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em1500_freq_5.setObjectName("em1500_freq_5")
        self.em1500_freq_3 = QtWidgets.QDoubleSpinBox(self.groupBox_28)
        self.em1500_freq_3.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em1500_freq_3.setObjectName("em1500_freq_3")
        self.groupBox_29 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_29.setGeometry(QtCore.QRect(260, 160, 81, 121))
        self.groupBox_29.setObjectName("groupBox_29")
        self.em1500_phase_4 = QtWidgets.QDoubleSpinBox(self.groupBox_29)
        self.em1500_phase_4.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em1500_phase_4.setObjectName("em1500_phase_4")
        self.em1500_phase_5 = QtWidgets.QDoubleSpinBox(self.groupBox_29)
        self.em1500_phase_5.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em1500_phase_5.setObjectName("em1500_phase_5")
        self.em1500_phase_3 = QtWidgets.QDoubleSpinBox(self.groupBox_29)
        self.em1500_phase_3.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em1500_phase_3.setObjectName("em1500_phase_3")
        self.groupBox_31 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_31.setGeometry(QtCore.QRect(10, 30, 61, 251))
        self.groupBox_31.setObjectName("groupBox_31")
        self.label_5 = QtWidgets.QLabel(self.groupBox_31)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 51, 16))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_31)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 51, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.groupBox_31)
        self.label.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.groupBox_31)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 51, 16))
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox_31)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_31)
        self.label_4.setGeometry(QtCore.QRect(10, 220, 51, 16))
        self.label_4.setObjectName("label_4")
        self.groupBox_32 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_32.setGeometry(QtCore.QRect(370, 10, 901, 811))
        self.groupBox_32.setObjectName("groupBox_32")
        self.em1500_plot = GraphicsLayoutWidget(self.groupBox_32)
        self.em1500_plot.setGeometry(QtCore.QRect(10, 30, 881, 771))
        self.em1500_plot.setObjectName("em1500_plot")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 520, 351, 301))
        self.groupBox_7.setObjectName("groupBox_7")
        self.em1500_cylinder_1 = QtWidgets.QProgressBar(self.groupBox_7)
        self.em1500_cylinder_1.setGeometry(QtCore.QRect(21, 31, 38, 240))
        self.em1500_cylinder_1.setMinimum(-100)
        self.em1500_cylinder_1.setProperty("value", 0)
        self.em1500_cylinder_1.setOrientation(QtCore.Qt.Vertical)
        self.em1500_cylinder_1.setInvertedAppearance(False)
        self.em1500_cylinder_1.setObjectName("em1500_cylinder_1")
        self.label_41 = QtWidgets.QLabel(self.groupBox_7)
        self.label_41.setGeometry(QtCore.QRect(239, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_7)
        self.label_42.setGeometry(QtCore.QRect(293, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_7)
        self.label_43.setGeometry(QtCore.QRect(188, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.groupBox_7)
        self.label_44.setGeometry(QtCore.QRect(132, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_7)
        self.label_45.setGeometry(QtCore.QRect(82, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_7)
        self.label_46.setGeometry(QtCore.QRect(28, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.em1500_cylinder_2 = QtWidgets.QProgressBar(self.groupBox_7)
        self.em1500_cylinder_2.setGeometry(QtCore.QRect(74, 31, 38, 240))
        self.em1500_cylinder_2.setMinimum(-100)
        self.em1500_cylinder_2.setProperty("value", 0)
        self.em1500_cylinder_2.setOrientation(QtCore.Qt.Vertical)
        self.em1500_cylinder_2.setInvertedAppearance(False)
        self.em1500_cylinder_2.setObjectName("em1500_cylinder_2")
        self.em1500_cylinder_3 = QtWidgets.QProgressBar(self.groupBox_7)
        self.em1500_cylinder_3.setGeometry(QtCore.QRect(126, 31, 38, 240))
        self.em1500_cylinder_3.setMinimum(-100)
        self.em1500_cylinder_3.setProperty("value", 0)
        self.em1500_cylinder_3.setOrientation(QtCore.Qt.Vertical)
        self.em1500_cylinder_3.setInvertedAppearance(False)
        self.em1500_cylinder_3.setObjectName("em1500_cylinder_3")
        self.em1500_cylinder_4 = QtWidgets.QProgressBar(self.groupBox_7)
        self.em1500_cylinder_4.setGeometry(QtCore.QRect(179, 31, 38, 240))
        self.em1500_cylinder_4.setMinimum(-100)
        self.em1500_cylinder_4.setProperty("value", 0)
        self.em1500_cylinder_4.setOrientation(QtCore.Qt.Vertical)
        self.em1500_cylinder_4.setInvertedAppearance(False)
        self.em1500_cylinder_4.setObjectName("em1500_cylinder_4")
        self.em1500_cylinder_5 = QtWidgets.QProgressBar(self.groupBox_7)
        self.em1500_cylinder_5.setGeometry(QtCore.QRect(231, 31, 38, 240))
        self.em1500_cylinder_5.setMinimum(-100)
        self.em1500_cylinder_5.setProperty("value", 0)
        self.em1500_cylinder_5.setOrientation(QtCore.Qt.Vertical)
        self.em1500_cylinder_5.setInvertedAppearance(False)
        self.em1500_cylinder_5.setObjectName("em1500_cylinder_5")
        self.em1500_cylinder_6 = QtWidgets.QProgressBar(self.groupBox_7)
        self.em1500_cylinder_6.setGeometry(QtCore.QRect(284, 31, 38, 240))
        self.em1500_cylinder_6.setMinimum(-100)
        self.em1500_cylinder_6.setProperty("value", 0)
        self.em1500_cylinder_6.setOrientation(QtCore.Qt.Vertical)
        self.em1500_cylinder_6.setInvertedAppearance(False)
        self.em1500_cylinder_6.setObjectName("em1500_cylinder_6")
        self.groupBox = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 351, 121))
        self.groupBox.setObjectName("groupBox")
        self.em1500_eOpMode = QtWidgets.QLineEdit(self.groupBox)
        self.em1500_eOpMode.setGeometry(QtCore.QRect(180, 85, 153, 22))
        self.em1500_eOpMode.setReadOnly(True)
        self.em1500_eOpMode.setObjectName("em1500_eOpMode")
        self.em1500_eStatus = QtWidgets.QLineEdit(self.groupBox)
        self.em1500_eStatus.setGeometry(QtCore.QRect(180, 55, 153, 22))
        self.em1500_eStatus.setReadOnly(True)
        self.em1500_eStatus.setObjectName("em1500_eStatus")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(19, 26, 141, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(19, 56, 141, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(19, 86, 141, 16))
        self.label_15.setObjectName("label_15")
        self.em1500_eState = QtWidgets.QLineEdit(self.groupBox)
        self.em1500_eState.setGeometry(QtCore.QRect(180, 25, 153, 22))
        self.em1500_eState.setReadOnly(True)
        self.em1500_eState.setObjectName("em1500_eState")
        self.tabSelector.addTab(self.tab_8, "")
        self.tab_interface = QtWidgets.QWidget()
        self.tab_interface.setObjectName("tab_interface")
        self.EM8000_settled_btn = QtWidgets.QPushButton(self.tab_interface)
        self.EM8000_settled_btn.setGeometry(QtCore.QRect(30, 110, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EM8000_settled_btn.setFont(font)
        self.EM8000_settled_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EM8000_settled_btn.setAutoFillBackground(False)
        self.EM8000_settled_btn.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.EM8000_settled_btn.setAutoDefault(False)
        self.EM8000_settled_btn.setDefault(False)
        self.EM8000_settled_btn.setFlat(False)
        self.EM8000_settled_btn.setObjectName("EM8000_settled_btn")
        self.EM8000_neutral_btn = QtWidgets.QPushButton(self.tab_interface)
        self.EM8000_neutral_btn.setGeometry(QtCore.QRect(30, 160, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EM8000_neutral_btn.setFont(font)
        self.EM8000_neutral_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EM8000_neutral_btn.setStyleSheet("selection-background-color: rgb(184, 255, 69);\n"
"border-color: rgb(0, 170, 127);")
        self.EM8000_neutral_btn.setCheckable(False)
        self.EM8000_neutral_btn.setAutoDefault(False)
        self.EM8000_neutral_btn.setObjectName("EM8000_neutral_btn")
        self.EM8000_engaged_btn = QtWidgets.QPushButton(self.tab_interface)
        self.EM8000_engaged_btn.setGeometry(QtCore.QRect(30, 210, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EM8000_engaged_btn.setFont(font)
        self.EM8000_engaged_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EM8000_engaged_btn.setAutoDefault(False)
        self.EM8000_engaged_btn.setObjectName("EM8000_engaged_btn")
        self.EM1500_settled_btn = QtWidgets.QPushButton(self.tab_interface)
        self.EM1500_settled_btn.setGeometry(QtCore.QRect(220, 110, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EM1500_settled_btn.setFont(font)
        self.EM1500_settled_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EM1500_settled_btn.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.EM1500_settled_btn.setAutoDefault(False)
        self.EM1500_settled_btn.setObjectName("EM1500_settled_btn")
        self.EM1500_neutral_btn = QtWidgets.QPushButton(self.tab_interface)
        self.EM1500_neutral_btn.setGeometry(QtCore.QRect(220, 160, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EM1500_neutral_btn.setFont(font)
        self.EM1500_neutral_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EM1500_neutral_btn.setAutoDefault(False)
        self.EM1500_neutral_btn.setObjectName("EM1500_neutral_btn")
        self.EM1500_engaged_btn = QtWidgets.QPushButton(self.tab_interface)
        self.EM1500_engaged_btn.setGeometry(QtCore.QRect(220, 210, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EM1500_engaged_btn.setFont(font)
        self.EM1500_engaged_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EM1500_engaged_btn.setAutoDefault(False)
        self.EM1500_engaged_btn.setObjectName("EM1500_engaged_btn")
        self.COMAU_settled_btn = QtWidgets.QPushButton(self.tab_interface)
        self.COMAU_settled_btn.setGeometry(QtCore.QRect(410, 110, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.COMAU_settled_btn.setFont(font)
        self.COMAU_settled_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.COMAU_settled_btn.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.COMAU_settled_btn.setAutoDefault(False)
        self.COMAU_settled_btn.setObjectName("COMAU_settled_btn")
        self.COMAU_engaged_fast_btn = QtWidgets.QPushButton(self.tab_interface)
        self.COMAU_engaged_fast_btn.setGeometry(QtCore.QRect(410, 210, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.COMAU_engaged_fast_btn.setFont(font)
        self.COMAU_engaged_fast_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.COMAU_engaged_fast_btn.setAutoDefault(False)
        self.COMAU_engaged_fast_btn.setObjectName("COMAU_engaged_fast_btn")
        self.COMAU_engaged_btn = QtWidgets.QPushButton(self.tab_interface)
        self.COMAU_engaged_btn.setGeometry(QtCore.QRect(410, 160, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.COMAU_engaged_btn.setFont(font)
        self.COMAU_engaged_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.COMAU_engaged_btn.setAutoDefault(False)
        self.COMAU_engaged_btn.setObjectName("COMAU_engaged_btn")
        self.label_8 = QtWidgets.QLabel(self.tab_interface)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 181, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.tab_interface)
        self.line.setGeometry(QtCore.QRect(20, 40, 1071, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_EM8000 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_EM8000.setGeometry(QtCore.QRect(20, 70, 161, 181))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_EM8000.setFont(font)
        self.groupBox_EM8000.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_EM8000.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_EM8000.setObjectName("groupBox_EM8000")
        self.groupBox_EM1500 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_EM1500.setGeometry(QtCore.QRect(210, 70, 161, 181))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_EM1500.setFont(font)
        self.groupBox_EM1500.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_EM1500.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_EM1500.setObjectName("groupBox_EM1500")
        self.groupBox_EM1500_2 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_EM1500_2.setGeometry(QtCore.QRect(400, 70, 161, 181))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_EM1500_2.setFont(font)
        self.groupBox_EM1500_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_EM1500_2.setStyleSheet("")
        self.groupBox_EM1500_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_EM1500_2.setObjectName("groupBox_EM1500_2")
        self.groupBox_EM1500_3 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_EM1500_3.setGeometry(QtCore.QRect(780, 70, 161, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_EM1500_3.setFont(font)
        self.groupBox_EM1500_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_EM1500_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_EM1500_3.setObjectName("groupBox_EM1500_3")
        self.SYSTEM_settled_btn = QtWidgets.QPushButton(self.groupBox_EM1500_3)
        self.SYSTEM_settled_btn.setGeometry(QtCore.QRect(10, 40, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SYSTEM_settled_btn.setFont(font)
        self.SYSTEM_settled_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SYSTEM_settled_btn.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.SYSTEM_settled_btn.setAutoDefault(False)
        self.SYSTEM_settled_btn.setObjectName("SYSTEM_settled_btn")
        self.SYSTEM_stop_btn = QtWidgets.QPushButton(self.groupBox_EM1500_3)
        self.SYSTEM_stop_btn.setGeometry(QtCore.QRect(10, 90, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SYSTEM_stop_btn.setFont(font)
        self.SYSTEM_stop_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SYSTEM_stop_btn.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.SYSTEM_stop_btn.setAutoDefault(False)
        self.SYSTEM_stop_btn.setObjectName("SYSTEM_stop_btn")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 440, 261, 291))
        self.groupBox_8.setObjectName("groupBox_8")
        self.EM8000_bar1_l1 = QtWidgets.QProgressBar(self.groupBox_8)
        self.EM8000_bar1_l1.setGeometry(QtCore.QRect(20, 30, 21, 221))
        self.EM8000_bar1_l1.setMinimum(-100)
        self.EM8000_bar1_l1.setProperty("value", 0)
        self.EM8000_bar1_l1.setOrientation(QtCore.Qt.Vertical)
        self.EM8000_bar1_l1.setInvertedAppearance(False)
        self.EM8000_bar1_l1.setObjectName("EM8000_bar1_l1")
        self.EM8000_bar1_l2 = QtWidgets.QProgressBar(self.groupBox_8)
        self.EM8000_bar1_l2.setGeometry(QtCore.QRect(60, 30, 21, 221))
        self.EM8000_bar1_l2.setMinimum(-100)
        self.EM8000_bar1_l2.setProperty("value", 0)
        self.EM8000_bar1_l2.setOrientation(QtCore.Qt.Vertical)
        self.EM8000_bar1_l2.setInvertedAppearance(False)
        self.EM8000_bar1_l2.setObjectName("EM8000_bar1_l2")
        self.EM8000_bar1_l3 = QtWidgets.QProgressBar(self.groupBox_8)
        self.EM8000_bar1_l3.setGeometry(QtCore.QRect(100, 30, 21, 221))
        self.EM8000_bar1_l3.setMinimum(-100)
        self.EM8000_bar1_l3.setProperty("value", 0)
        self.EM8000_bar1_l3.setOrientation(QtCore.Qt.Vertical)
        self.EM8000_bar1_l3.setInvertedAppearance(False)
        self.EM8000_bar1_l3.setObjectName("EM8000_bar1_l3")
        self.EM8000_bar1_l4 = QtWidgets.QProgressBar(self.groupBox_8)
        self.EM8000_bar1_l4.setGeometry(QtCore.QRect(140, 30, 21, 221))
        self.EM8000_bar1_l4.setMinimum(-100)
        self.EM8000_bar1_l4.setProperty("value", 0)
        self.EM8000_bar1_l4.setOrientation(QtCore.Qt.Vertical)
        self.EM8000_bar1_l4.setInvertedAppearance(False)
        self.EM8000_bar1_l4.setObjectName("EM8000_bar1_l4")
        self.EM8000_bar1_l5 = QtWidgets.QProgressBar(self.groupBox_8)
        self.EM8000_bar1_l5.setGeometry(QtCore.QRect(180, 30, 21, 221))
        self.EM8000_bar1_l5.setMinimum(-100)
        self.EM8000_bar1_l5.setProperty("value", 0)
        self.EM8000_bar1_l5.setOrientation(QtCore.Qt.Vertical)
        self.EM8000_bar1_l5.setInvertedAppearance(False)
        self.EM8000_bar1_l5.setObjectName("EM8000_bar1_l5")
        self.EM8000_bar1_l6 = QtWidgets.QProgressBar(self.groupBox_8)
        self.EM8000_bar1_l6.setGeometry(QtCore.QRect(220, 30, 21, 221))
        self.EM8000_bar1_l6.setMinimum(-100)
        self.EM8000_bar1_l6.setMaximum(100)
        self.EM8000_bar1_l6.setProperty("value", 0)
        self.EM8000_bar1_l6.setOrientation(QtCore.Qt.Vertical)
        self.EM8000_bar1_l6.setInvertedAppearance(False)
        self.EM8000_bar1_l6.setObjectName("EM8000_bar1_l6")
        self.label_21 = QtWidgets.QLabel(self.groupBox_8)
        self.label_21.setGeometry(QtCore.QRect(180, 260, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_47 = QtWidgets.QLabel(self.groupBox_8)
        self.label_47.setGeometry(QtCore.QRect(220, 260, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_8)
        self.label_48.setGeometry(QtCore.QRect(140, 260, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.groupBox_8)
        self.label_49.setGeometry(QtCore.QRect(100, 260, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.groupBox_8)
        self.label_50.setGeometry(QtCore.QRect(60, 260, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.groupBox_8)
        self.label_51.setGeometry(QtCore.QRect(20, 260, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_10.setGeometry(QtCore.QRect(580, 440, 261, 291))
        self.groupBox_10.setObjectName("groupBox_10")
        self.COMAU_bar1_j1 = QtWidgets.QProgressBar(self.groupBox_10)
        self.COMAU_bar1_j1.setGeometry(QtCore.QRect(20, 30, 21, 221))
        self.COMAU_bar1_j1.setMinimum(-100)
        self.COMAU_bar1_j1.setProperty("value", 0)
        self.COMAU_bar1_j1.setOrientation(QtCore.Qt.Vertical)
        self.COMAU_bar1_j1.setInvertedAppearance(False)
        self.COMAU_bar1_j1.setObjectName("COMAU_bar1_j1")
        self.COMAU_bar1_j2 = QtWidgets.QProgressBar(self.groupBox_10)
        self.COMAU_bar1_j2.setGeometry(QtCore.QRect(60, 30, 21, 221))
        self.COMAU_bar1_j2.setMinimum(-100)
        self.COMAU_bar1_j2.setProperty("value", 0)
        self.COMAU_bar1_j2.setOrientation(QtCore.Qt.Vertical)
        self.COMAU_bar1_j2.setInvertedAppearance(False)
        self.COMAU_bar1_j2.setObjectName("COMAU_bar1_j2")
        self.COMAU_bar1_j3 = QtWidgets.QProgressBar(self.groupBox_10)
        self.COMAU_bar1_j3.setGeometry(QtCore.QRect(100, 30, 21, 221))
        self.COMAU_bar1_j3.setMinimum(-100)
        self.COMAU_bar1_j3.setProperty("value", 0)
        self.COMAU_bar1_j3.setOrientation(QtCore.Qt.Vertical)
        self.COMAU_bar1_j3.setInvertedAppearance(False)
        self.COMAU_bar1_j3.setObjectName("COMAU_bar1_j3")
        self.COMAU_bar1_j4 = QtWidgets.QProgressBar(self.groupBox_10)
        self.COMAU_bar1_j4.setGeometry(QtCore.QRect(140, 30, 21, 221))
        self.COMAU_bar1_j4.setMinimum(-100)
        self.COMAU_bar1_j4.setProperty("value", 0)
        self.COMAU_bar1_j4.setOrientation(QtCore.Qt.Vertical)
        self.COMAU_bar1_j4.setInvertedAppearance(False)
        self.COMAU_bar1_j4.setObjectName("COMAU_bar1_j4")
        self.COMAU_bar1_j5 = QtWidgets.QProgressBar(self.groupBox_10)
        self.COMAU_bar1_j5.setGeometry(QtCore.QRect(180, 30, 21, 221))
        self.COMAU_bar1_j5.setMinimum(-100)
        self.COMAU_bar1_j5.setProperty("value", 0)
        self.COMAU_bar1_j5.setOrientation(QtCore.Qt.Vertical)
        self.COMAU_bar1_j5.setInvertedAppearance(False)
        self.COMAU_bar1_j5.setObjectName("COMAU_bar1_j5")
        self.COMAU_bar1_j6 = QtWidgets.QProgressBar(self.groupBox_10)
        self.COMAU_bar1_j6.setGeometry(QtCore.QRect(220, 30, 21, 221))
        self.COMAU_bar1_j6.setMinimum(-100)
        self.COMAU_bar1_j6.setProperty("value", 0)
        self.COMAU_bar1_j6.setOrientation(QtCore.Qt.Vertical)
        self.COMAU_bar1_j6.setInvertedAppearance(False)
        self.COMAU_bar1_j6.setObjectName("COMAU_bar1_j6")
        self.label_52 = QtWidgets.QLabel(self.groupBox_10)
        self.label_52.setGeometry(QtCore.QRect(180, 260, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.groupBox_10)
        self.label_53.setGeometry(QtCore.QRect(220, 260, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.groupBox_10)
        self.label_54.setGeometry(QtCore.QRect(140, 260, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.groupBox_10)
        self.label_55.setGeometry(QtCore.QRect(100, 260, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.groupBox_10)
        self.label_56.setGeometry(QtCore.QRect(60, 260, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.groupBox_10)
        self.label_57.setGeometry(QtCore.QRect(20, 260, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.groupBox_EM1500_5 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_EM1500_5.setGeometry(QtCore.QRect(590, 70, 161, 281))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_EM1500_5.setFont(font)
        self.groupBox_EM1500_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_EM1500_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_EM1500_5.setObjectName("groupBox_EM1500_5")
        self.winchOff = QtWidgets.QPushButton(self.groupBox_EM1500_5)
        self.winchOff.setGeometry(QtCore.QRect(10, 190, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.winchOff.setFont(font)
        self.winchOff.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.winchOff.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.winchOff.setAutoDefault(False)
        self.winchOff.setObjectName("winchOff")
        self.winchOn = QtWidgets.QPushButton(self.groupBox_EM1500_5)
        self.winchOn.setGeometry(QtCore.QRect(10, 240, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.winchOn.setFont(font)
        self.winchOn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.winchOn.setAutoDefault(False)
        self.winchOn.setObjectName("winchOn")
        self.winchEngagedFast = QtWidgets.QPushButton(self.groupBox_EM1500_5)
        self.winchEngagedFast.setGeometry(QtCore.QRect(10, 140, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.winchEngagedFast.setFont(font)
        self.winchEngagedFast.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.winchEngagedFast.setAutoDefault(False)
        self.winchEngagedFast.setObjectName("winchEngagedFast")
        self.winchSettled = QtWidgets.QPushButton(self.groupBox_EM1500_5)
        self.winchSettled.setGeometry(QtCore.QRect(10, 40, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.winchSettled.setFont(font)
        self.winchSettled.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.winchSettled.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.winchSettled.setAutoDefault(False)
        self.winchSettled.setObjectName("winchSettled")
        self.winchEngaged = QtWidgets.QPushButton(self.groupBox_EM1500_5)
        self.winchEngaged.setGeometry(QtCore.QRect(10, 90, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.winchEngaged.setFont(font)
        self.winchEngaged.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.winchEngaged.setAutoDefault(False)
        self.winchEngaged.setObjectName("winchEngaged")
        self.show3dView = QtWidgets.QPushButton(self.tab_interface)
        self.show3dView.setGeometry(QtCore.QRect(890, 630, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show3dView.setFont(font)
        self.show3dView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.show3dView.setAutoDefault(False)
        self.show3dView.setObjectName("show3dView")
        self.groupBox_EM1500_4 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_EM1500_4.setGeometry(QtCore.QRect(970, 70, 121, 401))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_EM1500_4.setFont(font)
        self.groupBox_EM1500_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_EM1500_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_EM1500_4.setObjectName("groupBox_EM1500_4")
        self.activeEM8000 = QtWidgets.QCheckBox(self.groupBox_EM1500_4)
        self.activeEM8000.setGeometry(QtCore.QRect(20, 40, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.activeEM8000.setFont(font)
        self.activeEM8000.setIconSize(QtCore.QSize(16, 16))
        self.activeEM8000.setCheckable(False)
        self.activeEM8000.setTristate(False)
        self.activeEM8000.setObjectName("activeEM8000")
        self.activeEM1500 = QtWidgets.QCheckBox(self.groupBox_EM1500_4)
        self.activeEM1500.setGeometry(QtCore.QRect(20, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.activeEM1500.setFont(font)
        self.activeEM1500.setIconSize(QtCore.QSize(16, 16))
        self.activeEM1500.setCheckable(False)
        self.activeEM1500.setTristate(False)
        self.activeEM1500.setObjectName("activeEM1500")
        self.activeCOMAU = QtWidgets.QCheckBox(self.groupBox_EM1500_4)
        self.activeCOMAU.setGeometry(QtCore.QRect(20, 200, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.activeCOMAU.setFont(font)
        self.activeCOMAU.setIconSize(QtCore.QSize(16, 16))
        self.activeCOMAU.setCheckable(False)
        self.activeCOMAU.setTristate(False)
        self.activeCOMAU.setObjectName("activeCOMAU")
        self.activeWINCH = QtWidgets.QCheckBox(self.groupBox_EM1500_4)
        self.activeWINCH.setGeometry(QtCore.QRect(20, 240, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.activeWINCH.setFont(font)
        self.activeWINCH.setIconSize(QtCore.QSize(16, 16))
        self.activeWINCH.setCheckable(False)
        self.activeWINCH.setTristate(False)
        self.activeWINCH.setObjectName("activeWINCH")
        self.activeLEICA = QtWidgets.QCheckBox(self.groupBox_EM1500_4)
        self.activeLEICA.setGeometry(QtCore.QRect(20, 280, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.activeLEICA.setFont(font)
        self.activeLEICA.setIconSize(QtCore.QSize(16, 16))
        self.activeLEICA.setCheckable(False)
        self.activeLEICA.setTristate(False)
        self.activeLEICA.setObjectName("activeLEICA")
        self.activeQTM = QtWidgets.QCheckBox(self.groupBox_EM1500_4)
        self.activeQTM.setGeometry(QtCore.QRect(20, 320, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.activeQTM.setFont(font)
        self.activeQTM.setIconSize(QtCore.QSize(16, 16))
        self.activeQTM.setCheckable(False)
        self.activeQTM.setTristate(False)
        self.activeQTM.setObjectName("activeQTM")
        self.activeMRU1 = QtWidgets.QCheckBox(self.groupBox_EM1500_4)
        self.activeMRU1.setGeometry(QtCore.QRect(20, 120, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.activeMRU1.setFont(font)
        self.activeMRU1.setIconSize(QtCore.QSize(16, 16))
        self.activeMRU1.setCheckable(False)
        self.activeMRU1.setTristate(False)
        self.activeMRU1.setObjectName("activeMRU1")
        self.activeMRU2 = QtWidgets.QCheckBox(self.groupBox_EM1500_4)
        self.activeMRU2.setGeometry(QtCore.QRect(20, 160, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.activeMRU2.setFont(font)
        self.activeMRU2.setIconSize(QtCore.QSize(16, 16))
        self.activeMRU2.setCheckable(False)
        self.activeMRU2.setTristate(False)
        self.activeMRU2.setObjectName("activeMRU2")
        self.activeXBOX = QtWidgets.QCheckBox(self.groupBox_EM1500_4)
        self.activeXBOX.setGeometry(QtCore.QRect(20, 360, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.activeXBOX.setFont(font)
        self.activeXBOX.setIconSize(QtCore.QSize(16, 16))
        self.activeXBOX.setCheckable(False)
        self.activeXBOX.setTristate(False)
        self.activeXBOX.setObjectName("activeXBOX")
        self.groupBox_EM8000.raise_()
        self.groupBox_EM1500_2.raise_()
        self.groupBox_EM1500.raise_()
        self.EM8000_settled_btn.raise_()
        self.EM8000_neutral_btn.raise_()
        self.EM8000_engaged_btn.raise_()
        self.EM1500_settled_btn.raise_()
        self.EM1500_neutral_btn.raise_()
        self.EM1500_engaged_btn.raise_()
        self.COMAU_settled_btn.raise_()
        self.COMAU_engaged_fast_btn.raise_()
        self.COMAU_engaged_btn.raise_()
        self.label_8.raise_()
        self.line.raise_()
        self.groupBox_EM1500_3.raise_()
        self.groupBox_8.raise_()
        self.groupBox_10.raise_()
        self.groupBox_EM1500_5.raise_()
        self.show3dView.raise_()
        self.groupBox_EM1500_4.raise_()
        self.tabSelector.addTab(self.tab_interface, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabSelector.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabSelector.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabSelector.addTab(self.tab_3, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tabSelector.addTab(self.tab_12, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabSelector.addTab(self.tab_9, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.line_6 = QtWidgets.QFrame(self.tab_5)
        self.line_6.setGeometry(QtCore.QRect(20, 40, 1071, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_58 = QtWidgets.QLabel(self.tab_5)
        self.label_58.setGeometry(QtCore.QRect(30, 20, 681, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.tab_6 = QtWidgets.QTabWidget(self.tab_5)
        self.tab_6.setGeometry(QtCore.QRect(300, 70, 791, 701))
        self.tab_6.setObjectName("tab_6")
        self.widget_2 = QtWidgets.QWidget()
        self.widget_2.setObjectName("widget_2")
        self.DP1_SimStates = GraphicsLayoutWidget(self.widget_2)
        self.DP1_SimStates.setGeometry(QtCore.QRect(0, 0, 791, 671))
        self.DP1_SimStates.setObjectName("DP1_SimStates")
        self.tab_6.addTab(self.widget_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.DP2_SimStates = GraphicsLayoutWidget(self.tab_7)
        self.DP2_SimStates.setGeometry(QtCore.QRect(0, 0, 791, 671))
        self.DP2_SimStates.setObjectName("DP2_SimStates")
        self.tab_6.addTab(self.tab_7, "")
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_23.setGeometry(QtCore.QRect(20, 70, 261, 321))
        self.groupBox_23.setObjectName("groupBox_23")
        self.label_149 = QtWidgets.QLabel(self.groupBox_23)
        self.label_149.setGeometry(QtCore.QRect(220, 60, 31, 20))
        self.label_149.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_149.setObjectName("label_149")
        self.label_151 = QtWidgets.QLabel(self.groupBox_23)
        self.label_151.setGeometry(QtCore.QRect(220, 30, 31, 20))
        self.label_151.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_151.setObjectName("label_151")
        self.label_152 = QtWidgets.QLabel(self.groupBox_23)
        self.label_152.setGeometry(QtCore.QRect(10, 31, 151, 20))
        self.label_152.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_152.setObjectName("label_152")
        self.label_159 = QtWidgets.QLabel(self.groupBox_23)
        self.label_159.setGeometry(QtCore.QRect(10, 60, 151, 20))
        self.label_159.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_159.setObjectName("label_159")
        self.label_160 = QtWidgets.QLabel(self.groupBox_23)
        self.label_160.setGeometry(QtCore.QRect(10, 90, 141, 20))
        self.label_160.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_160.setObjectName("label_160")
        self.EM8000_wave_spectra = QtWidgets.QComboBox(self.groupBox_23)
        self.EM8000_wave_spectra.setGeometry(QtCore.QRect(160, 90, 81, 22))
        self.EM8000_wave_spectra.setObjectName("EM8000_wave_spectra")
        self.EM8000_wave_spectra.addItem("")
        self.EM8000_wave_spectra.addItem("")
        self.EM8000_wave_height = QtWidgets.QLineEdit(self.groupBox_23)
        self.EM8000_wave_height.setGeometry(QtCore.QRect(160, 30, 51, 20))
        self.EM8000_wave_height.setClearButtonEnabled(False)
        self.EM8000_wave_height.setObjectName("EM8000_wave_height")
        self.EM8000_wave_period = QtWidgets.QLineEdit(self.groupBox_23)
        self.EM8000_wave_period.setGeometry(QtCore.QRect(160, 60, 51, 20))
        self.EM8000_wave_period.setClearButtonEnabled(False)
        self.EM8000_wave_period.setObjectName("EM8000_wave_period")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_15.setGeometry(QtCore.QRect(20, 400, 261, 51))
        self.groupBox_15.setObjectName("groupBox_15")
        self.label_109 = QtWidgets.QLabel(self.groupBox_15)
        self.label_109.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.label_109.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_109.setObjectName("label_109")
        self.EM8000_plot_time_range_ship = QtWidgets.QComboBox(self.groupBox_15)
        self.EM8000_plot_time_range_ship.setGeometry(QtCore.QRect(130, 20, 69, 22))
        self.EM8000_plot_time_range_ship.setObjectName("EM8000_plot_time_range_ship")
        self.EM8000_plot_time_range_ship.addItem("")
        self.EM8000_plot_time_range_ship.addItem("")
        self.EM8000_plot_time_range_ship.addItem("")
        self.EM8000_plot_time_range_ship.addItem("")
        self.EM8000_plot_time_range_ship.addItem("")
        self.EM8000_plot_time_range_ship.addItem("")
        self.label_110 = QtWidgets.QLabel(self.groupBox_15)
        self.label_110.setGeometry(QtCore.QRect(210, 20, 31, 20))
        self.label_110.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_110.setObjectName("label_110")
        self.DP1_wavespectrum = GraphicsLayoutWidget(self.tab_5)
        self.DP1_wavespectrum.setGeometry(QtCore.QRect(20, 467, 261, 301))
        self.DP1_wavespectrum.setObjectName("DP1_wavespectrum")
        self.tabSelector.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        self.label_34.setGeometry(QtCore.QRect(30, 20, 581, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.line_4 = QtWidgets.QFrame(self.tab_4)
        self.line_4.setGeometry(QtCore.QRect(20, 40, 1071, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.estimatedDampingPlot = QtWidgets.QTabWidget(self.tab_4)
        self.estimatedDampingPlot.setGeometry(QtCore.QRect(300, 70, 791, 701))
        self.estimatedDampingPlot.setTabBarAutoHide(False)
        self.estimatedDampingPlot.setObjectName("estimatedDampingPlot")
        self.widget_3 = QtWidgets.QWidget()
        self.widget_3.setObjectName("widget_3")
        self.swingAnglesWidget = GraphicsLayoutWidget(self.widget_3)
        self.swingAnglesWidget.setGeometry(QtCore.QRect(0, 0, 791, 335))
        self.swingAnglesWidget.setObjectName("swingAnglesWidget")
        self.swingVelocityWidget = GraphicsLayoutWidget(self.widget_3)
        self.swingVelocityWidget.setGeometry(QtCore.QRect(0, 337, 791, 335))
        self.swingVelocityWidget.setObjectName("swingVelocityWidget")
        self.estimatedDampingPlot.addTab(self.widget_3, "")
        self.DampingParamter = QtWidgets.QWidget()
        self.DampingParamter.setObjectName("DampingParamter")
        self.dampingParamPlotWidget = GraphicsLayoutWidget(self.DampingParamter)
        self.dampingParamPlotWidget.setGeometry(QtCore.QRect(0, 0, 791, 671))
        self.dampingParamPlotWidget.setObjectName("dampingParamPlotWidget")
        self.estimatedDampingPlot.addTab(self.DampingParamter, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.errorStatePlotWidget = GraphicsLayoutWidget(self.tab_10)
        self.errorStatePlotWidget.setGeometry(QtCore.QRect(0, 0, 791, 671))
        self.errorStatePlotWidget.setObjectName("errorStatePlotWidget")
        self.estimatedDampingPlot.addTab(self.tab_10, "")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_17.setGeometry(QtCore.QRect(20, 70, 241, 51))
        self.groupBox_17.setObjectName("groupBox_17")
        self.label_98 = QtWidgets.QLabel(self.groupBox_17)
        self.label_98.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.label_98.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_98.setObjectName("label_98")
        self.antiSwayPlotRange = QtWidgets.QComboBox(self.groupBox_17)
        self.antiSwayPlotRange.setGeometry(QtCore.QRect(130, 20, 69, 22))
        self.antiSwayPlotRange.setObjectName("antiSwayPlotRange")
        self.antiSwayPlotRange.addItem("")
        self.antiSwayPlotRange.addItem("")
        self.antiSwayPlotRange.addItem("")
        self.antiSwayPlotRange.addItem("")
        self.antiSwayPlotRange.addItem("")
        self.antiSwayPlotRange.addItem("")
        self.label_99 = QtWidgets.QLabel(self.groupBox_17)
        self.label_99.setGeometry(QtCore.QRect(210, 20, 31, 20))
        self.label_99.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_99.setObjectName("label_99")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_18.setGeometry(QtCore.QRect(20, 330, 241, 151))
        self.groupBox_18.setObjectName("groupBox_18")
        self.btnDeactivateAntiSway = QtWidgets.QPushButton(self.groupBox_18)
        self.btnDeactivateAntiSway.setGeometry(QtCore.QRect(10, 70, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDeactivateAntiSway.setFont(font)
        self.btnDeactivateAntiSway.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnDeactivateAntiSway.setAutoDefault(False)
        self.btnDeactivateAntiSway.setObjectName("btnDeactivateAntiSway")
        self.btnActivateAntiSway = QtWidgets.QPushButton(self.groupBox_18)
        self.btnActivateAntiSway.setGeometry(QtCore.QRect(10, 30, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnActivateAntiSway.setFont(font)
        self.btnActivateAntiSway.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnActivateAntiSway.setAutoDefault(False)
        self.btnActivateAntiSway.setObjectName("btnActivateAntiSway")
        self.btnResetAntiSway = QtWidgets.QPushButton(self.groupBox_18)
        self.btnResetAntiSway.setGeometry(QtCore.QRect(10, 110, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnResetAntiSway.setFont(font)
        self.btnResetAntiSway.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnResetAntiSway.setAutoDefault(False)
        self.btnResetAntiSway.setObjectName("btnResetAntiSway")
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_24.setGeometry(QtCore.QRect(20, 160, 241, 151))
        self.groupBox_24.setObjectName("groupBox_24")
        self.btnEnableMruEKF = QtWidgets.QPushButton(self.groupBox_24)
        self.btnEnableMruEKF.setGeometry(QtCore.QRect(10, 70, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEnableMruEKF.setFont(font)
        self.btnEnableMruEKF.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnEnableMruEKF.setAutoDefault(False)
        self.btnEnableMruEKF.setObjectName("btnEnableMruEKF")
        self.btnDisableMruEKF = QtWidgets.QPushButton(self.groupBox_24)
        self.btnDisableMruEKF.setGeometry(QtCore.QRect(10, 30, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDisableMruEKF.setFont(font)
        self.btnDisableMruEKF.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnDisableMruEKF.setAutoDefault(False)
        self.btnDisableMruEKF.setObjectName("btnDisableMruEKF")
        self.btnResetEKF = QtWidgets.QPushButton(self.groupBox_24)
        self.btnResetEKF.setGeometry(QtCore.QRect(10, 110, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnResetEKF.setFont(font)
        self.btnResetEKF.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnResetEKF.setAutoDefault(False)
        self.btnResetEKF.setObjectName("btnResetEKF")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_19.setGeometry(QtCore.QRect(20, 630, 241, 111))
        self.groupBox_19.setObjectName("groupBox_19")
        self.btnEnableMruCM = QtWidgets.QPushButton(self.groupBox_19)
        self.btnEnableMruCM.setGeometry(QtCore.QRect(10, 70, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEnableMruCM.setFont(font)
        self.btnEnableMruCM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnEnableMruCM.setAutoDefault(False)
        self.btnEnableMruCM.setObjectName("btnEnableMruCM")
        self.btnDisableMruCM = QtWidgets.QPushButton(self.groupBox_19)
        self.btnDisableMruCM.setGeometry(QtCore.QRect(10, 30, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDisableMruCM.setFont(font)
        self.btnDisableMruCM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnDisableMruCM.setAutoDefault(False)
        self.btnDisableMruCM.setObjectName("btnDisableMruCM")
        self.groupBox_25 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_25.setGeometry(QtCore.QRect(20, 500, 241, 111))
        self.groupBox_25.setObjectName("groupBox_25")
        self.btnEnableMruWinch = QtWidgets.QPushButton(self.groupBox_25)
        self.btnEnableMruWinch.setGeometry(QtCore.QRect(10, 70, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEnableMruWinch.setFont(font)
        self.btnEnableMruWinch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnEnableMruWinch.setAutoDefault(False)
        self.btnEnableMruWinch.setObjectName("btnEnableMruWinch")
        self.btnDisableMruWinch = QtWidgets.QPushButton(self.groupBox_25)
        self.btnDisableMruWinch.setGeometry(QtCore.QRect(10, 30, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDisableMruWinch.setFont(font)
        self.btnDisableMruWinch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnDisableMruWinch.setAutoDefault(False)
        self.btnDisableMruWinch.setObjectName("btnDisableMruWinch")
        self.tabSelector.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabSelector, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_open_file = QtWidgets.QAction(MainWindow)
        self.menu_open_file.setObjectName("menu_open_file")
        self.menu_save_file = QtWidgets.QAction(MainWindow)
        self.menu_save_file.setObjectName("menu_save_file")

        self.retranslateUi(MainWindow)
        self.tabSelector.setCurrentIndex(1)
        self.tab_6.setCurrentIndex(1)
        self.EM8000_wave_spectra.setCurrentIndex(0)
        self.EM8000_plot_time_range_ship.setCurrentIndex(1)
        self.estimatedDampingPlot.setCurrentIndex(0)
        self.antiSwayPlotRange.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.em1500_eModeCmd, self.em1500_engage)
        MainWindow.setTabOrder(self.em1500_engage, self.em1500_disengage)
        MainWindow.setTabOrder(self.em1500_disengage, self.activeWINCH)
        MainWindow.setTabOrder(self.activeWINCH, self.em1500_amp_0)
        MainWindow.setTabOrder(self.em1500_amp_0, self.em1500_freq_0)
        MainWindow.setTabOrder(self.em1500_freq_0, self.em1500_phase_0)
        MainWindow.setTabOrder(self.em1500_phase_0, self.em1500_amp_1)
        MainWindow.setTabOrder(self.em1500_amp_1, self.em1500_freq_1)
        MainWindow.setTabOrder(self.em1500_freq_1, self.em1500_phase_1)
        MainWindow.setTabOrder(self.em1500_phase_1, self.em1500_amp_2)
        MainWindow.setTabOrder(self.em1500_amp_2, self.em1500_freq_2)
        MainWindow.setTabOrder(self.em1500_freq_2, self.em1500_phase_2)
        MainWindow.setTabOrder(self.em1500_phase_2, self.em1500_amp_3)
        MainWindow.setTabOrder(self.em1500_amp_3, self.em1500_freq_3)
        MainWindow.setTabOrder(self.em1500_freq_3, self.em1500_phase_3)
        MainWindow.setTabOrder(self.em1500_phase_3, self.em1500_amp_4)
        MainWindow.setTabOrder(self.em1500_amp_4, self.em1500_freq_4)
        MainWindow.setTabOrder(self.em1500_freq_4, self.em1500_phase_4)
        MainWindow.setTabOrder(self.em1500_phase_4, self.em1500_amp_5)
        MainWindow.setTabOrder(self.em1500_amp_5, self.em1500_freq_5)
        MainWindow.setTabOrder(self.em1500_freq_5, self.em1500_phase_5)
        MainWindow.setTabOrder(self.em1500_phase_5, self.activeLEICA)
        MainWindow.setTabOrder(self.activeLEICA, self.activeQTM)
        MainWindow.setTabOrder(self.activeQTM, self.activeMRU1)
        MainWindow.setTabOrder(self.activeMRU1, self.activeMRU2)
        MainWindow.setTabOrder(self.activeMRU2, self.activeXBOX)
        MainWindow.setTabOrder(self.activeXBOX, self.EM8000_settled_btn)
        MainWindow.setTabOrder(self.EM8000_settled_btn, self.em1500_eState)
        MainWindow.setTabOrder(self.em1500_eState, self.em1500_eStatus)
        MainWindow.setTabOrder(self.em1500_eStatus, self.em1500_eOpMode)
        MainWindow.setTabOrder(self.em1500_eOpMode, self.EM1500_neutral_btn)
        MainWindow.setTabOrder(self.EM1500_neutral_btn, self.SYSTEM_settled_btn)
        MainWindow.setTabOrder(self.SYSTEM_settled_btn, self.winchEngaged)
        MainWindow.setTabOrder(self.winchEngaged, self.em1500_plot)
        MainWindow.setTabOrder(self.em1500_plot, self._bStopEM8000)
        MainWindow.setTabOrder(self._bStopEM8000, self._bResetEM8000)
        MainWindow.setTabOrder(self._bResetEM8000, self._eModeEM8000)
        MainWindow.setTabOrder(self._eModeEM8000, self._plotModeEM8000)
        MainWindow.setTabOrder(self._plotModeEM8000, self._plotEM8000)
        MainWindow.setTabOrder(self._plotEM8000, self._ampEM8000_0)
        MainWindow.setTabOrder(self._ampEM8000_0, self._ampEM8000_1)
        MainWindow.setTabOrder(self._ampEM8000_1, self._ampEM8000_2)
        MainWindow.setTabOrder(self._ampEM8000_2, self._freqEM8000_0)
        MainWindow.setTabOrder(self._freqEM8000_0, self._freqEM8000_1)
        MainWindow.setTabOrder(self._freqEM8000_1, self._freqEM8000_2)
        MainWindow.setTabOrder(self._freqEM8000_2, self._phaseEM8000_0)
        MainWindow.setTabOrder(self._phaseEM8000_0, self._phaseEM8000_1)
        MainWindow.setTabOrder(self._phaseEM8000_1, self._phaseEM8000_2)
        MainWindow.setTabOrder(self._phaseEM8000_2, self._ampEM8000_3)
        MainWindow.setTabOrder(self._ampEM8000_3, self._ampEM8000_4)
        MainWindow.setTabOrder(self._ampEM8000_4, self._ampEM8000_5)
        MainWindow.setTabOrder(self._ampEM8000_5, self._freqEM8000_3)
        MainWindow.setTabOrder(self._freqEM8000_3, self._freqEM8000_4)
        MainWindow.setTabOrder(self._freqEM8000_4, self._freqEM8000_5)
        MainWindow.setTabOrder(self._freqEM8000_5, self._phaseEM8000_3)
        MainWindow.setTabOrder(self._phaseEM8000_3, self._phaseEM8000_4)
        MainWindow.setTabOrder(self._phaseEM8000_4, self._phaseEM8000_5)
        MainWindow.setTabOrder(self._phaseEM8000_5, self.tab_6)
        MainWindow.setTabOrder(self.tab_6, self.DP1_SimStates)
        MainWindow.setTabOrder(self.DP1_SimStates, self.DP2_SimStates)
        MainWindow.setTabOrder(self.DP2_SimStates, self.EM8000_wave_spectra)
        MainWindow.setTabOrder(self.EM8000_wave_spectra, self.EM8000_wave_height)
        MainWindow.setTabOrder(self.EM8000_wave_height, self.EM8000_wave_period)
        MainWindow.setTabOrder(self.EM8000_wave_period, self.EM8000_plot_time_range_ship)
        MainWindow.setTabOrder(self.EM8000_plot_time_range_ship, self.DP1_wavespectrum)
        MainWindow.setTabOrder(self.DP1_wavespectrum, self.estimatedDampingPlot)
        MainWindow.setTabOrder(self.estimatedDampingPlot, self.swingAnglesWidget)
        MainWindow.setTabOrder(self.swingAnglesWidget, self.swingVelocityWidget)
        MainWindow.setTabOrder(self.swingVelocityWidget, self.dampingParamPlotWidget)
        MainWindow.setTabOrder(self.dampingParamPlotWidget, self.errorStatePlotWidget)
        MainWindow.setTabOrder(self.errorStatePlotWidget, self.antiSwayPlotRange)
        MainWindow.setTabOrder(self.antiSwayPlotRange, self.btnDeactivateAntiSway)
        MainWindow.setTabOrder(self.btnDeactivateAntiSway, self.btnActivateAntiSway)
        MainWindow.setTabOrder(self.btnActivateAntiSway, self.btnResetAntiSway)
        MainWindow.setTabOrder(self.btnResetAntiSway, self.btnEnableMruEKF)
        MainWindow.setTabOrder(self.btnEnableMruEKF, self.btnDisableMruEKF)
        MainWindow.setTabOrder(self.btnDisableMruEKF, self.btnResetEKF)
        MainWindow.setTabOrder(self.btnResetEKF, self.btnEnableMruCM)
        MainWindow.setTabOrder(self.btnEnableMruCM, self.btnDisableMruCM)
        MainWindow.setTabOrder(self.btnDisableMruCM, self.btnEnableMruWinch)
        MainWindow.setTabOrder(self.btnEnableMruWinch, self.btnDisableMruWinch)
        MainWindow.setTabOrder(self.btnDisableMruWinch, self.EM8000_neutral_btn)
        MainWindow.setTabOrder(self.EM8000_neutral_btn, self.EM8000_engaged_btn)
        MainWindow.setTabOrder(self.EM8000_engaged_btn, self.em1500_eMode)
        MainWindow.setTabOrder(self.em1500_eMode, self.EM1500_engaged_btn)
        MainWindow.setTabOrder(self.EM1500_engaged_btn, self.COMAU_settled_btn)
        MainWindow.setTabOrder(self.COMAU_settled_btn, self.EM1500_settled_btn)
        MainWindow.setTabOrder(self.EM1500_settled_btn, self.COMAU_engaged_fast_btn)
        MainWindow.setTabOrder(self.COMAU_engaged_fast_btn, self.SYSTEM_stop_btn)
        MainWindow.setTabOrder(self.SYSTEM_stop_btn, self.winchOff)
        MainWindow.setTabOrder(self.winchOff, self.winchOn)
        MainWindow.setTabOrder(self.winchOn, self.winchEngagedFast)
        MainWindow.setTabOrder(self.winchEngagedFast, self.show3dView)
        MainWindow.setTabOrder(self.show3dView, self.activeEM8000)
        MainWindow.setTabOrder(self.activeEM8000, self.activeEM1500)
        MainWindow.setTabOrder(self.activeEM1500, self.activeCOMAU)
        MainWindow.setTabOrder(self.activeCOMAU, self.tabSelector)
        MainWindow.setTabOrder(self.tabSelector, self.COMAU_engaged_btn)
        MainWindow.setTabOrder(self.COMAU_engaged_btn, self.winchSettled)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "The Norwegian Motion Laboratory"))
        self.groupBox_33.setTitle(_translate("MainWindow", "Stewart Mode Selector"))
        self._bStopEM8000.setText(_translate("MainWindow", "STOP"))
        self._bResetEM8000.setText(_translate("MainWindow", "RESET"))
        self._eModeEM8000.setItemText(0, _translate("MainWindow", "SETTLED"))
        self._eModeEM8000.setItemText(1, _translate("MainWindow", "NEUTRAL"))
        self._eModeEM8000.setItemText(2, _translate("MainWindow", "WAVE SIMULATOR"))
        self._eModeEM8000.setItemText(3, _translate("MainWindow", "SINE GENERATOR"))
        self._eModeEM8000.setItemText(4, _translate("MainWindow", "REMOTE"))
        self.groupBox_34.setTitle(_translate("MainWindow", "Ship Simulator Settings"))
        self.groupBox_35.setTitle(_translate("MainWindow", "Stewart Command Inspector"))
        self._plotModeEM8000.setItemText(0, _translate("MainWindow", "WAVE SIMULATOR"))
        self._plotModeEM8000.setItemText(1, _translate("MainWindow", "SINE GENERATOR"))
        self._plotModeEM8000.setItemText(2, _translate("MainWindow", "REMOTE"))
        self.groupBox_36.setTitle(_translate("MainWindow", "Sine Generator Settings"))
        self.groupBox_37.setTitle(_translate("MainWindow", "Amp [m]"))
        self.groupBox_38.setTitle(_translate("MainWindow", "Freq [Hz]"))
        self.groupBox_39.setTitle(_translate("MainWindow", "Phase [deg]"))
        self.groupBox_40.setTitle(_translate("MainWindow", "Amp [deg]"))
        self.groupBox_41.setTitle(_translate("MainWindow", "Freq [Hz]"))
        self.groupBox_42.setTitle(_translate("MainWindow", "Phase [deg]"))
        self.groupBox_43.setTitle(_translate("MainWindow", "DOF"))
        self.label_7.setText(_translate("MainWindow", "Roll:"))
        self.label_10.setText(_translate("MainWindow", "Heave:"))
        self.label_11.setText(_translate("MainWindow", "Surge:"))
        self.label_12.setText(_translate("MainWindow", "Pitch:"))
        self.label_19.setText(_translate("MainWindow", "Sway:"))
        self.label_20.setText(_translate("MainWindow", "Yaw:"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_11), _translate("MainWindow", "EM8000"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Stewart Operation"))
        self.em1500_eModeCmd.setItemText(0, _translate("MainWindow", "SETTLED"))
        self.em1500_eModeCmd.setItemText(1, _translate("MainWindow", "NEUTRAL"))
        self.em1500_eModeCmd.setItemText(2, _translate("MainWindow", "SIMULATION"))
        self.em1500_eModeCmd.setItemText(3, _translate("MainWindow", "GENERATOR"))
        self.em1500_eModeCmd.setItemText(4, _translate("MainWindow", "FILE"))
        self.em1500_engage.setText(_translate("MainWindow", "ENGAGE"))
        self.em1500_disengage.setText(_translate("MainWindow", "DISENGAGE"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Sine Generator Settings"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Amp [m]"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Freq [Hz]"))
        self.groupBox_26.setTitle(_translate("MainWindow", "Phase [deg]"))
        self.groupBox_27.setTitle(_translate("MainWindow", "Amp [deg]"))
        self.groupBox_28.setTitle(_translate("MainWindow", "Freq [Hz]"))
        self.groupBox_29.setTitle(_translate("MainWindow", "Phase [deg]"))
        self.groupBox_31.setTitle(_translate("MainWindow", "DOF"))
        self.label_5.setText(_translate("MainWindow", "Roll:"))
        self.label_3.setText(_translate("MainWindow", "Heave:"))
        self.label.setText(_translate("MainWindow", "Surge:"))
        self.label_6.setText(_translate("MainWindow", "Pitch:"))
        self.label_2.setText(_translate("MainWindow", "Sway:"))
        self.label_4.setText(_translate("MainWindow", "Yaw:"))
        self.groupBox_32.setTitle(_translate("MainWindow", "Stewart Command Inspector"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Actuator Stroke Utilization"))
        self.label_41.setText(_translate("MainWindow", "5"))
        self.label_42.setText(_translate("MainWindow", "6"))
        self.label_43.setText(_translate("MainWindow", "4"))
        self.label_44.setText(_translate("MainWindow", "3"))
        self.label_45.setText(_translate("MainWindow", "2"))
        self.label_46.setText(_translate("MainWindow", "1"))
        self.groupBox.setTitle(_translate("MainWindow", "Stewart Status Feedback"))
        self.label_13.setText(_translate("MainWindow", "Operation State:"))
        self.label_14.setText(_translate("MainWindow", "System Status:"))
        self.label_15.setText(_translate("MainWindow", "Operation Mode:"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_8), _translate("MainWindow", "EM1500"))
        self.EM8000_settled_btn.setText(_translate("MainWindow", "Settled"))
        self.EM8000_neutral_btn.setText(_translate("MainWindow", "Neutral"))
        self.EM8000_engaged_btn.setText(_translate("MainWindow", "Engaged"))
        self.EM1500_settled_btn.setText(_translate("MainWindow", "Settled"))
        self.EM1500_neutral_btn.setText(_translate("MainWindow", "Neutral"))
        self.EM1500_engaged_btn.setText(_translate("MainWindow", "Engaged"))
        self.COMAU_settled_btn.setText(_translate("MainWindow", "Settled"))
        self.COMAU_engaged_fast_btn.setText(_translate("MainWindow", "Engaged - Fast"))
        self.COMAU_engaged_btn.setText(_translate("MainWindow", "Engaged"))
        self.label_8.setText(_translate("MainWindow", "Motion-Lab Control"))
        self.groupBox_EM8000.setTitle(_translate("MainWindow", "E-Motion 8000"))
        self.groupBox_EM1500.setTitle(_translate("MainWindow", "E-Motion 1500"))
        self.groupBox_EM1500_2.setTitle(_translate("MainWindow", "COMAU Robot"))
        self.groupBox_EM1500_3.setTitle(_translate("MainWindow", "System"))
        self.SYSTEM_settled_btn.setText(_translate("MainWindow", "Full System Settled"))
        self.SYSTEM_stop_btn.setText(_translate("MainWindow", "STOP"))
        self.groupBox_8.setTitle(_translate("MainWindow", "EM8000 Actuator Position"))
        self.label_21.setText(_translate("MainWindow", "5"))
        self.label_47.setText(_translate("MainWindow", "6"))
        self.label_48.setText(_translate("MainWindow", "4"))
        self.label_49.setText(_translate("MainWindow", "3"))
        self.label_50.setText(_translate("MainWindow", "2"))
        self.label_51.setText(_translate("MainWindow", "1"))
        self.groupBox_10.setTitle(_translate("MainWindow", "COMAU Joint Position"))
        self.label_52.setText(_translate("MainWindow", "5"))
        self.label_53.setText(_translate("MainWindow", "6"))
        self.label_54.setText(_translate("MainWindow", "4"))
        self.label_55.setText(_translate("MainWindow", "3"))
        self.label_56.setText(_translate("MainWindow", "2"))
        self.label_57.setText(_translate("MainWindow", "1"))
        self.groupBox_EM1500_5.setTitle(_translate("MainWindow", "Winch"))
        self.winchOff.setText(_translate("MainWindow", "OFF"))
        self.winchOn.setText(_translate("MainWindow", "ON"))
        self.winchEngagedFast.setText(_translate("MainWindow", "Engaged - Fast"))
        self.winchSettled.setText(_translate("MainWindow", "Settled"))
        self.winchEngaged.setText(_translate("MainWindow", "Engaged"))
        self.show3dView.setText(_translate("MainWindow", "Show 3D View"))
        self.groupBox_EM1500_4.setTitle(_translate("MainWindow", "Status"))
        self.activeEM8000.setText(_translate("MainWindow", "EM8000"))
        self.activeEM1500.setText(_translate("MainWindow", "EM1500"))
        self.activeCOMAU.setText(_translate("MainWindow", "COMAU"))
        self.activeWINCH.setText(_translate("MainWindow", "WINCH"))
        self.activeLEICA.setText(_translate("MainWindow", "LEICA"))
        self.activeQTM.setText(_translate("MainWindow", "QTM"))
        self.activeMRU1.setText(_translate("MainWindow", "MRU1"))
        self.activeMRU2.setText(_translate("MainWindow", "MRU2"))
        self.activeXBOX.setText(_translate("MainWindow", "XBOX"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_interface), _translate("MainWindow", "COMAU"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab), _translate("MainWindow", "WINCH"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_2), _translate("MainWindow", "MRU 1"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_3), _translate("MainWindow", "MRU 2"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_12), _translate("MainWindow", "Wave Simulator"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_9), _translate("MainWindow", "Data Logger"))
        self.label_58.setText(_translate("MainWindow", "Real-Time Dyanamic Positioning (DP) Simulator - 6DOF"))
        self.tab_6.setTabText(self.tab_6.indexOf(self.widget_2), _translate("MainWindow", "EM 8000"))
        self.tab_6.setTabText(self.tab_6.indexOf(self.tab_7), _translate("MainWindow", "EM 1500"))
        self.groupBox_23.setTitle(_translate("MainWindow", "Wave Spectrum Settings"))
        self.label_149.setText(_translate("MainWindow", "[s]"))
        self.label_151.setText(_translate("MainWindow", "[m]"))
        self.label_152.setText(_translate("MainWindow", "Significant Wave Height :"))
        self.label_159.setText(_translate("MainWindow", "Wave Time Period :"))
        self.label_160.setText(_translate("MainWindow", "Ocean-Wave Spectra :"))
        self.EM8000_wave_spectra.setCurrentText(_translate("MainWindow", "JONSWAP"))
        self.EM8000_wave_spectra.setItemText(0, _translate("MainWindow", "JONSWAP"))
        self.EM8000_wave_spectra.setItemText(1, _translate("MainWindow", "PMS"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Plot options"))
        self.label_109.setText(_translate("MainWindow", "Time axis range:"))
        self.EM8000_plot_time_range_ship.setCurrentText(_translate("MainWindow", "20"))
        self.EM8000_plot_time_range_ship.setItemText(0, _translate("MainWindow", "10"))
        self.EM8000_plot_time_range_ship.setItemText(1, _translate("MainWindow", "20"))
        self.EM8000_plot_time_range_ship.setItemText(2, _translate("MainWindow", "30"))
        self.EM8000_plot_time_range_ship.setItemText(3, _translate("MainWindow", "40"))
        self.EM8000_plot_time_range_ship.setItemText(4, _translate("MainWindow", "50"))
        self.EM8000_plot_time_range_ship.setItemText(5, _translate("MainWindow", "60"))
        self.label_110.setText(_translate("MainWindow", "[s]"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_5), _translate("MainWindow", "DP Simulator"))
        self.label_34.setText(_translate("MainWindow", "Controller and Anti-Swing System"))
        self.estimatedDampingPlot.setTabText(self.estimatedDampingPlot.indexOf(self.widget_3), _translate("MainWindow", "Pendulum States"))
        self.estimatedDampingPlot.setTabText(self.estimatedDampingPlot.indexOf(self.DampingParamter), _translate("MainWindow", "Damping Parameter"))
        self.estimatedDampingPlot.setTabText(self.estimatedDampingPlot.indexOf(self.tab_10), _translate("MainWindow", "Error States"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Plot options"))
        self.label_98.setText(_translate("MainWindow", "Time axis range:"))
        self.antiSwayPlotRange.setCurrentText(_translate("MainWindow", "10"))
        self.antiSwayPlotRange.setItemText(0, _translate("MainWindow", "10"))
        self.antiSwayPlotRange.setItemText(1, _translate("MainWindow", "20"))
        self.antiSwayPlotRange.setItemText(2, _translate("MainWindow", "30"))
        self.antiSwayPlotRange.setItemText(3, _translate("MainWindow", "40"))
        self.antiSwayPlotRange.setItemText(4, _translate("MainWindow", "50"))
        self.antiSwayPlotRange.setItemText(5, _translate("MainWindow", "60"))
        self.label_99.setText(_translate("MainWindow", "[s]"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Anti-Swing System"))
        self.btnDeactivateAntiSway.setText(_translate("MainWindow", "Deactivate"))
        self.btnActivateAntiSway.setText(_translate("MainWindow", "Activate"))
        self.btnResetAntiSway.setText(_translate("MainWindow", "Reset"))
        self.groupBox_24.setTitle(_translate("MainWindow", "Pendel Estimator - EKF"))
        self.btnEnableMruEKF.setText(_translate("MainWindow", "MRU Feedback"))
        self.btnDisableMruEKF.setText(_translate("MainWindow", "Stewart Feedback"))
        self.btnResetEKF.setText(_translate("MainWindow", "Reset"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Control Mapping"))
        self.btnEnableMruCM.setText(_translate("MainWindow", "MRU Feedback"))
        self.btnDisableMruCM.setText(_translate("MainWindow", "Stewart Feedback"))
        self.groupBox_25.setTitle(_translate("MainWindow", "Winch Controller"))
        self.btnEnableMruWinch.setText(_translate("MainWindow", "MRU Feedback"))
        self.btnDisableMruWinch.setText(_translate("MainWindow", "Stewart Feedback"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_4), _translate("MainWindow", "Anti-Swing System"))
        self.menu_open_file.setText(_translate("MainWindow", "Open File"))
        self.menu_open_file.setStatusTip(_translate("MainWindow", "Open File"))
        self.menu_open_file.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.menu_save_file.setText(_translate("MainWindow", "Save File"))
        self.menu_save_file.setStatusTip(_translate("MainWindow", "Save File"))
        self.menu_save_file.setShortcut(_translate("MainWindow", "Ctrl+S"))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

