# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1309, 1030)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabSelector = QtWidgets.QTabWidget(self.centralwidget)
        self.tabSelector.setGeometry(QtCore.QRect(10, 0, 1285, 861))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSelector.sizePolicy().hasHeightForWidth())
        self.tabSelector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabSelector.setFont(font)
        self.tabSelector.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tabSelector.setStyleSheet("")
        self.tabSelector.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabSelector.setObjectName("tabSelector")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 230, 351, 291))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_6.setGeometry(QtCore.QRect(80, 30, 81, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.em8000_amp_0 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.em8000_amp_0.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em8000_amp_0.setObjectName("em8000_amp_0")
        self.em8000_amp_1 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.em8000_amp_1.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em8000_amp_1.setObjectName("em8000_amp_1")
        self.em8000_amp_2 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.em8000_amp_2.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em8000_amp_2.setObjectName("em8000_amp_2")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_11.setGeometry(QtCore.QRect(170, 30, 81, 121))
        self.groupBox_11.setObjectName("groupBox_11")
        self.em8000_freq_0 = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.em8000_freq_0.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em8000_freq_0.setObjectName("em8000_freq_0")
        self.em8000_freq_1 = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.em8000_freq_1.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em8000_freq_1.setObjectName("em8000_freq_1")
        self.em8000_freq_2 = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.em8000_freq_2.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em8000_freq_2.setObjectName("em8000_freq_2")
        self.groupBox_30 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_30.setGeometry(QtCore.QRect(260, 30, 81, 121))
        self.groupBox_30.setObjectName("groupBox_30")
        self.em8000_phase_0 = QtWidgets.QDoubleSpinBox(self.groupBox_30)
        self.em8000_phase_0.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em8000_phase_0.setObjectName("em8000_phase_0")
        self.em8000_phase_1 = QtWidgets.QDoubleSpinBox(self.groupBox_30)
        self.em8000_phase_1.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em8000_phase_1.setObjectName("em8000_phase_1")
        self.em8000_phase_2 = QtWidgets.QDoubleSpinBox(self.groupBox_30)
        self.em8000_phase_2.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em8000_phase_2.setObjectName("em8000_phase_2")
        self.groupBox_33 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_33.setGeometry(QtCore.QRect(80, 160, 81, 121))
        self.groupBox_33.setObjectName("groupBox_33")
        self.em8000_amp_3 = QtWidgets.QDoubleSpinBox(self.groupBox_33)
        self.em8000_amp_3.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em8000_amp_3.setObjectName("em8000_amp_3")
        self.em8000_amp_4 = QtWidgets.QDoubleSpinBox(self.groupBox_33)
        self.em8000_amp_4.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em8000_amp_4.setObjectName("em8000_amp_4")
        self.em8000_amp_5 = QtWidgets.QDoubleSpinBox(self.groupBox_33)
        self.em8000_amp_5.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em8000_amp_5.setObjectName("em8000_amp_5")
        self.groupBox_34 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_34.setGeometry(QtCore.QRect(170, 160, 81, 121))
        self.groupBox_34.setObjectName("groupBox_34")
        self.em8000_freq_3 = QtWidgets.QDoubleSpinBox(self.groupBox_34)
        self.em8000_freq_3.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em8000_freq_3.setObjectName("em8000_freq_3")
        self.em8000_freq_4 = QtWidgets.QDoubleSpinBox(self.groupBox_34)
        self.em8000_freq_4.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em8000_freq_4.setObjectName("em8000_freq_4")
        self.em8000_freq_5 = QtWidgets.QDoubleSpinBox(self.groupBox_34)
        self.em8000_freq_5.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em8000_freq_5.setObjectName("em8000_freq_5")
        self.groupBox_35 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_35.setGeometry(QtCore.QRect(260, 160, 81, 121))
        self.groupBox_35.setObjectName("groupBox_35")
        self.em8000_phase_3 = QtWidgets.QDoubleSpinBox(self.groupBox_35)
        self.em8000_phase_3.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em8000_phase_3.setObjectName("em8000_phase_3")
        self.em8000_phase_4 = QtWidgets.QDoubleSpinBox(self.groupBox_35)
        self.em8000_phase_4.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em8000_phase_4.setObjectName("em8000_phase_4")
        self.em8000_phase_5 = QtWidgets.QDoubleSpinBox(self.groupBox_35)
        self.em8000_phase_5.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em8000_phase_5.setObjectName("em8000_phase_5")
        self.groupBox_36 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_36.setGeometry(QtCore.QRect(10, 30, 61, 251))
        self.groupBox_36.setObjectName("groupBox_36")
        self.label_7 = QtWidgets.QLabel(self.groupBox_36)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 51, 16))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_36)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 51, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_36)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_36)
        self.label_11.setGeometry(QtCore.QRect(10, 190, 51, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_36)
        self.label_12.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.groupBox_36)
        self.label_16.setGeometry(QtCore.QRect(10, 220, 51, 16))
        self.label_16.setObjectName("label_16")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 110, 351, 121))
        self.groupBox_12.setObjectName("groupBox_12")
        self.em8000_eOpMode = QtWidgets.QLineEdit(self.groupBox_12)
        self.em8000_eOpMode.setGeometry(QtCore.QRect(180, 85, 153, 22))
        self.em8000_eOpMode.setReadOnly(True)
        self.em8000_eOpMode.setObjectName("em8000_eOpMode")
        self.em8000_eStatus = QtWidgets.QLineEdit(self.groupBox_12)
        self.em8000_eStatus.setGeometry(QtCore.QRect(180, 55, 153, 22))
        self.em8000_eStatus.setReadOnly(True)
        self.em8000_eStatus.setObjectName("em8000_eStatus")
        self.label_17 = QtWidgets.QLabel(self.groupBox_12)
        self.label_17.setGeometry(QtCore.QRect(19, 26, 141, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_12)
        self.label_18.setGeometry(QtCore.QRect(19, 56, 141, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_12)
        self.label_19.setGeometry(QtCore.QRect(19, 86, 141, 16))
        self.label_19.setObjectName("label_19")
        self.em8000_eState = QtWidgets.QLineEdit(self.groupBox_12)
        self.em8000_eState.setGeometry(QtCore.QRect(180, 25, 153, 22))
        self.em8000_eState.setReadOnly(True)
        self.em8000_eState.setObjectName("em8000_eState")
        self.groupBox_37 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_37.setGeometry(QtCore.QRect(370, 10, 901, 811))
        self.groupBox_37.setObjectName("groupBox_37")
        self.em8000_plot = GraphicsLayoutWidget(self.groupBox_37)
        self.em8000_plot.setGeometry(QtCore.QRect(10, 30, 881, 771))
        self.em8000_plot.setObjectName("em8000_plot")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 10, 351, 101))
        self.groupBox_13.setObjectName("groupBox_13")
        self.em8000_eModeCmd = QtWidgets.QComboBox(self.groupBox_13)
        self.em8000_eModeCmd.setGeometry(QtCore.QRect(13, 30, 153, 22))
        self.em8000_eModeCmd.setObjectName("em8000_eModeCmd")
        self.em8000_eModeCmd.addItem("")
        self.em8000_eModeCmd.addItem("")
        self.em8000_eModeCmd.addItem("")
        self.em8000_eModeCmd.addItem("")
        self.em8000_eModeCmd.addItem("")
        self.em8000_engage = QtWidgets.QPushButton(self.groupBox_13)
        self.em8000_engage.setGeometry(QtCore.QRect(12, 65, 155, 23))
        self.em8000_engage.setObjectName("em8000_engage")
        self.em8000_disengage = QtWidgets.QPushButton(self.groupBox_13)
        self.em8000_disengage.setGeometry(QtCore.QRect(180, 65, 155, 23))
        self.em8000_disengage.setObjectName("em8000_disengage")
        self.em8000_eMode = QtWidgets.QLineEdit(self.groupBox_13)
        self.em8000_eMode.setGeometry(QtCore.QRect(180, 30, 153, 22))
        self.em8000_eMode.setReadOnly(True)
        self.em8000_eMode.setObjectName("em8000_eMode")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 520, 351, 301))
        self.groupBox_14.setObjectName("groupBox_14")
        self.em8000_cylinder_1 = QtWidgets.QProgressBar(self.groupBox_14)
        self.em8000_cylinder_1.setGeometry(QtCore.QRect(21, 31, 38, 240))
        self.em8000_cylinder_1.setMinimum(-100)
        self.em8000_cylinder_1.setProperty("value", 0)
        self.em8000_cylinder_1.setOrientation(QtCore.Qt.Vertical)
        self.em8000_cylinder_1.setInvertedAppearance(False)
        self.em8000_cylinder_1.setObjectName("em8000_cylinder_1")
        self.label_59 = QtWidgets.QLabel(self.groupBox_14)
        self.label_59.setGeometry(QtCore.QRect(239, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.groupBox_14)
        self.label_60.setGeometry(QtCore.QRect(293, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.groupBox_14)
        self.label_61.setGeometry(QtCore.QRect(188, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.groupBox_14)
        self.label_62.setGeometry(QtCore.QRect(132, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.groupBox_14)
        self.label_63.setGeometry(QtCore.QRect(82, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.groupBox_14)
        self.label_64.setGeometry(QtCore.QRect(28, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.em8000_cylinder_2 = QtWidgets.QProgressBar(self.groupBox_14)
        self.em8000_cylinder_2.setGeometry(QtCore.QRect(74, 31, 38, 240))
        self.em8000_cylinder_2.setMinimum(-100)
        self.em8000_cylinder_2.setProperty("value", 0)
        self.em8000_cylinder_2.setOrientation(QtCore.Qt.Vertical)
        self.em8000_cylinder_2.setInvertedAppearance(False)
        self.em8000_cylinder_2.setObjectName("em8000_cylinder_2")
        self.em8000_cylinder_3 = QtWidgets.QProgressBar(self.groupBox_14)
        self.em8000_cylinder_3.setGeometry(QtCore.QRect(126, 31, 38, 240))
        self.em8000_cylinder_3.setMinimum(-100)
        self.em8000_cylinder_3.setProperty("value", 0)
        self.em8000_cylinder_3.setOrientation(QtCore.Qt.Vertical)
        self.em8000_cylinder_3.setInvertedAppearance(False)
        self.em8000_cylinder_3.setObjectName("em8000_cylinder_3")
        self.em8000_cylinder_4 = QtWidgets.QProgressBar(self.groupBox_14)
        self.em8000_cylinder_4.setGeometry(QtCore.QRect(179, 31, 38, 240))
        self.em8000_cylinder_4.setMinimum(-100)
        self.em8000_cylinder_4.setProperty("value", 0)
        self.em8000_cylinder_4.setOrientation(QtCore.Qt.Vertical)
        self.em8000_cylinder_4.setInvertedAppearance(False)
        self.em8000_cylinder_4.setObjectName("em8000_cylinder_4")
        self.em8000_cylinder_5 = QtWidgets.QProgressBar(self.groupBox_14)
        self.em8000_cylinder_5.setGeometry(QtCore.QRect(231, 31, 38, 240))
        self.em8000_cylinder_5.setMinimum(-100)
        self.em8000_cylinder_5.setProperty("value", 0)
        self.em8000_cylinder_5.setOrientation(QtCore.Qt.Vertical)
        self.em8000_cylinder_5.setInvertedAppearance(False)
        self.em8000_cylinder_5.setObjectName("em8000_cylinder_5")
        self.em8000_cylinder_6 = QtWidgets.QProgressBar(self.groupBox_14)
        self.em8000_cylinder_6.setGeometry(QtCore.QRect(284, 31, 38, 240))
        self.em8000_cylinder_6.setMinimum(-100)
        self.em8000_cylinder_6.setProperty("value", 0)
        self.em8000_cylinder_6.setOrientation(QtCore.Qt.Vertical)
        self.em8000_cylinder_6.setInvertedAppearance(False)
        self.em8000_cylinder_6.setObjectName("em8000_cylinder_6")
        self.tabSelector.addTab(self.tab_11, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 351, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.em1500_eModeCmd = QtWidgets.QComboBox(self.groupBox_2)
        self.em1500_eModeCmd.setGeometry(QtCore.QRect(13, 30, 153, 22))
        self.em1500_eModeCmd.setObjectName("em1500_eModeCmd")
        self.em1500_eModeCmd.addItem("")
        self.em1500_eModeCmd.addItem("")
        self.em1500_eModeCmd.addItem("")
        self.em1500_eModeCmd.addItem("")
        self.em1500_eModeCmd.addItem("")
        self.em1500_engage = QtWidgets.QPushButton(self.groupBox_2)
        self.em1500_engage.setGeometry(QtCore.QRect(12, 65, 155, 23))
        self.em1500_engage.setObjectName("em1500_engage")
        self.em1500_disengage = QtWidgets.QPushButton(self.groupBox_2)
        self.em1500_disengage.setGeometry(QtCore.QRect(180, 65, 155, 23))
        self.em1500_disengage.setObjectName("em1500_disengage")
        self.em1500_eMode = QtWidgets.QLineEdit(self.groupBox_2)
        self.em1500_eMode.setGeometry(QtCore.QRect(180, 30, 153, 22))
        self.em1500_eMode.setReadOnly(True)
        self.em1500_eMode.setObjectName("em1500_eMode")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 230, 351, 291))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(80, 30, 81, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.em1500_amp_1 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.em1500_amp_1.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em1500_amp_1.setObjectName("em1500_amp_1")
        self.em1500_amp_2 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.em1500_amp_2.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em1500_amp_2.setObjectName("em1500_amp_2")
        self.em1500_amp_0 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.em1500_amp_0.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em1500_amp_0.setObjectName("em1500_amp_0")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_9.setGeometry(QtCore.QRect(170, 30, 81, 121))
        self.groupBox_9.setObjectName("groupBox_9")
        self.em1500_freq_1 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.em1500_freq_1.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em1500_freq_1.setObjectName("em1500_freq_1")
        self.em1500_freq_2 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.em1500_freq_2.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em1500_freq_2.setObjectName("em1500_freq_2")
        self.em1500_freq_0 = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.em1500_freq_0.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em1500_freq_0.setObjectName("em1500_freq_0")
        self.groupBox_26 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_26.setGeometry(QtCore.QRect(260, 30, 81, 121))
        self.groupBox_26.setObjectName("groupBox_26")
        self.em1500_phase_1 = QtWidgets.QDoubleSpinBox(self.groupBox_26)
        self.em1500_phase_1.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em1500_phase_1.setObjectName("em1500_phase_1")
        self.em1500_phase_2 = QtWidgets.QDoubleSpinBox(self.groupBox_26)
        self.em1500_phase_2.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em1500_phase_2.setObjectName("em1500_phase_2")
        self.em1500_phase_0 = QtWidgets.QDoubleSpinBox(self.groupBox_26)
        self.em1500_phase_0.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em1500_phase_0.setObjectName("em1500_phase_0")
        self.groupBox_27 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_27.setGeometry(QtCore.QRect(80, 160, 81, 121))
        self.groupBox_27.setObjectName("groupBox_27")
        self.em1500_amp_4 = QtWidgets.QDoubleSpinBox(self.groupBox_27)
        self.em1500_amp_4.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em1500_amp_4.setObjectName("em1500_amp_4")
        self.em1500_amp_5 = QtWidgets.QDoubleSpinBox(self.groupBox_27)
        self.em1500_amp_5.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em1500_amp_5.setObjectName("em1500_amp_5")
        self.em1500_amp_3 = QtWidgets.QDoubleSpinBox(self.groupBox_27)
        self.em1500_amp_3.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em1500_amp_3.setObjectName("em1500_amp_3")
        self.groupBox_28 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_28.setGeometry(QtCore.QRect(170, 160, 81, 121))
        self.groupBox_28.setObjectName("groupBox_28")
        self.em1500_freq_4 = QtWidgets.QDoubleSpinBox(self.groupBox_28)
        self.em1500_freq_4.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em1500_freq_4.setObjectName("em1500_freq_4")
        self.em1500_freq_5 = QtWidgets.QDoubleSpinBox(self.groupBox_28)
        self.em1500_freq_5.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em1500_freq_5.setObjectName("em1500_freq_5")
        self.em1500_freq_3 = QtWidgets.QDoubleSpinBox(self.groupBox_28)
        self.em1500_freq_3.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em1500_freq_3.setObjectName("em1500_freq_3")
        self.groupBox_29 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_29.setGeometry(QtCore.QRect(260, 160, 81, 121))
        self.groupBox_29.setObjectName("groupBox_29")
        self.em1500_phase_4 = QtWidgets.QDoubleSpinBox(self.groupBox_29)
        self.em1500_phase_4.setGeometry(QtCore.QRect(10, 60, 62, 22))
        self.em1500_phase_4.setObjectName("em1500_phase_4")
        self.em1500_phase_5 = QtWidgets.QDoubleSpinBox(self.groupBox_29)
        self.em1500_phase_5.setGeometry(QtCore.QRect(10, 90, 62, 22))
        self.em1500_phase_5.setObjectName("em1500_phase_5")
        self.em1500_phase_3 = QtWidgets.QDoubleSpinBox(self.groupBox_29)
        self.em1500_phase_3.setGeometry(QtCore.QRect(10, 30, 62, 22))
        self.em1500_phase_3.setObjectName("em1500_phase_3")
        self.groupBox_31 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_31.setGeometry(QtCore.QRect(10, 30, 61, 251))
        self.groupBox_31.setObjectName("groupBox_31")
        self.label_5 = QtWidgets.QLabel(self.groupBox_31)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 51, 16))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_31)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 51, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.groupBox_31)
        self.label.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.groupBox_31)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 51, 16))
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox_31)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_31)
        self.label_4.setGeometry(QtCore.QRect(10, 220, 51, 16))
        self.label_4.setObjectName("label_4")
        self.groupBox_32 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_32.setGeometry(QtCore.QRect(370, 10, 901, 811))
        self.groupBox_32.setObjectName("groupBox_32")
        self.em1500_plot = GraphicsLayoutWidget(self.groupBox_32)
        self.em1500_plot.setGeometry(QtCore.QRect(10, 30, 881, 771))
        self.em1500_plot.setObjectName("em1500_plot")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 520, 351, 301))
        self.groupBox_7.setObjectName("groupBox_7")
        self.em1500_cylinder_1 = QtWidgets.QProgressBar(self.groupBox_7)
        self.em1500_cylinder_1.setGeometry(QtCore.QRect(21, 31, 38, 240))
        self.em1500_cylinder_1.setMinimum(-100)
        self.em1500_cylinder_1.setProperty("value", 0)
        self.em1500_cylinder_1.setOrientation(QtCore.Qt.Vertical)
        self.em1500_cylinder_1.setInvertedAppearance(False)
        self.em1500_cylinder_1.setObjectName("em1500_cylinder_1")
        self.label_41 = QtWidgets.QLabel(self.groupBox_7)
        self.label_41.setGeometry(QtCore.QRect(239, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_7)
        self.label_42.setGeometry(QtCore.QRect(293, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_7)
        self.label_43.setGeometry(QtCore.QRect(188, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.groupBox_7)
        self.label_44.setGeometry(QtCore.QRect(132, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_7)
        self.label_45.setGeometry(QtCore.QRect(82, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_7)
        self.label_46.setGeometry(QtCore.QRect(28, 275, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.em1500_cylinder_2 = QtWidgets.QProgressBar(self.groupBox_7)
        self.em1500_cylinder_2.setGeometry(QtCore.QRect(74, 31, 38, 240))
        self.em1500_cylinder_2.setMinimum(-100)
        self.em1500_cylinder_2.setProperty("value", 0)
        self.em1500_cylinder_2.setOrientation(QtCore.Qt.Vertical)
        self.em1500_cylinder_2.setInvertedAppearance(False)
        self.em1500_cylinder_2.setObjectName("em1500_cylinder_2")
        self.em1500_cylinder_3 = QtWidgets.QProgressBar(self.groupBox_7)
        self.em1500_cylinder_3.setGeometry(QtCore.QRect(126, 31, 38, 240))
        self.em1500_cylinder_3.setMinimum(-100)
        self.em1500_cylinder_3.setProperty("value", 0)
        self.em1500_cylinder_3.setOrientation(QtCore.Qt.Vertical)
        self.em1500_cylinder_3.setInvertedAppearance(False)
        self.em1500_cylinder_3.setObjectName("em1500_cylinder_3")
        self.em1500_cylinder_4 = QtWidgets.QProgressBar(self.groupBox_7)
        self.em1500_cylinder_4.setGeometry(QtCore.QRect(179, 31, 38, 240))
        self.em1500_cylinder_4.setMinimum(-100)
        self.em1500_cylinder_4.setProperty("value", 0)
        self.em1500_cylinder_4.setOrientation(QtCore.Qt.Vertical)
        self.em1500_cylinder_4.setInvertedAppearance(False)
        self.em1500_cylinder_4.setObjectName("em1500_cylinder_4")
        self.em1500_cylinder_5 = QtWidgets.QProgressBar(self.groupBox_7)
        self.em1500_cylinder_5.setGeometry(QtCore.QRect(231, 31, 38, 240))
        self.em1500_cylinder_5.setMinimum(-100)
        self.em1500_cylinder_5.setProperty("value", 0)
        self.em1500_cylinder_5.setOrientation(QtCore.Qt.Vertical)
        self.em1500_cylinder_5.setInvertedAppearance(False)
        self.em1500_cylinder_5.setObjectName("em1500_cylinder_5")
        self.em1500_cylinder_6 = QtWidgets.QProgressBar(self.groupBox_7)
        self.em1500_cylinder_6.setGeometry(QtCore.QRect(284, 31, 38, 240))
        self.em1500_cylinder_6.setMinimum(-100)
        self.em1500_cylinder_6.setProperty("value", 0)
        self.em1500_cylinder_6.setOrientation(QtCore.Qt.Vertical)
        self.em1500_cylinder_6.setInvertedAppearance(False)
        self.em1500_cylinder_6.setObjectName("em1500_cylinder_6")
        self.groupBox = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 351, 121))
        self.groupBox.setObjectName("groupBox")
        self.em1500_eOpMode = QtWidgets.QLineEdit(self.groupBox)
        self.em1500_eOpMode.setGeometry(QtCore.QRect(180, 85, 153, 22))
        self.em1500_eOpMode.setReadOnly(True)
        self.em1500_eOpMode.setObjectName("em1500_eOpMode")
        self.em1500_eStatus = QtWidgets.QLineEdit(self.groupBox)
        self.em1500_eStatus.setGeometry(QtCore.QRect(180, 55, 153, 22))
        self.em1500_eStatus.setReadOnly(True)
        self.em1500_eStatus.setObjectName("em1500_eStatus")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(19, 26, 141, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(19, 56, 141, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(19, 86, 141, 16))
        self.label_15.setObjectName("label_15")
        self.em1500_eState = QtWidgets.QLineEdit(self.groupBox)
        self.em1500_eState.setGeometry(QtCore.QRect(180, 25, 153, 22))
        self.em1500_eState.setReadOnly(True)
        self.em1500_eState.setObjectName("em1500_eState")
        self.tabSelector.addTab(self.tab_8, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.groupBox_40 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_40.setGeometry(QtCore.QRect(370, 10, 901, 811))
        self.groupBox_40.setObjectName("groupBox_40")
        self.waveSpectrum_plot = GraphicsLayoutWidget(self.groupBox_40)
        self.waveSpectrum_plot.setGeometry(QtCore.QRect(10, 30, 881, 771))
        self.waveSpectrum_plot.setObjectName("waveSpectrum_plot")
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_23.setGeometry(QtCore.QRect(10, 10, 351, 171))
        self.groupBox_23.setObjectName("groupBox_23")
        self.label_149 = QtWidgets.QLabel(self.groupBox_23)
        self.label_149.setGeometry(QtCore.QRect(310, 51, 31, 20))
        self.label_149.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_149.setObjectName("label_149")
        self.label_151 = QtWidgets.QLabel(self.groupBox_23)
        self.label_151.setGeometry(QtCore.QRect(310, 20, 31, 20))
        self.label_151.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_151.setObjectName("label_151")
        self.label_152 = QtWidgets.QLabel(self.groupBox_23)
        self.label_152.setGeometry(QtCore.QRect(11, 21, 181, 20))
        self.label_152.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_152.setObjectName("label_152")
        self.label_159 = QtWidgets.QLabel(self.groupBox_23)
        self.label_159.setGeometry(QtCore.QRect(11, 51, 151, 20))
        self.label_159.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_159.setObjectName("label_159")
        self.label_160 = QtWidgets.QLabel(self.groupBox_23)
        self.label_160.setGeometry(QtCore.QRect(11, 95, 141, 20))
        self.label_160.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_160.setObjectName("label_160")
        self.spectrumType = QtWidgets.QComboBox(self.groupBox_23)
        self.spectrumType.setGeometry(QtCore.QRect(141, 95, 151, 22))
        self.spectrumType.setObjectName("spectrumType")
        self.spectrumType.addItem("")
        self.spectrumType.addItem("")
        self.Hs = QtWidgets.QDoubleSpinBox(self.groupBox_23)
        self.Hs.setGeometry(QtCore.QRect(210, 20, 81, 22))
        self.Hs.setMinimum(0.5)
        self.Hs.setMaximum(2.5)
        self.Hs.setSingleStep(0.2)
        self.Hs.setProperty("value", 1.0)
        self.Hs.setObjectName("Hs")
        self.Tp = QtWidgets.QDoubleSpinBox(self.groupBox_23)
        self.Tp.setGeometry(QtCore.QRect(210, 51, 81, 22))
        self.Tp.setMinimum(5.0)
        self.Tp.setMaximum(25.0)
        self.Tp.setSingleStep(1.0)
        self.Tp.setProperty("value", 12.0)
        self.Tp.setObjectName("Tp")
        self.bResetDofScaling = QtWidgets.QPushButton(self.groupBox_23)
        self.bResetDofScaling.setGeometry(QtCore.QRect(141, 134, 151, 23))
        self.bResetDofScaling.setObjectName("bResetDofScaling")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 500, 351, 321))
        self.groupBox_8.setObjectName("groupBox_8")
        self.em1500_dof_scale_0 = QtWidgets.QProgressBar(self.groupBox_8)
        self.em1500_dof_scale_0.setGeometry(QtCore.QRect(21, 36, 38, 240))
        self.em1500_dof_scale_0.setMinimum(0)
        self.em1500_dof_scale_0.setProperty("value", 100)
        self.em1500_dof_scale_0.setOrientation(QtCore.Qt.Vertical)
        self.em1500_dof_scale_0.setInvertedAppearance(False)
        self.em1500_dof_scale_0.setObjectName("em1500_dof_scale_0")
        self.label_47 = QtWidgets.QLabel(self.groupBox_8)
        self.label_47.setGeometry(QtCore.QRect(223, 280, 50, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_49 = QtWidgets.QLabel(self.groupBox_8)
        self.label_49.setGeometry(QtCore.QRect(188, 280, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.groupBox_8)
        self.label_50.setGeometry(QtCore.QRect(132, 280, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.groupBox_8)
        self.label_51.setGeometry(QtCore.QRect(82, 280, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.groupBox_8)
        self.label_52.setGeometry(QtCore.QRect(28, 280, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.em1500_dof_scale_1 = QtWidgets.QProgressBar(self.groupBox_8)
        self.em1500_dof_scale_1.setGeometry(QtCore.QRect(74, 36, 38, 240))
        self.em1500_dof_scale_1.setMinimum(0)
        self.em1500_dof_scale_1.setProperty("value", 100)
        self.em1500_dof_scale_1.setOrientation(QtCore.Qt.Vertical)
        self.em1500_dof_scale_1.setInvertedAppearance(False)
        self.em1500_dof_scale_1.setObjectName("em1500_dof_scale_1")
        self.em1500_dof_scale_2 = QtWidgets.QProgressBar(self.groupBox_8)
        self.em1500_dof_scale_2.setGeometry(QtCore.QRect(126, 36, 38, 240))
        self.em1500_dof_scale_2.setMinimum(0)
        self.em1500_dof_scale_2.setProperty("value", 100)
        self.em1500_dof_scale_2.setOrientation(QtCore.Qt.Vertical)
        self.em1500_dof_scale_2.setInvertedAppearance(False)
        self.em1500_dof_scale_2.setObjectName("em1500_dof_scale_2")
        self.em1500_dof_scale_3 = QtWidgets.QProgressBar(self.groupBox_8)
        self.em1500_dof_scale_3.setGeometry(QtCore.QRect(179, 36, 38, 240))
        self.em1500_dof_scale_3.setMinimum(0)
        self.em1500_dof_scale_3.setProperty("value", 100)
        self.em1500_dof_scale_3.setOrientation(QtCore.Qt.Vertical)
        self.em1500_dof_scale_3.setInvertedAppearance(False)
        self.em1500_dof_scale_3.setObjectName("em1500_dof_scale_3")
        self.em1500_dof_scale_4 = QtWidgets.QProgressBar(self.groupBox_8)
        self.em1500_dof_scale_4.setGeometry(QtCore.QRect(231, 36, 38, 240))
        self.em1500_dof_scale_4.setMinimum(0)
        self.em1500_dof_scale_4.setProperty("value", 100)
        self.em1500_dof_scale_4.setOrientation(QtCore.Qt.Vertical)
        self.em1500_dof_scale_4.setInvertedAppearance(False)
        self.em1500_dof_scale_4.setObjectName("em1500_dof_scale_4")
        self.em1500_dof_scale_5 = QtWidgets.QProgressBar(self.groupBox_8)
        self.em1500_dof_scale_5.setGeometry(QtCore.QRect(284, 36, 38, 240))
        self.em1500_dof_scale_5.setMinimum(0)
        self.em1500_dof_scale_5.setProperty("value", 100)
        self.em1500_dof_scale_5.setOrientation(QtCore.Qt.Vertical)
        self.em1500_dof_scale_5.setInvertedAppearance(False)
        self.em1500_dof_scale_5.setObjectName("em1500_dof_scale_5")
        self.label_48 = QtWidgets.QLabel(self.groupBox_8)
        self.label_48.setGeometry(QtCore.QRect(276, 280, 50, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 180, 351, 321))
        self.groupBox_10.setObjectName("groupBox_10")
        self.em8000_dof_scale_0 = QtWidgets.QProgressBar(self.groupBox_10)
        self.em8000_dof_scale_0.setGeometry(QtCore.QRect(21, 36, 38, 240))
        self.em8000_dof_scale_0.setMinimum(0)
        self.em8000_dof_scale_0.setProperty("value", 100)
        self.em8000_dof_scale_0.setOrientation(QtCore.Qt.Vertical)
        self.em8000_dof_scale_0.setInvertedAppearance(False)
        self.em8000_dof_scale_0.setObjectName("em8000_dof_scale_0")
        self.label_53 = QtWidgets.QLabel(self.groupBox_10)
        self.label_53.setGeometry(QtCore.QRect(223, 280, 50, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.groupBox_10)
        self.label_54.setGeometry(QtCore.QRect(188, 280, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.groupBox_10)
        self.label_55.setGeometry(QtCore.QRect(132, 280, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.groupBox_10)
        self.label_56.setGeometry(QtCore.QRect(82, 280, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.groupBox_10)
        self.label_57.setGeometry(QtCore.QRect(28, 280, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.em8000_dof_scale_1 = QtWidgets.QProgressBar(self.groupBox_10)
        self.em8000_dof_scale_1.setGeometry(QtCore.QRect(74, 36, 38, 240))
        self.em8000_dof_scale_1.setMinimum(0)
        self.em8000_dof_scale_1.setProperty("value", 100)
        self.em8000_dof_scale_1.setOrientation(QtCore.Qt.Vertical)
        self.em8000_dof_scale_1.setInvertedAppearance(False)
        self.em8000_dof_scale_1.setObjectName("em8000_dof_scale_1")
        self.em8000_dof_scale_2 = QtWidgets.QProgressBar(self.groupBox_10)
        self.em8000_dof_scale_2.setGeometry(QtCore.QRect(126, 36, 38, 240))
        self.em8000_dof_scale_2.setMinimum(0)
        self.em8000_dof_scale_2.setProperty("value", 100)
        self.em8000_dof_scale_2.setOrientation(QtCore.Qt.Vertical)
        self.em8000_dof_scale_2.setInvertedAppearance(False)
        self.em8000_dof_scale_2.setObjectName("em8000_dof_scale_2")
        self.em8000_dof_scale_3 = QtWidgets.QProgressBar(self.groupBox_10)
        self.em8000_dof_scale_3.setGeometry(QtCore.QRect(179, 36, 38, 240))
        self.em8000_dof_scale_3.setMinimum(0)
        self.em8000_dof_scale_3.setProperty("value", 100)
        self.em8000_dof_scale_3.setOrientation(QtCore.Qt.Vertical)
        self.em8000_dof_scale_3.setInvertedAppearance(False)
        self.em8000_dof_scale_3.setObjectName("em8000_dof_scale_3")
        self.em8000_dof_scale_4 = QtWidgets.QProgressBar(self.groupBox_10)
        self.em8000_dof_scale_4.setGeometry(QtCore.QRect(231, 36, 38, 240))
        self.em8000_dof_scale_4.setMinimum(0)
        self.em8000_dof_scale_4.setProperty("value", 100)
        self.em8000_dof_scale_4.setOrientation(QtCore.Qt.Vertical)
        self.em8000_dof_scale_4.setInvertedAppearance(False)
        self.em8000_dof_scale_4.setObjectName("em8000_dof_scale_4")
        self.em8000_dof_scale_5 = QtWidgets.QProgressBar(self.groupBox_10)
        self.em8000_dof_scale_5.setGeometry(QtCore.QRect(284, 36, 38, 240))
        self.em8000_dof_scale_5.setMinimum(0)
        self.em8000_dof_scale_5.setProperty("value", 100)
        self.em8000_dof_scale_5.setOrientation(QtCore.Qt.Vertical)
        self.em8000_dof_scale_5.setInvertedAppearance(False)
        self.em8000_dof_scale_5.setObjectName("em8000_dof_scale_5")
        self.label_65 = QtWidgets.QLabel(self.groupBox_10)
        self.label_65.setGeometry(QtCore.QRect(276, 280, 50, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.tabSelector.addTab(self.tab_12, "")
        self.tab_interface = QtWidgets.QWidget()
        self.tab_interface.setObjectName("tab_interface")
        self.groupBox_38 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_38.setGeometry(QtCore.QRect(370, 10, 901, 811))
        self.groupBox_38.setObjectName("groupBox_38")
        self.comau_plot = GraphicsLayoutWidget(self.groupBox_38)
        self.comau_plot.setGeometry(QtCore.QRect(10, 30, 881, 771))
        self.comau_plot.setObjectName("comau_plot")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 10, 351, 91))
        self.groupBox_15.setObjectName("groupBox_15")
        self.comau_eModeCmd = QtWidgets.QComboBox(self.groupBox_15)
        self.comau_eModeCmd.setGeometry(QtCore.QRect(13, 30, 153, 22))
        self.comau_eModeCmd.setObjectName("comau_eModeCmd")
        self.comau_eModeCmd.addItem("")
        self.comau_eModeCmd.addItem("")
        self.comau_eModeCmd.addItem("")
        self.comau_engage = QtWidgets.QPushButton(self.groupBox_15)
        self.comau_engage.setGeometry(QtCore.QRect(12, 60, 155, 23))
        self.comau_engage.setObjectName("comau_engage")
        self.comau_disengage = QtWidgets.QPushButton(self.groupBox_15)
        self.comau_disengage.setGeometry(QtCore.QRect(180, 60, 155, 23))
        self.comau_disengage.setObjectName("comau_disengage")
        self.comau_eMode = QtWidgets.QLineEdit(self.groupBox_15)
        self.comau_eMode.setGeometry(QtCore.QRect(180, 30, 153, 22))
        self.comau_eMode.setReadOnly(True)
        self.comau_eMode.setObjectName("comau_eMode")
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_20.setGeometry(QtCore.QRect(10, 190, 351, 221))
        self.groupBox_20.setObjectName("groupBox_20")
        self.groupBox_21 = QtWidgets.QGroupBox(self.groupBox_20)
        self.groupBox_21.setGeometry(QtCore.QRect(160, 230, 351, 231))
        self.groupBox_21.setObjectName("groupBox_21")
        self.comau_q_0 = QtWidgets.QProgressBar(self.groupBox_20)
        self.comau_q_0.setGeometry(QtCore.QRect(40, 29, 300, 23))
        self.comau_q_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comau_q_0.setMinimum(0)
        self.comau_q_0.setProperty("value", 50)
        self.comau_q_0.setTextVisible(False)
        self.comau_q_0.setObjectName("comau_q_0")
        self.comau_q_1 = QtWidgets.QProgressBar(self.groupBox_20)
        self.comau_q_1.setGeometry(QtCore.QRect(40, 60, 300, 23))
        self.comau_q_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comau_q_1.setMinimum(0)
        self.comau_q_1.setProperty("value", 50)
        self.comau_q_1.setTextVisible(False)
        self.comau_q_1.setObjectName("comau_q_1")
        self.comau_q_2 = QtWidgets.QProgressBar(self.groupBox_20)
        self.comau_q_2.setGeometry(QtCore.QRect(40, 91, 300, 23))
        self.comau_q_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comau_q_2.setMinimum(0)
        self.comau_q_2.setProperty("value", 50)
        self.comau_q_2.setTextVisible(False)
        self.comau_q_2.setObjectName("comau_q_2")
        self.comau_q_3 = QtWidgets.QProgressBar(self.groupBox_20)
        self.comau_q_3.setGeometry(QtCore.QRect(40, 121, 300, 23))
        self.comau_q_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comau_q_3.setMinimum(0)
        self.comau_q_3.setProperty("value", 50)
        self.comau_q_3.setTextVisible(False)
        self.comau_q_3.setObjectName("comau_q_3")
        self.comau_q_4 = QtWidgets.QProgressBar(self.groupBox_20)
        self.comau_q_4.setGeometry(QtCore.QRect(40, 152, 300, 23))
        self.comau_q_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comau_q_4.setMinimum(0)
        self.comau_q_4.setProperty("value", 50)
        self.comau_q_4.setTextVisible(False)
        self.comau_q_4.setObjectName("comau_q_4")
        self.comau_q_5 = QtWidgets.QProgressBar(self.groupBox_20)
        self.comau_q_5.setGeometry(QtCore.QRect(40, 183, 300, 23))
        self.comau_q_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comau_q_5.setMinimum(0)
        self.comau_q_5.setProperty("value", 50)
        self.comau_q_5.setTextVisible(False)
        self.comau_q_5.setObjectName("comau_q_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_20)
        self.label_8.setGeometry(QtCore.QRect(10, 32, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_20 = QtWidgets.QLabel(self.groupBox_20)
        self.label_20.setGeometry(QtCore.QRect(10, 64, 47, 13))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_20)
        self.label_21.setGeometry(QtCore.QRect(10, 94, 47, 13))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_20)
        self.label_22.setGeometry(QtCore.QRect(10, 125, 47, 13))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_20)
        self.label_23.setGeometry(QtCore.QRect(10, 155, 47, 13))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_20)
        self.label_24.setGeometry(QtCore.QRect(10, 186, 47, 13))
        self.label_24.setObjectName("label_24")
        self.groupBox_42 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_42.setGeometry(QtCore.QRect(10, 580, 351, 71))
        self.groupBox_42.setObjectName("groupBox_42")
        self.winch_l = QtWidgets.QProgressBar(self.groupBox_42)
        self.winch_l.setGeometry(QtCore.QRect(40, 33, 300, 23))
        self.winch_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.winch_l.setMinimum(0)
        self.winch_l.setProperty("value", 50)
        self.winch_l.setTextVisible(False)
        self.winch_l.setObjectName("winch_l")
        self.label_25 = QtWidgets.QLabel(self.groupBox_42)
        self.label_25.setGeometry(QtCore.QRect(11, 37, 47, 13))
        self.label_25.setObjectName("label_25")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 423, 351, 91))
        self.groupBox_16.setObjectName("groupBox_16")
        self.winch_eModeCmd = QtWidgets.QComboBox(self.groupBox_16)
        self.winch_eModeCmd.setGeometry(QtCore.QRect(13, 30, 155, 22))
        self.winch_eModeCmd.setObjectName("winch_eModeCmd")
        self.winch_eModeCmd.addItem("")
        self.winch_eModeCmd.addItem("")
        self.winch_eModeCmd.addItem("")
        self.winch_eModeCmd.addItem("")
        self.winch_engage = QtWidgets.QPushButton(self.groupBox_16)
        self.winch_engage.setGeometry(QtCore.QRect(12, 60, 155, 23))
        self.winch_engage.setObjectName("winch_engage")
        self.winch_disengage = QtWidgets.QPushButton(self.groupBox_16)
        self.winch_disengage.setGeometry(QtCore.QRect(180, 60, 155, 23))
        self.winch_disengage.setObjectName("winch_disengage")
        self.winch_eMode = QtWidgets.QLineEdit(self.groupBox_16)
        self.winch_eMode.setGeometry(QtCore.QRect(180, 30, 153, 22))
        self.winch_eMode.setReadOnly(True)
        self.winch_eMode.setObjectName("winch_eMode")
        self.groupBox_43 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_43.setGeometry(QtCore.QRect(10, 517, 351, 61))
        self.groupBox_43.setObjectName("groupBox_43")
        self.winchVelSetpoint = QtWidgets.QSlider(self.groupBox_43)
        self.winchVelSetpoint.setGeometry(QtCore.QRect(40, 28, 291, 22))
        self.winchVelSetpoint.setMinimum(-100)
        self.winchVelSetpoint.setMaximum(100)
        self.winchVelSetpoint.setSingleStep(0)
        self.winchVelSetpoint.setOrientation(QtCore.Qt.Horizontal)
        self.winchVelSetpoint.setObjectName("winchVelSetpoint")
        self.label_26 = QtWidgets.QLabel(self.groupBox_43)
        self.label_26.setGeometry(QtCore.QRect(10, 30, 47, 13))
        self.label_26.setObjectName("label_26")
        self.groupBox_47 = QtWidgets.QGroupBox(self.tab_interface)
        self.groupBox_47.setGeometry(QtCore.QRect(10, 100, 351, 71))
        self.groupBox_47.setObjectName("groupBox_47")
        self.tabSelector.addTab(self.tab_interface, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        self.label_34.setGeometry(QtCore.QRect(30, 20, 581, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.line_4 = QtWidgets.QFrame(self.tab_4)
        self.line_4.setGeometry(QtCore.QRect(20, 40, 1071, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.estimatedDampingPlot = QtWidgets.QTabWidget(self.tab_4)
        self.estimatedDampingPlot.setGeometry(QtCore.QRect(300, 70, 791, 701))
        self.estimatedDampingPlot.setTabBarAutoHide(False)
        self.estimatedDampingPlot.setObjectName("estimatedDampingPlot")
        self.widget_3 = QtWidgets.QWidget()
        self.widget_3.setObjectName("widget_3")
        self.swingAnglesWidget = GraphicsLayoutWidget(self.widget_3)
        self.swingAnglesWidget.setGeometry(QtCore.QRect(0, 0, 791, 335))
        self.swingAnglesWidget.setObjectName("swingAnglesWidget")
        self.swingVelocityWidget = GraphicsLayoutWidget(self.widget_3)
        self.swingVelocityWidget.setGeometry(QtCore.QRect(0, 337, 791, 335))
        self.swingVelocityWidget.setObjectName("swingVelocityWidget")
        self.estimatedDampingPlot.addTab(self.widget_3, "")
        self.DampingParamter = QtWidgets.QWidget()
        self.DampingParamter.setObjectName("DampingParamter")
        self.dampingParamPlotWidget = GraphicsLayoutWidget(self.DampingParamter)
        self.dampingParamPlotWidget.setGeometry(QtCore.QRect(0, 0, 791, 671))
        self.dampingParamPlotWidget.setObjectName("dampingParamPlotWidget")
        self.estimatedDampingPlot.addTab(self.DampingParamter, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.errorStatePlotWidget = GraphicsLayoutWidget(self.tab_10)
        self.errorStatePlotWidget.setGeometry(QtCore.QRect(0, 0, 791, 671))
        self.errorStatePlotWidget.setObjectName("errorStatePlotWidget")
        self.estimatedDampingPlot.addTab(self.tab_10, "")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_17.setGeometry(QtCore.QRect(20, 70, 241, 51))
        self.groupBox_17.setObjectName("groupBox_17")
        self.label_98 = QtWidgets.QLabel(self.groupBox_17)
        self.label_98.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.label_98.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_98.setObjectName("label_98")
        self.antiSwayPlotRange = QtWidgets.QComboBox(self.groupBox_17)
        self.antiSwayPlotRange.setGeometry(QtCore.QRect(130, 20, 69, 22))
        self.antiSwayPlotRange.setObjectName("antiSwayPlotRange")
        self.antiSwayPlotRange.addItem("")
        self.antiSwayPlotRange.addItem("")
        self.antiSwayPlotRange.addItem("")
        self.antiSwayPlotRange.addItem("")
        self.antiSwayPlotRange.addItem("")
        self.antiSwayPlotRange.addItem("")
        self.label_99 = QtWidgets.QLabel(self.groupBox_17)
        self.label_99.setGeometry(QtCore.QRect(210, 20, 31, 20))
        self.label_99.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_99.setObjectName("label_99")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_18.setGeometry(QtCore.QRect(20, 330, 241, 151))
        self.groupBox_18.setObjectName("groupBox_18")
        self.btnDeactivateAntiSway = QtWidgets.QPushButton(self.groupBox_18)
        self.btnDeactivateAntiSway.setGeometry(QtCore.QRect(10, 70, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDeactivateAntiSway.setFont(font)
        self.btnDeactivateAntiSway.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnDeactivateAntiSway.setAutoDefault(False)
        self.btnDeactivateAntiSway.setObjectName("btnDeactivateAntiSway")
        self.btnActivateAntiSway = QtWidgets.QPushButton(self.groupBox_18)
        self.btnActivateAntiSway.setGeometry(QtCore.QRect(10, 30, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnActivateAntiSway.setFont(font)
        self.btnActivateAntiSway.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnActivateAntiSway.setAutoDefault(False)
        self.btnActivateAntiSway.setObjectName("btnActivateAntiSway")
        self.btnResetAntiSway = QtWidgets.QPushButton(self.groupBox_18)
        self.btnResetAntiSway.setGeometry(QtCore.QRect(10, 110, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnResetAntiSway.setFont(font)
        self.btnResetAntiSway.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnResetAntiSway.setAutoDefault(False)
        self.btnResetAntiSway.setObjectName("btnResetAntiSway")
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_24.setGeometry(QtCore.QRect(20, 160, 241, 151))
        self.groupBox_24.setObjectName("groupBox_24")
        self.btnEnableMruEKF = QtWidgets.QPushButton(self.groupBox_24)
        self.btnEnableMruEKF.setGeometry(QtCore.QRect(10, 70, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEnableMruEKF.setFont(font)
        self.btnEnableMruEKF.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnEnableMruEKF.setAutoDefault(False)
        self.btnEnableMruEKF.setObjectName("btnEnableMruEKF")
        self.btnDisableMruEKF = QtWidgets.QPushButton(self.groupBox_24)
        self.btnDisableMruEKF.setGeometry(QtCore.QRect(10, 30, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDisableMruEKF.setFont(font)
        self.btnDisableMruEKF.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnDisableMruEKF.setAutoDefault(False)
        self.btnDisableMruEKF.setObjectName("btnDisableMruEKF")
        self.btnResetEKF = QtWidgets.QPushButton(self.groupBox_24)
        self.btnResetEKF.setGeometry(QtCore.QRect(10, 110, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnResetEKF.setFont(font)
        self.btnResetEKF.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnResetEKF.setAutoDefault(False)
        self.btnResetEKF.setObjectName("btnResetEKF")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_19.setGeometry(QtCore.QRect(20, 630, 241, 111))
        self.groupBox_19.setObjectName("groupBox_19")
        self.btnEnableMruCM = QtWidgets.QPushButton(self.groupBox_19)
        self.btnEnableMruCM.setGeometry(QtCore.QRect(10, 70, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEnableMruCM.setFont(font)
        self.btnEnableMruCM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnEnableMruCM.setAutoDefault(False)
        self.btnEnableMruCM.setObjectName("btnEnableMruCM")
        self.btnDisableMruCM = QtWidgets.QPushButton(self.groupBox_19)
        self.btnDisableMruCM.setGeometry(QtCore.QRect(10, 30, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDisableMruCM.setFont(font)
        self.btnDisableMruCM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnDisableMruCM.setAutoDefault(False)
        self.btnDisableMruCM.setObjectName("btnDisableMruCM")
        self.groupBox_25 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_25.setGeometry(QtCore.QRect(20, 500, 241, 111))
        self.groupBox_25.setObjectName("groupBox_25")
        self.btnEnableMruWinch = QtWidgets.QPushButton(self.groupBox_25)
        self.btnEnableMruWinch.setGeometry(QtCore.QRect(10, 70, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEnableMruWinch.setFont(font)
        self.btnEnableMruWinch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnEnableMruWinch.setAutoDefault(False)
        self.btnEnableMruWinch.setObjectName("btnEnableMruWinch")
        self.btnDisableMruWinch = QtWidgets.QPushButton(self.groupBox_25)
        self.btnDisableMruWinch.setGeometry(QtCore.QRect(10, 30, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnDisableMruWinch.setFont(font)
        self.btnDisableMruWinch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnDisableMruWinch.setAutoDefault(False)
        self.btnDisableMruWinch.setObjectName("btnDisableMruWinch")
        self.tabSelector.addTab(self.tab_4, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.groupBox_41 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_41.setGeometry(QtCore.QRect(370, 10, 901, 811))
        self.groupBox_41.setObjectName("groupBox_41")
        self.waveSpectrum_plot_2 = GraphicsLayoutWidget(self.groupBox_41)
        self.waveSpectrum_plot_2.setGeometry(QtCore.QRect(10, 30, 881, 771))
        self.waveSpectrum_plot_2.setObjectName("waveSpectrum_plot_2")
        self.tabSelector.addTab(self.tab_9, "")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 860, 1285, 140))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.logDump = QtWidgets.QTextEdit(self.tab)
        self.logDump.setGeometry(QtCore.QRect(510, 9, 761, 93))
        self.logDump.setReadOnly(True)
        self.logDump.setObjectName("logDump")
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_22.setGeometry(QtCore.QRect(120, 0, 381, 102))
        self.groupBox_22.setObjectName("groupBox_22")
        self.em1500_bActive = QtWidgets.QLabel(self.groupBox_22)
        self.em1500_bActive.setGeometry(QtCore.QRect(20, 73, 20, 20))
        self.em1500_bActive.setObjectName("em1500_bActive")
        self.label_28 = QtWidgets.QLabel(self.groupBox_22)
        self.label_28.setGeometry(QtCore.QRect(44, 73, 47, 20))
        self.label_28.setObjectName("label_28")
        self.mru1_bActive = QtWidgets.QLabel(self.groupBox_22)
        self.mru1_bActive.setGeometry(QtCore.QRect(107, 23, 20, 20))
        self.mru1_bActive.setObjectName("mru1_bActive")
        self.mru2_bActive = QtWidgets.QLabel(self.groupBox_22)
        self.mru2_bActive.setGeometry(QtCore.QRect(107, 73, 20, 20))
        self.mru2_bActive.setObjectName("mru2_bActive")
        self.label_27 = QtWidgets.QLabel(self.groupBox_22)
        self.label_27.setGeometry(QtCore.QRect(44, 23, 47, 20))
        self.label_27.setObjectName("label_27")
        self.label_31 = QtWidgets.QLabel(self.groupBox_22)
        self.label_31.setGeometry(QtCore.QRect(132, 73, 41, 20))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_22)
        self.label_32.setGeometry(QtCore.QRect(132, 23, 41, 20))
        self.label_32.setObjectName("label_32")
        self.label_37 = QtWidgets.QLabel(self.groupBox_22)
        self.label_37.setGeometry(QtCore.QRect(310, 73, 61, 20))
        self.label_37.setObjectName("label_37")
        self.qtm_bActive = QtWidgets.QLabel(self.groupBox_22)
        self.qtm_bActive.setGeometry(QtCore.QRect(286, 73, 20, 20))
        self.qtm_bActive.setObjectName("qtm_bActive")
        self.em8000_bActive = QtWidgets.QLabel(self.groupBox_22)
        self.em8000_bActive.setGeometry(QtCore.QRect(20, 23, 20, 20))
        self.em8000_bActive.setObjectName("em8000_bActive")
        self.label_35 = QtWidgets.QLabel(self.groupBox_22)
        self.label_35.setGeometry(QtCore.QRect(218, 23, 61, 20))
        self.label_35.setObjectName("label_35")
        self.remote_bActive = QtWidgets.QLabel(self.groupBox_22)
        self.remote_bActive.setGeometry(QtCore.QRect(286, 23, 20, 20))
        self.remote_bActive.setObjectName("remote_bActive")
        self.comau_bActive = QtWidgets.QLabel(self.groupBox_22)
        self.comau_bActive.setGeometry(QtCore.QRect(194, 23, 20, 20))
        self.comau_bActive.setObjectName("comau_bActive")
        self.winch_bActive = QtWidgets.QLabel(self.groupBox_22)
        self.winch_bActive.setGeometry(QtCore.QRect(194, 73, 20, 20))
        self.winch_bActive.setObjectName("winch_bActive")
        self.label_33 = QtWidgets.QLabel(self.groupBox_22)
        self.label_33.setGeometry(QtCore.QRect(218, 73, 61, 20))
        self.label_33.setObjectName("label_33")
        self.label_36 = QtWidgets.QLabel(self.groupBox_22)
        self.label_36.setGeometry(QtCore.QRect(310, 23, 61, 20))
        self.label_36.setObjectName("label_36")
        self.stopButtonA = QtWidgets.QPushButton(self.tab)
        self.stopButtonA.setGeometry(QtCore.QRect(10, 10, 92, 92))
        self.stopButtonA.setText("")
        self.stopButtonA.setObjectName("stopButtonA")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_45 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_45.setGeometry(QtCore.QRect(120, 0, 431, 101))
        self.groupBox_45.setObjectName("groupBox_45")
        self.logEndTime = QtWidgets.QSpinBox(self.groupBox_45)
        self.logEndTime.setGeometry(QtCore.QRect(301, 29, 81, 21))
        self.logEndTime.setMinimum(1)
        self.logEndTime.setMaximum(1200)
        self.logEndTime.setProperty("value", 10)
        self.logEndTime.setObjectName("logEndTime")
        self.label_154 = QtWidgets.QLabel(self.groupBox_45)
        self.label_154.setGeometry(QtCore.QRect(10, 29, 181, 19))
        self.label_154.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_154.setObjectName("label_154")
        self.label_153 = QtWidgets.QLabel(self.groupBox_45)
        self.label_153.setGeometry(QtCore.QRect(400, 28, 31, 19))
        self.label_153.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_153.setObjectName("label_153")
        self.logFilePath = QtWidgets.QLineEdit(self.groupBox_45)
        self.logFilePath.setGeometry(QtCore.QRect(10, 60, 371, 20))
        self.logFilePath.setObjectName("logFilePath")
        self.groupBox_44 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_44.setGeometry(QtCore.QRect(690, 0, 351, 101))
        self.groupBox_44.setObjectName("groupBox_44")
        self.logProgress = QtWidgets.QProgressBar(self.groupBox_44)
        self.logProgress.setGeometry(QtCore.QRect(9, 64, 331, 23))
        self.logProgress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.logProgress.setMinimum(0)
        self.logProgress.setProperty("value", 0)
        self.logProgress.setTextVisible(False)
        self.logProgress.setObjectName("logProgress")
        self.label_155 = QtWidgets.QLabel(self.groupBox_44)
        self.label_155.setGeometry(QtCore.QRect(10, 30, 181, 19))
        self.label_155.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_155.setObjectName("label_155")
        self.logSampleCount = QtWidgets.QLineEdit(self.groupBox_44)
        self.logSampleCount.setGeometry(QtCore.QRect(218, 30, 121, 22))
        self.logSampleCount.setReadOnly(True)
        self.logSampleCount.setObjectName("logSampleCount")
        self.groupBox_48 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_48.setGeometry(QtCore.QRect(560, 0, 121, 101))
        self.groupBox_48.setObjectName("groupBox_48")
        self.btnStartLog = QtWidgets.QPushButton(self.groupBox_48)
        self.btnStartLog.setGeometry(QtCore.QRect(10, 30, 100, 23))
        self.btnStartLog.setObjectName("btnStartLog")
        self.btnStopLog = QtWidgets.QPushButton(self.groupBox_48)
        self.btnStopLog.setGeometry(QtCore.QRect(10, 60, 100, 23))
        self.btnStopLog.setObjectName("btnStopLog")
        self.stopButtonB = QtWidgets.QPushButton(self.tab_2)
        self.stopButtonB.setGeometry(QtCore.QRect(10, 10, 92, 92))
        self.stopButtonB.setText("")
        self.stopButtonB.setObjectName("stopButtonB")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1309, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabSelector.setCurrentIndex(1)
        self.spectrumType.setCurrentIndex(0)
        self.estimatedDampingPlot.setCurrentIndex(0)
        self.antiSwayPlotRange.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Sine Generator Settings"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Amp [m]"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Freq [Hz]"))
        self.groupBox_30.setTitle(_translate("MainWindow", "Phase [deg]"))
        self.groupBox_33.setTitle(_translate("MainWindow", "Amp [deg]"))
        self.groupBox_34.setTitle(_translate("MainWindow", "Freq [Hz]"))
        self.groupBox_35.setTitle(_translate("MainWindow", "Phase [deg]"))
        self.groupBox_36.setTitle(_translate("MainWindow", "DOF"))
        self.label_7.setText(_translate("MainWindow", "Roll:"))
        self.label_9.setText(_translate("MainWindow", "Heave:"))
        self.label_10.setText(_translate("MainWindow", "Surge:"))
        self.label_11.setText(_translate("MainWindow", "Pitch:"))
        self.label_12.setText(_translate("MainWindow", "Sway:"))
        self.label_16.setText(_translate("MainWindow", "Yaw:"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Stewart Status Feedback"))
        self.label_17.setText(_translate("MainWindow", "Operation State:"))
        self.label_18.setText(_translate("MainWindow", "System Status:"))
        self.label_19.setText(_translate("MainWindow", "Operation Mode:"))
        self.groupBox_37.setTitle(_translate("MainWindow", "Stewart Command Inspector"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Stewart Operation"))
        self.em8000_eModeCmd.setItemText(0, _translate("MainWindow", "SETTLED"))
        self.em8000_eModeCmd.setItemText(1, _translate("MainWindow", "NEUTRAL"))
        self.em8000_eModeCmd.setItemText(2, _translate("MainWindow", "SIMULATION"))
        self.em8000_eModeCmd.setItemText(3, _translate("MainWindow", "GENERATOR"))
        self.em8000_eModeCmd.setItemText(4, _translate("MainWindow", "REMOTE"))
        self.em8000_engage.setText(_translate("MainWindow", "ENGAGE"))
        self.em8000_disengage.setText(_translate("MainWindow", "DISENGAGE"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Actuator Stroke Utilization"))
        self.label_59.setText(_translate("MainWindow", "5"))
        self.label_60.setText(_translate("MainWindow", "6"))
        self.label_61.setText(_translate("MainWindow", "4"))
        self.label_62.setText(_translate("MainWindow", "3"))
        self.label_63.setText(_translate("MainWindow", "2"))
        self.label_64.setText(_translate("MainWindow", "1"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_11), _translate("MainWindow", "EM8000"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Stewart Operation"))
        self.em1500_eModeCmd.setItemText(0, _translate("MainWindow", "SETTLED"))
        self.em1500_eModeCmd.setItemText(1, _translate("MainWindow", "NEUTRAL"))
        self.em1500_eModeCmd.setItemText(2, _translate("MainWindow", "SIMULATION"))
        self.em1500_eModeCmd.setItemText(3, _translate("MainWindow", "GENERATOR"))
        self.em1500_eModeCmd.setItemText(4, _translate("MainWindow", "REMOTE"))
        self.em1500_engage.setText(_translate("MainWindow", "ENGAGE"))
        self.em1500_disengage.setText(_translate("MainWindow", "DISENGAGE"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Sine Generator Settings"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Amp [m]"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Freq [Hz]"))
        self.groupBox_26.setTitle(_translate("MainWindow", "Phase [deg]"))
        self.groupBox_27.setTitle(_translate("MainWindow", "Amp [deg]"))
        self.groupBox_28.setTitle(_translate("MainWindow", "Freq [Hz]"))
        self.groupBox_29.setTitle(_translate("MainWindow", "Phase [deg]"))
        self.groupBox_31.setTitle(_translate("MainWindow", "DOF"))
        self.label_5.setText(_translate("MainWindow", "Roll:"))
        self.label_3.setText(_translate("MainWindow", "Heave:"))
        self.label.setText(_translate("MainWindow", "Surge:"))
        self.label_6.setText(_translate("MainWindow", "Pitch:"))
        self.label_2.setText(_translate("MainWindow", "Sway:"))
        self.label_4.setText(_translate("MainWindow", "Yaw:"))
        self.groupBox_32.setTitle(_translate("MainWindow", "Stewart Command Inspector"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Actuator Stroke Utilization"))
        self.label_41.setText(_translate("MainWindow", "5"))
        self.label_42.setText(_translate("MainWindow", "6"))
        self.label_43.setText(_translate("MainWindow", "4"))
        self.label_44.setText(_translate("MainWindow", "3"))
        self.label_45.setText(_translate("MainWindow", "2"))
        self.label_46.setText(_translate("MainWindow", "1"))
        self.groupBox.setTitle(_translate("MainWindow", "Stewart Status Feedback"))
        self.label_13.setText(_translate("MainWindow", "Operation State:"))
        self.label_14.setText(_translate("MainWindow", "System Status:"))
        self.label_15.setText(_translate("MainWindow", "Operation Mode:"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_8), _translate("MainWindow", "EM1500"))
        self.groupBox_40.setTitle(_translate("MainWindow", "Wave Spectrum"))
        self.groupBox_23.setTitle(_translate("MainWindow", "Wave Spectrum Settings"))
        self.label_149.setText(_translate("MainWindow", "[s]"))
        self.label_151.setText(_translate("MainWindow", "[m]"))
        self.label_152.setText(_translate("MainWindow", "Significant Wave Height (Hs):"))
        self.label_159.setText(_translate("MainWindow", "Wave Time Period (Tp) :"))
        self.label_160.setText(_translate("MainWindow", "Wave Spectum :"))
        self.spectrumType.setCurrentText(_translate("MainWindow", "Pierson-Moskowitz"))
        self.spectrumType.setItemText(0, _translate("MainWindow", "Pierson-Moskowitz"))
        self.spectrumType.setItemText(1, _translate("MainWindow", "JONSWAP"))
        self.bResetDofScaling.setText(_translate("MainWindow", "Reset DOF Scaling"))
        self.groupBox_8.setTitle(_translate("MainWindow", "EM1500 DOF Scale"))
        self.label_47.setText(_translate("MainWindow", "pitch"))
        self.label_49.setText(_translate("MainWindow", "roll"))
        self.label_50.setText(_translate("MainWindow", "z"))
        self.label_51.setText(_translate("MainWindow", "y"))
        self.label_52.setText(_translate("MainWindow", "x"))
        self.label_48.setText(_translate("MainWindow", "yaw"))
        self.groupBox_10.setTitle(_translate("MainWindow", "EM8000 DOF Scale"))
        self.label_53.setText(_translate("MainWindow", "pitch"))
        self.label_54.setText(_translate("MainWindow", "roll"))
        self.label_55.setText(_translate("MainWindow", "z"))
        self.label_56.setText(_translate("MainWindow", "y"))
        self.label_57.setText(_translate("MainWindow", "x"))
        self.label_65.setText(_translate("MainWindow", "yaw"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_12), _translate("MainWindow", "Wave Simulator"))
        self.groupBox_38.setTitle(_translate("MainWindow", "Control Inputs"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Robot Operation Mode"))
        self.comau_eModeCmd.setItemText(0, _translate("MainWindow", "SETTLED"))
        self.comau_eModeCmd.setItemText(1, _translate("MainWindow", "REMOTE"))
        self.comau_eModeCmd.setItemText(2, _translate("MainWindow", "MOTION_COMP"))
        self.comau_engage.setText(_translate("MainWindow", "ENGAGE"))
        self.comau_disengage.setText(_translate("MainWindow", "DISENGAGE"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Robot Joint Angle Utilization - qMin < q(t) < qMax"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Robot Jont Utilization"))
        self.label_8.setText(_translate("MainWindow", "#1"))
        self.label_20.setText(_translate("MainWindow", "#2"))
        self.label_21.setText(_translate("MainWindow", "#3"))
        self.label_22.setText(_translate("MainWindow", "#4"))
        self.label_23.setText(_translate("MainWindow", "#5"))
        self.label_24.setText(_translate("MainWindow", "#6"))
        self.groupBox_42.setTitle(_translate("MainWindow", "Winch Length Utilization"))
        self.label_25.setText(_translate("MainWindow", "#1"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Winch Operation Mode"))
        self.winch_eModeCmd.setItemText(0, _translate("MainWindow", "SETTLED"))
        self.winch_eModeCmd.setItemText(1, _translate("MainWindow", "LOCAL"))
        self.winch_eModeCmd.setItemText(2, _translate("MainWindow", "REMOTE"))
        self.winch_eModeCmd.setItemText(3, _translate("MainWindow", "MOTION_COMP"))
        self.winch_engage.setText(_translate("MainWindow", "ENGAGE"))
        self.winch_disengage.setText(_translate("MainWindow", "DISENGAGE"))
        self.groupBox_43.setTitle(_translate("MainWindow", "Velocity Setpoint - max 0.2 m/s"))
        self.label_26.setText(_translate("MainWindow", "#1"))
        self.groupBox_47.setTitle(_translate("MainWindow", "Joint Jogger"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_interface), _translate("MainWindow", "Control Interface"))
        self.label_34.setText(_translate("MainWindow", "Controller and Anti-Swing System"))
        self.estimatedDampingPlot.setTabText(self.estimatedDampingPlot.indexOf(self.widget_3), _translate("MainWindow", "Pendulum States"))
        self.estimatedDampingPlot.setTabText(self.estimatedDampingPlot.indexOf(self.DampingParamter), _translate("MainWindow", "Damping Parameter"))
        self.estimatedDampingPlot.setTabText(self.estimatedDampingPlot.indexOf(self.tab_10), _translate("MainWindow", "Error States"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Plot options"))
        self.label_98.setText(_translate("MainWindow", "Time axis range:"))
        self.antiSwayPlotRange.setCurrentText(_translate("MainWindow", "10"))
        self.antiSwayPlotRange.setItemText(0, _translate("MainWindow", "10"))
        self.antiSwayPlotRange.setItemText(1, _translate("MainWindow", "20"))
        self.antiSwayPlotRange.setItemText(2, _translate("MainWindow", "30"))
        self.antiSwayPlotRange.setItemText(3, _translate("MainWindow", "40"))
        self.antiSwayPlotRange.setItemText(4, _translate("MainWindow", "50"))
        self.antiSwayPlotRange.setItemText(5, _translate("MainWindow", "60"))
        self.label_99.setText(_translate("MainWindow", "[s]"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Anti-Swing System"))
        self.btnDeactivateAntiSway.setText(_translate("MainWindow", "Deactivate"))
        self.btnActivateAntiSway.setText(_translate("MainWindow", "Activate"))
        self.btnResetAntiSway.setText(_translate("MainWindow", "Reset"))
        self.groupBox_24.setTitle(_translate("MainWindow", "Pendel Estimator - EKF"))
        self.btnEnableMruEKF.setText(_translate("MainWindow", "MRU Feedback"))
        self.btnDisableMruEKF.setText(_translate("MainWindow", "Stewart Feedback"))
        self.btnResetEKF.setText(_translate("MainWindow", "Reset"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Control Mapping"))
        self.btnEnableMruCM.setText(_translate("MainWindow", "MRU Feedback"))
        self.btnDisableMruCM.setText(_translate("MainWindow", "Stewart Feedback"))
        self.groupBox_25.setTitle(_translate("MainWindow", "Winch Controller"))
        self.btnEnableMruWinch.setText(_translate("MainWindow", "MRU Feedback"))
        self.btnDisableMruWinch.setText(_translate("MainWindow", "Stewart Feedback"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_4), _translate("MainWindow", "Pendel Estimator"))
        self.groupBox_41.setTitle(_translate("MainWindow", "Signal Inspector"))
        self.tabSelector.setTabText(self.tabSelector.indexOf(self.tab_9), _translate("MainWindow", "Signal Inspector"))
        self.groupBox_22.setTitle(_translate("MainWindow", "Machine and Sensor States"))
        self.em1500_bActive.setText(_translate("MainWindow", "X"))
        self.label_28.setText(_translate("MainWindow", "EM1500"))
        self.mru1_bActive.setText(_translate("MainWindow", "X"))
        self.mru2_bActive.setText(_translate("MainWindow", "X"))
        self.label_27.setText(_translate("MainWindow", "EM8000"))
        self.label_31.setText(_translate("MainWindow", "MRU2"))
        self.label_32.setText(_translate("MainWindow", "MRU1"))
        self.label_37.setText(_translate("MainWindow", "QTM"))
        self.qtm_bActive.setText(_translate("MainWindow", "X"))
        self.em8000_bActive.setText(_translate("MainWindow", "X"))
        self.label_35.setText(_translate("MainWindow", "COMAU"))
        self.remote_bActive.setText(_translate("MainWindow", "X"))
        self.comau_bActive.setText(_translate("MainWindow", "X"))
        self.winch_bActive.setText(_translate("MainWindow", "X"))
        self.label_33.setText(_translate("MainWindow", "WINCH"))
        self.label_36.setText(_translate("MainWindow", "REMOTE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Status"))
        self.groupBox_45.setTitle(_translate("MainWindow", "Data Logging Settings"))
        self.label_154.setText(_translate("MainWindow", "End logging after N seconds:"))
        self.label_153.setText(_translate("MainWindow", "[s]"))
        self.logFilePath.setText(_translate("MainWindow", "C:\\Temp\\log.csv"))
        self.groupBox_44.setTitle(_translate("MainWindow", "Log Progress"))
        self.label_155.setText(_translate("MainWindow", "Number og logged samples:"))
        self.logSampleCount.setText(_translate("MainWindow", "0"))
        self.groupBox_48.setTitle(_translate("MainWindow", "Start/Stop"))
        self.btnStartLog.setText(_translate("MainWindow", "Start"))
        self.btnStopLog.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "CSV Logger"))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

