// ****************** CWaveSimulatorNewClassFactory.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "stdafx.h"
#pragma hdrstop

#include "CWaveSimulatorNew.h"
#include "CWaveSimulatorNewClassFactory.h"

// ITComClassFactory
BEGIN_CLASS_MAP(CWaveSimulatorNewClassFactory)
	CLASS_ENTRY_RT(CID_WaveSimulatorNew,SRVNAME_WaveSimulatorNew "!CWaveSimulatorNew", CWaveSimulatorNew)
END_CLASS_MAP()


CWaveSimulatorNewClassFactory::CWaveSimulatorNewClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_WaveSimulatorNew)); 
}

