// ****************** CWaveSimulatorNewDrv.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef CWAVESIMULATORNEWDRV_H_INCLUDED
#define CWAVESIMULATORNEWDRV_H_INCLUDED

#include "TcPch.h"

#define WaveSimulatorNewDRV_NAME			"WaveSimulatorNew"
#define WaveSimulatorNewDRV_Major			1
#define WaveSimulatorNewDRV_Minor			0

#if defined DEVICE_MAIN		// is supposed to be __cplusplus

#define DEVICE_CLASS			CWaveSimulatorNewDrv

#include "ObjDriver.h"

class CWaveSimulatorNewDrv : public CObjDriver
{
public:
	virtual IOSTATUS	OnLoad( );
	virtual VOID		OnUnLoad( );
	
  //////////////////////////////////////////////////////
  // VxD-Services exported by this driver
  static unsigned long _cdecl WaveSimulatorNew_GetVersion( );
};

#endif	// #if defined DEVICE_MAIN

Begin_VxD_Service_Table( WaveSimulatorNewDRV)
	VxD_Service( WaveSimulatorNew_GetVersion		)
End_VxD_Service_Table


#endif
