// ****************** CWaveSimulatorNewDrv.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop
#define DEVICE_MAIN

#include "CWaveSimulatorNewDrv.h"
#include "CWaveSimulatorNew.h"
#include "CWaveSimulatorNewClassFactory.h"
#include "WaveSimulatorNewVersion.h"

DECLARE_GENERIC_DEVICE(WaveSimulatorNewDRV)
#undef DEVICE_MAIN

IOSTATUS CWaveSimulatorNewDrv::OnLoad( )
{
	TRACE(_T("CWaveSimulatorNewClassFactory::OnLoad()\n") );
	m_pObjClassFactory = new CWaveSimulatorNewClassFactory();

	return IOSTATUS_SUCCESS;
}

VOID CWaveSimulatorNewDrv::OnUnLoad( )
{
	delete m_pObjClassFactory;
}

unsigned long _cdecl CWaveSimulatorNewDrv::WaveSimulatorNew_GetVersion( )
{
	return(0);
}