// ****************** WaveSimulatorNewCtrl.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef WAVESIMULATORNEWCTRL_H_INCLUDED
#define WAVESIMULATORNEWCTRL_H_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CWaveSimulatorNewDrvName "WaveSimulatorNew"

#include "WaveSimulatorNewResource.h"
#include "WaveSimulatorNewW32.h"
#include "TcPch.h"
#include "CWaveSimulatorNewClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CWaveSimulatorNewCtrl :		public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CWaveSimulatorNewCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CWaveSimulatorNewCtrl, CWaveSimulatorNewClassFactory>
{
public:
	CWaveSimulatorNewCtrl() : ITcOCFCtrlImpl<CWaveSimulatorNewCtrl, CWaveSimulatorNewClassFactory>(){}

	virtual ~CWaveSimulatorNewCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_WaveSimulatorNewCtrl)
DECLARE_NOT_AGGREGATABLE(CWaveSimulatorNewCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CWaveSimulatorNewCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif
