// ****************** WaveSimulatorNewInterfaces.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef WAVESIMULATORNEWINTERFACES_H_INCLUDED
#define WAVESIMULATORNEWINTERFACES_H_INCLUDED

#include "WaveSimulatorNewServices.h"

// define new interfaces provided by this driver

#endif
