// ****************** WaveSimulatorNewServices.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef WAVESIMULATORNEWSERVICES_H_INCLUDED
#define WAVESIMULATORNEWSERVICES_H_INCLUDED

#define SRVNAME_WaveSimulatorNew "WaveSimulatorNew"

// TcCOM-ClassId of this module: cdc30dbe-9b25-4baf-a6ca-10f20dc3ffa4
const   CTCID   CID_WaveSimulatorNew    =  {0xcdc30dbe,0x9b25,0x4baf,{0xa6,0xca,0x10,0xf2,0x0d,0xc3,0xff,0xa4}};

#endif


