// ****************** CWaveSimulator0ClassFactory.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "stdafx.h"
#pragma hdrstop

#include "CWaveSimulator0.h"
#include "CWaveSimulator0ClassFactory.h"

// ITComClassFactory
BEGIN_CLASS_MAP(CWaveSimulator0ClassFactory)
	CLASS_ENTRY_RT(CID_WaveSimulator0,SRVNAME_WaveSimulator0 "!CWaveSimulator0", CWaveSimulator0)
END_CLASS_MAP()


CWaveSimulator0ClassFactory::CWaveSimulator0ClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_WaveSimulator0)); 
}

