// ****************** CWaveSimulator0ClassFactory.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#ifndef CWAVESIMULATOR0CLASSFACTORY_H_INCLUDED
#define CWAVESIMULATOR0CLASSFACTORY_H_INCLUDED

#include "ObjClassFactory.h"

class CWaveSimulator0ClassFactory : public CObjClassFactory
{
public:
	CWaveSimulator0ClassFactory();
	
	// ITComClassFactory
	DECLARE_CLASS_MAP()
};

#endif
