// ****************** TcPch.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
///////////////////////////////////////////////////////////////////////////////
// TcPch.cpp includes the projects standard header files using TcPch.h
// It is dedicated to create the precompiled header, which 
// is configured as a file specifc build option. 
// 
// - TcPch.pch will be the pre-compiled header
// - TcPch.obj will contain the pre-compiled type information
// 
// For correct precompiled header usage each *.cpp source file in 
// the TwinCAT driver project must start with the following two lines:

#include "TcPch.h"
#pragma hdrstop


#ifdef _ATL_STATIC_REGISTRY
#include <statreg.h>
#include <statreg.cpp>
#endif