// ****************** WaveSimulator0Services.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef WAVESIMULATOR0SERVICES_H_INCLUDED
#define WAVESIMULATOR0SERVICES_H_INCLUDED

#define SRVNAME_WaveSimulator0 "WaveSimulator0"

// TcCOM-ClassId of this module: c3576942-b34f-4c25-b323-6e15abd237e1
const   CTCID   CID_WaveSimulator0    =  {0xc3576942,0xb34f,0x4c25,{0xb3,0x23,0x6e,0x15,0xab,0xd2,0x37,0xe1}};

#endif


