// ****************** WaveSimulator0Ctrl.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef WAVESIMULATOR0CTRL_H_INCLUDED
#define WAVESIMULATOR0CTRL_H_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CWaveSimulator0DrvName "WaveSimulator0"

#include "WaveSimulator0Resource.h"
#include "WaveSimulator0W32.h"
#include "TcPch.h"
#include "CWaveSimulator0ClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CWaveSimulator0Ctrl :		public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CWaveSimulator0Ctrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CWaveSimulator0Ctrl, CWaveSimulator0ClassFactory>
{
public:
	CWaveSimulator0Ctrl() : ITcOCFCtrlImpl<CWaveSimulator0Ctrl, CWaveSimulator0ClassFactory>(){}

	virtual ~CWaveSimulator0Ctrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_WaveSimulator0Ctrl)
DECLARE_NOT_AGGREGATABLE(CWaveSimulator0Ctrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CWaveSimulator0Ctrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif
