// ****************** WaveSimulator0W32.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "TcPch.h"
#include "WaveSimulator0Ctrl.h"
#include "TcSysW32_i.c"

CComModule _Module;

const   CLSID   IID_WaveSimulator0Ctrl		=  {0xa4eadf3d,0x2208,0x46be,{0x90,0xd5,0x4e,0xc1,0x21,0x95,0x7b,0xa5}};
const   CLSID   LIBID_WaveSimulator0W32Lib	=  {0xa4eadf3d,0x2208,0x46be,{0x90,0xd5,0x4e,0xc1,0x21,0x95,0x7b,0xa5}};
const   CLSID   CLSID_WaveSimulator0Ctrl   =  {0xa4eadf3d,0x2208,0x46be,{0x90,0xd5,0x4e,0xc1,0x21,0x95,0x7b,0xa5}};

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_WaveSimulator0Ctrl, CWaveSimulator0Ctrl)
END_OBJECT_MAP()

/////////////////////////////////////////////////////////////////////////////
// DLL Entry Point

extern "C"
BOOL WINAPI DllMain(HANDLE hInstance, DWORD dwReason, LPVOID /*lpReserved*/)
{
	if (dwReason == DLL_PROCESS_ATTACH)
	{
		_Module.Init(ObjectMap, (HINSTANCE)hInstance);
#ifndef UNDER_CE
		DisableThreadLibraryCalls((HINSTANCE)hInstance);
#endif
	}
	else if (dwReason == DLL_PROCESS_DETACH)
		_Module.Term();
	return TRUE;    // ok
}

/////////////////////////////////////////////////////////////////////////////
// Used to determine whether the DLL can be unloaded by OLE

STDAPI DllCanUnloadNow(void)
{
	return (_Module.GetLockCount()==0) ? S_OK : S_FALSE;
}

/////////////////////////////////////////////////////////////////////////////
// Returns a class factory to create an object of the requested type

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
	return _Module.GetClassObject(rclsid, riid, ppv);
}

/////////////////////////////////////////////////////////////////////////////
// DllRegisterServer - Adds entries to the system registry

STDAPI DllRegisterServer(void)
{
	// registers object, typelib and all interfaces in typelib
	return _Module.RegisterServer(TRUE);
}

/////////////////////////////////////////////////////////////////////////////
// DllUnregisterServer - Removes entries from the system registry

STDAPI DllUnregisterServer(void)
{
	_Module.UnregisterServer();
	return S_OK;
}

/////////////////////////////////////////////////////////////////////////////
STDAPI DllGetTcCtrl(ITcCtrl** ppCtrl)
{
	if ( ppCtrl == NULL )
		return E_POINTER;

	CComObject<CWaveSimulator0Ctrl>* pCWaveSimulator0Ctrl = new CComObject<CWaveSimulator0Ctrl>();
	if (pCWaveSimulator0Ctrl == NULL) return E_POINTER;
	return pCWaveSimulator0Ctrl->QueryInterface(IID_ITcCtrl, reinterpret_cast<void**>(ppCtrl));
}