// ****************** WaveSimulator0Version.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef WAVESIMULATOR0VERSION_H_INCLUDED
#define WAVESIMULATOR0VERSION_H_INCLUDED

////////////////////////////////////////////////////////////////
//  Version Information
////////////////////////////////////////////////////////////////

#define TWINCAT_TARGET_VERSION  1.2.1237
#define MATLAB_RELEASE	"R2019a"

#endif
