function f = f(in1,Ts)
%F
%    F = F(IN1,TS)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    24-May-2018 11:13:19

c1 = in1(34,:);
eta1 = in1(1,:);
eta2 = in1(2,:);
eta3 = in1(3,:);
eta4 = in1(4,:);
eta5 = in1(5,:);
eta6 = in1(6,:);
l = in1(28,:);
l_t = in1(29,:);
p1 = in1(19,:);
p2 = in1(20,:);
p3 = in1(21,:);
p_t1 = in1(22,:);
p_t2 = in1(23,:);
p_t3 = in1(24,:);
p_tt1 = in1(25,:);
p_tt2 = in1(26,:);
p_tt3 = in1(27,:);
phi1 = in1(30,:);
phi2 = in1(31,:);
phi_t1 = in1(32,:);
phi_t2 = in1(33,:);
v1 = in1(7,:);
v2 = in1(8,:);
v3 = in1(9,:);
v4 = in1(10,:);
v5 = in1(11,:);
v6 = in1(12,:);
v_t1 = in1(13,:);
v_t2 = in1(14,:);
v_t3 = in1(15,:);
v_t4 = in1(16,:);
v_t5 = in1(17,:);
v_t6 = in1(18,:);
t2 = cos(eta5);
t3 = 1.0./t2;
t4 = sin(eta5);
t5 = cos(eta4);
t6 = sin(eta4);
t7 = sin(phi1);
t8 = 1.0./l;
t9 = cos(phi1);
f = [eta1+Ts.*v1;eta2+Ts.*v2;eta3+Ts.*v3;eta4+Ts.*(v4+t3.*t4.*t5.*v6+t3.*t4.*t6.*v5);eta5+Ts.*(t5.*v5-t6.*v6);t3.*(eta6.*t2+Ts.*t5.*v6+Ts.*t6.*v5);v1+Ts.*v_t1;v2+Ts.*v_t2;v3+Ts.*v_t3;v4+Ts.*v_t4;v5+Ts.*v_t5;v6+Ts.*v_t6;v_t1;v_t2;v_t3;v_t4;v_t5;v_t6;p1+Ts.*p_t1;p2+Ts.*p_t2;p3+Ts.*p_t3;p_t1+Ts.*p_tt1;p_t2+Ts.*p_tt2;p_t3+Ts.*p_tt3;p_tt1;p_tt2;p_tt3;l+Ts.*l_t;l_t;phi1+Ts.*phi_t1;phi2+Ts.*phi_t2;phi_t1-Ts.*t8.*(l_t.*phi_t1.*2.0+c1.*t7.*cos(phi2)+l.*phi_t2.^2.*t7.*t9);phi_t2-(Ts.*t8.*(c1.*sin(phi2)+l_t.*phi_t2.*t9.*2.0-l.*phi_t1.*phi_t2.*t7.*2.0))./t9;c1];
