// ****************** CHydroSimulatorDrv.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef CHYDROSIMULATORDRV_H_INCLUDED
#define CHYDROSIMULATORDRV_H_INCLUDED

#include "TcPch.h"

#define HydroSimulatorDRV_NAME			"HydroSimulator"
#define HydroSimulatorDRV_Major			1
#define HydroSimulatorDRV_Minor			0

#if defined DEVICE_MAIN		// is supposed to be __cplusplus

#define DEVICE_CLASS			CHydroSimulatorDrv

#include "ObjDriver.h"

class CHydroSimulatorDrv : public CObjDriver
{
public:
	virtual IOSTATUS	OnLoad( );
	virtual VOID		OnUnLoad( );
	
  //////////////////////////////////////////////////////
  // VxD-Services exported by this driver
  static unsigned long _cdecl HydroSimulator_GetVersion( );
};

#endif	// #if defined DEVICE_MAIN

Begin_VxD_Service_Table( HydroSimulatorDRV)
	VxD_Service( HydroSimulator_GetVersion		)
End_VxD_Service_Table


#endif
