// ****************** CHydroSimulatorClassFactory.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "stdafx.h"
#pragma hdrstop

#include "CHydroSimulator.h"
#include "CHydroSimulatorClassFactory.h"

// ITComClassFactory
BEGIN_CLASS_MAP(CHydroSimulatorClassFactory)
	CLASS_ENTRY_RT(CID_HydroSimulator,SRVNAME_HydroSimulator "!CHydroSimulator", CHydroSimulator)
END_CLASS_MAP()


CHydroSimulatorClassFactory::CHydroSimulatorClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_HydroSimulator)); 
}

