// ****************** CHydroSimulatorDrv.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop
#define DEVICE_MAIN

#include "CHydroSimulatorDrv.h"
#include "CHydroSimulator.h"
#include "CHydroSimulatorClassFactory.h"
#include "HydroSimulatorVersion.h"

DECLARE_GENERIC_DEVICE(HydroSimulatorDRV)
#undef DEVICE_MAIN

IOSTATUS CHydroSimulatorDrv::OnLoad( )
{
	TRACE(_T("CHydroSimulatorClassFactory::OnLoad()\n") );
	m_pObjClassFactory = new CHydroSimulatorClassFactory();

	return IOSTATUS_SUCCESS;
}

VOID CHydroSimulatorDrv::OnUnLoad( )
{
	delete m_pObjClassFactory;
}

unsigned long _cdecl CHydroSimulatorDrv::HydroSimulator_GetVersion( )
{
	return(0);
}