// ****************** HydroSimulatorServices.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef HYDROSIMULATORSERVICES_H_INCLUDED
#define HYDROSIMULATORSERVICES_H_INCLUDED

#define SRVNAME_HydroSimulator "HydroSimulator"

// TcCOM-ClassId of this module: 1ddd7197-7f96-43a8-9f9f-ee8f6b630dc0
const   CTCID   CID_HydroSimulator    =  {0x1ddd7197,0x7f96,0x43a8,{0x9f,0x9f,0xee,0x8f,0x6b,0x63,0x0d,0xc0}};

#endif


