// ****************** HydroSimulatorCtrl.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2019a (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1237
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef HYDROSIMULATORCTRL_H_INCLUDED
#define HYDROSIMULATORCTRL_H_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CHydroSimulatorDrvName "HydroSimulator"

#include "HydroSimulatorResource.h"
#include "HydroSimulatorW32.h"
#include "TcPch.h"
#include "CHydroSimulatorClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CHydroSimulatorCtrl :		public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CHydroSimulatorCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CHydroSimulatorCtrl, CHydroSimulatorClassFactory>
{
public:
	CHydroSimulatorCtrl() : ITcOCFCtrlImpl<CHydroSimulatorCtrl, CHydroSimulatorClassFactory>(){}

	virtual ~CHydroSimulatorCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_HydroSimulatorCtrl)
DECLARE_NOT_AGGREGATABLE(CHydroSimulatorCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CHydroSimulatorCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif
