<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="FB_WinchInterface" Id="{b40b1ebc-2802-44ba-aaac-015fbf2974fe}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_WinchInterface
VAR_INPUT
	
END_VAR
VAR_OUTPUT
END_VAR
VAR
	axis1 : AXIS_REF;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_WinchInterface">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>