<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="MAIN" Id="{4193d1f4-5b8a-4d46-8bb1-f5443e3607b6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	txHmi : ST_TxHmi;
	
	counter : DINT;

	em8000 : FB_StewartInterface(3232258590, 50030, 50040, ADR(txHmi.em8000));
	em1500 : FB_StewartInterface(3232258591, 50031, 50041, ADR(txHmi.em1500));
	
	comau : FB_ComauInterface(3232258592, 50032, 50042);
	
	mru1 : FB_MruInterface(7551);
	mru2 : FB_MruInterface(7552);

	
	test : POINTER TO FB_StewartInterface;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[counter := counter + 1;

em8000();
em1500();
comau();
mru1();
mru2();


txHmi.t := txHmi.t + 0.005;




]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="109" Count="0" />
      <LineId Id="127" Count="0" />
      <LineId Id="110" Count="0" />
      <LineId Id="120" Count="0" />
      <LineId Id="145" Count="0" />
      <LineId Id="141" Count="1" />
      <LineId Id="169" Count="0" />
      <LineId Id="172" Count="0" />
      <LineId Id="170" Count="0" />
      <LineId Id="168" Count="0" />
      <LineId Id="129" Count="0" />
      <LineId Id="128" Count="0" />
      <LineId Id="121" Count="0" />
      <LineId Id="17" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>