<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="TEST" Id="{f2edba56-12f7-486d-8838-64932ca9e828}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TEST
VAR
	csvReader : FB_CsvReader;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

csvReader();]]></ST>
    </Implementation>
    <LineIds Name="TEST">
      <LineId Id="7" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>