<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="MAIN" Id="{841967ed-ee1e-4fd2-acd5-2d10c3ac666f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	// Remote Interface	
	remote				: FB_Remote(3232258620, 50060, 50050);
	
	// EtherCAT equipment
	at960				: FB_Leica;
	
	// UDP Equipment
	em1500				: FB_Stewart(3232258591, 50031, 50041, ADR(HMI.feedback.em1500));
	em8000				: FB_Stewart(3232258590, 50030, 50040, ADR(HMI.feedback.em8000));
	comau				: FB_Comau(3232258592, 50032, 50042);
	mru1				: FB_MotionReferenceUnit(7551);
	mru2				: FB_MotionReferenceUnit(7552);
	
	counter				: UDINT := 0;

	
END_VAR
	]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Exchange remote data
remote();

// Update EtherCAT equipment
at960();

// Update UDP equipment
em1500();
em8000();
comau();
mru1();
mru2();

// Increment main counter
counter := counter + 1;





]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="534" Count="0" />
      <LineId Id="532" Count="1" />
      <LineId Id="3" Count="0" />
      <LineId Id="401" Count="0" />
      <LineId Id="531" Count="0" />
      <LineId Id="530" Count="0" />
      <LineId Id="539" Count="0" />
      <LineId Id="545" Count="0" />
      <LineId Id="542" Count="1" />
      <LineId Id="536" Count="1" />
      <LineId Id="126" Count="0" />
      <LineId Id="421" Count="0" />
      <LineId Id="465" Count="0" />
      <LineId Id="52" Count="0" />
      <LineId Id="27" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="51" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>