# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 441)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 30, 301, 271))
        self.groupBox.setObjectName("groupBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 101, 20))
        self.label_6.setObjectName("label_6")
        self.comau_u_4 = QtWidgets.QSlider(self.groupBox)
        self.comau_u_4.setGeometry(QtCore.QRect(130, 193, 160, 22))
        self.comau_u_4.setMinimum(-100)
        self.comau_u_4.setMaximum(100)
        self.comau_u_4.setOrientation(QtCore.Qt.Horizontal)
        self.comau_u_4.setObjectName("comau_u_4")
        self.comau_u_5 = QtWidgets.QSlider(self.groupBox)
        self.comau_u_5.setGeometry(QtCore.QRect(130, 232, 160, 22))
        self.comau_u_5.setMinimum(-100)
        self.comau_u_5.setMaximum(100)
        self.comau_u_5.setOrientation(QtCore.Qt.Horizontal)
        self.comau_u_5.setObjectName("comau_u_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 69, 101, 20))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 151, 101, 20))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 111, 101, 20))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 101, 20))
        self.label.setObjectName("label")
        self.comau_u_1 = QtWidgets.QSlider(self.groupBox)
        self.comau_u_1.setGeometry(QtCore.QRect(130, 72, 160, 22))
        self.comau_u_1.setMinimum(-100)
        self.comau_u_1.setMaximum(100)
        self.comau_u_1.setOrientation(QtCore.Qt.Horizontal)
        self.comau_u_1.setObjectName("comau_u_1")
        self.comau_u_3 = QtWidgets.QSlider(self.groupBox)
        self.comau_u_3.setGeometry(QtCore.QRect(130, 152, 160, 22))
        self.comau_u_3.setMinimum(-100)
        self.comau_u_3.setMaximum(100)
        self.comau_u_3.setOrientation(QtCore.Qt.Horizontal)
        self.comau_u_3.setObjectName("comau_u_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 192, 101, 20))
        self.label_5.setObjectName("label_5")
        self.comau_u_0 = QtWidgets.QSlider(self.groupBox)
        self.comau_u_0.setGeometry(QtCore.QRect(130, 32, 160, 22))
        self.comau_u_0.setMinimum(-100)
        self.comau_u_0.setMaximum(100)
        self.comau_u_0.setOrientation(QtCore.Qt.Horizontal)
        self.comau_u_0.setObjectName("comau_u_0")
        self.comau_u_2 = QtWidgets.QSlider(self.groupBox)
        self.comau_u_2.setGeometry(QtCore.QRect(130, 112, 160, 22))
        self.comau_u_2.setMinimum(-100)
        self.comau_u_2.setMaximum(100)
        self.comau_u_2.setOrientation(QtCore.Qt.Horizontal)
        self.comau_u_2.setObjectName("comau_u_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 310, 301, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 30, 101, 20))
        self.label_11.setObjectName("label_11")
        self.winch_u = QtWidgets.QSlider(self.groupBox_2)
        self.winch_u.setGeometry(QtCore.QRect(130, 32, 160, 22))
        self.winch_u.setMinimum(-100)
        self.winch_u.setMaximum(100)
        self.winch_u.setOrientation(QtCore.Qt.Horizontal)
        self.winch_u.setObjectName("winch_u")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Comau Speed Input"))
        self.label_6.setText(_translate("MainWindow", "Comau qDotRef[5]"))
        self.label_2.setText(_translate("MainWindow", "Comau qDotRef[1]"))
        self.label_4.setText(_translate("MainWindow", "Comau qDotRef[3]"))
        self.label_3.setText(_translate("MainWindow", "Comau qDotRef[2]"))
        self.label.setText(_translate("MainWindow", "Comau qDotRef[0]"))
        self.label_5.setText(_translate("MainWindow", "Comau qDotRef[4]"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Winch Speed Input"))
        self.label_11.setText(_translate("MainWindow", "Winch qDotRef"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

